### ISSUE TITLE
search crashes after running a GPTMD task

### ISSUE THREAD

**Issue by Dmorgen** [smith-chem-wisc/MetaMorpheus#1012]
Please see the attached file. GPTMD task seems to have been concluded successfully.

Thanks!
David.

[results.txt](https://github.com/smith-chem-wisc/MetaMorpheus/files/1779726/results.txt)

**Comment by Dmorgen** [comment]
And now it fails when trying to search alone with the XML from the GPTMD XML...
[results.txt](https://github.com/smith-chem-wisc/MetaMorpheus/files/1779796/results.txt)

**Comment by rmillikin** [comment]
Hello David,

The crash seems to be occurring while performing the in silico GPTMD database digestion. Can you please upload your database and share it with us?

Thanks,
Rob

**Comment by Dmorgen** [comment]
The one that GPTMD prepares?

**Comment by rmillikin** [comment]
Yes, please

**Comment by rmillikin** [comment]
You may email a link to me at rmillikin@wisc.edu

**Comment by rmillikin** [comment]
This digests OK with me for trypsin, but semi-trypsin is causing a crash. We'll look into this and report back; thanks for your patience.

**Comment by rmillikin** [comment]
fixed in #1016 . This will be included in v0.0.271. Going to keep this issue open until that release is made.

**Comment by rmillikin** [comment]
Fixed in the latest release! Feel free to reopen this issue or make a new one if you encounter the same problem.
