### ISSUE TITLE
Generate aggregateQuantifiedProteins.tsv

### ISSUE THREAD

**Issue by zrolfs** [smith-chem-wisc/MetaMorpheus#1013]
MM quantification currently outputs quantified peaks, baseSeqs, and fullSeqs, but users are interested in protein quantification, not peptide quantification.

**Comment by rmillikin** [comment]
This is already in the aggregateProteinGroups file; there should be an intensity column for each raw file

**Comment by zrolfs** [comment]
That's great! We should be sure to include that in the wiki.
