### ISSUE TITLE
Question re GPTMD

### ISSUE THREAD

**Issue by Dmorgen** [smith-chem-wisc/MetaMorpheus#1018]
I'm seeing many more modifications found in GPTMD, than the subsequent regular search done on the XML it generated. does that a result of the FDR? is any FDR done on the GPTMD?

Thanks,
David.

**Comment by trishorts** [comment]
psms results from gptmd should be ignored. Actually don't think we should even provide them. GPTMD should be followed up with regular search using the gptmd database. Those are the results to focus on.

Incidentally, are you guys going to ushupo? I'd love to touch base and share notes. Your team is doing some amazing work!

**Comment by Dmorgen** [comment]
Thanks for compliments :) no, we'll be coming to ASMS though... if you're there, we definitely would like to meet!

**Comment by trishorts** [comment]
We'll be there. I'll send you a mail closer to the time.
