### ISSUE TITLE
make the command line version work

### ISSUE THREAD

**Issue by stefanks** [smith-chem-wisc/MetaMorpheus#102]

**Comment by stefanks** [comment]
Pass in a list of params files for tasks in order, a list of spectra files and a list of database files. Need to somehow be able to specify contaminant dbs.
Also, this means that task params files should not have spectra/db files in them, because those are determined dynamically for subsequent tasks.

**Comment by acesnik** [comment]
Because all consecutive tasks reference the same output folder, you could use that as a way to string together tasks. For example, if the first task was to calibrate, a following GPTMD task would use the mzMLs in the first task's output folder, as long as the GPTMD command referenced the folder above that one. 

Contaminant DBs could have a different flag than protein DBs for the organism.

**Comment by stefanks** [comment]
Tasks are already stringed together that way in MetaMorpheus. If calibration is followed by a search, then newly calibrated files are used in the search. If G-PTM-D is followed by a search, the new augmented database is used in the search, etc. 

I imagine a command line call looking like:

`mm.exe -t task1.txt task2.txt -s spectra1.raw spectra2.raw -db proteinDb.xml`

**Comment by stefanks** [comment]
Let's use the rule 
`
            if (fileName.ToUpper().Contains("contaminant".ToUpper())
                || fileName.ToUpper().Contains("crap".ToUpper()))
                Contaminant = true;
`

Otherwise, everything is set up! Only thing left is to populate the taskList, startingRawFilenameList , and startingXmlDbFilenameList from command line arguments!

Will gladly accept any pull request that implements this.

**Comment by acesnik** [comment]
Should we use case-sensitive checking for "cRAP" databases, since "crap" is a fairly common substring?

**Comment by stefanks** [comment]
Anthony, I agree. Going forward with that.

**Comment by stefanks** [comment]
Done https://github.com/smith-chem-wisc/MetaMorpheus/commit/90145674794b03ff571f54d6debb88128ad5ec62
