### ISSUE TITLE
Wiki Revamp

### ISSUE THREAD

**Issue by rmillikin** [smith-chem-wisc/MetaMorpheus#1029]
The wiki is quite outdated and missing a lot of info. As MetaMorpheus becomes increasingly stable, I'd like to codify information about MetaMorpheus. This is a very open-ended issue and will probably never be fully resolved but I think we can get 90% of the way there fairly easily.

**Comment by acesnik** [comment]
Should we do this on the regular? We tend to add features regularly, and as a group we could probably just schedule the writing.

**Comment by trishorts** [comment]
add explanation of complementary ions
