### ISSUE TITLE
Is Classic Search Still Useful?

### ISSUE THREAD

**Issue by zrolfs** [smith-chem-wisc/MetaMorpheus#1032]
Is there a reason to keep using classic search (ie is it faster in some instances), or should we switch everything over to modern?
It would make the GUI less confusing to only have one type of search mode.

**Comment by rmillikin** [comment]
modern search requires making the fragment index which is several gigabytes. some users (e.g., me) may value their hard drive space and don't want to make an index for each organism+search type combination

**Comment by zrolfs** [comment]
We could have a default option of wiping the index after the run? It seems like a small sacrifice.

**Comment by rmillikin** [comment]
pretty sure classic search is faster in most types of searches except open-mass searches. could be wrong though. takes a long time to make the fragment index. I'm just not sure what the benefit is here. a tooltip briefly explaining the difference between classic and modern and some more detailed info on the wiki seems adequate

**Comment by rmillikin** [comment]
if we're looking to revamp the GUI I'd advocate for some features hidden behind an "advanced options" button, plus some more guidance for modification selection (GPTMD vs variable, etc). those are the biggest hangups for most users. I don't think we should just remove core functionality

**Comment by zrolfs** [comment]
The main question was "is there a situation where classic search is faster than modern search". I'm not really looking to revamp the GUI with this. Talking with Alexey, he said that MSFragger was able to easily handle nonspecific/semispecific searches, which is something we currently struggle with for classic searches. We also have significantly more theoretical peptides with our GPTMD databases, which are noticeably slower searches after adding those mods.

**Comment by rmillikin** [comment]
feel free to run some benchmarks. the classic search is intended for standard searches, i.e. searching standard bottom-up data. there are of course cases like nonspecific or open-mass searches when modern search is superior. RAM usage is also a factor in modern search. I'd like to see data for that in classic vs. modern. in modern you can use DB partitions but you need to know what you're doing there, i.e. how many partitions should I use?

**Comment by Dmorgen** [comment]
Modern search crashed multiple times on me while classic didn't. generally speaking both GPTMD and the search tend to eat up the memory to a stall (128GB system), unless I tell it to conserve memory(in both searches). In this case it doesn't crash but it uses only 30% of available RAM.

**Comment by rmillikin** [comment]
Yes
