### ISSUE TITLE
Fraction analysis

### ISSUE THREAD

**Issue by Dmorgen** [smith-chem-wisc/MetaMorpheus#1033]
I know the wiki contains a section about fractions but I couldn't understand it well - is there a way to tell the software to sum up fraction to a single column output (LFQ, #PSMs, etc.)?

Thanks!
David.

**Comment by rmillikin** [comment]
Not yet, no; I'm actually working on that now, actually. The difficulty is in normalizing the fractions. But we'd like to have the user input the conditions, biological rep, tech rep, and fraction info for each file and sum/normalize appropriately to make quantitative analysis easier. So hold tight!

**Comment by rmillikin** [comment]
I'm going to close this issue and merge with issue #291.
