### ISSUE TITLE
No reporting of modification and cross-linker masses

### ISSUE THREAD

**Issue by mriffle** [smith-chem-wisc/MetaMorpheus#1035]
Greetings,

I maintain a resource called proxl for visualization and sharing cross-linking proteomics data (http://proxl-ms.org/). I've received a request from a user to support the importing of data generated by MetaMorpheus cross-linking search results. To do this, I need to convert the results of MetaMorpheus to proxl XML. I plan on writing a robust converter and hosting it on GitHub at https://github.com/yeastrc/proxl-import-metamorpheus and listing MetaMorpheus as a supported pipeline on our website.

However, there are some values required by proxl that I am having a hard time locating in the MetaMorpheus search results--specifically fixed modification and "deadend" masses. When viewing the pepXML file, I do see:

      <parameter name="Cross-linker mass" value="138.06808" />

Which is great. However, for Fixed Modifications I see:

      <parameter name="Fixed Modifications" value="Carbamidomethyl of C.Carbamidomethyl of U." />

Which doesn't tell me much about what masses MetaMorpheus used to search for those modifications. Likewise, variable modifications are reported as:

      <parameter name="Variable Modificaions" value="Oxidation of M." />

Would it be possible for MetaMorpheus to output the actual calculated value it is using to search for all of these modifications--either in the pepXML file or as a separate output file.  Ideally all of the following mod masses would be reported:

 * fixed modifications
 * variable modifications
 * cross-linker cross-link mass(es)
 * cross-linker loop-link mass(es)
 * cross-linker mono-link/deadend mass(es)

Without reporting these masses, I'll have to hard code some specific values into the converter and only support, perhaps, a couple cross-linkers and the common fixed and dynamic mods defined by MetaMorpheus--which would be considerably less robust.

Thanks.

**Comment by lonelu** [comment]
Hi mriffle,  Thanks for supporting MetaMorpheus Crosslink. 
It is easy for me to add cross-linker related masses. However, the change of fixed modifications and variable modifications may change the results of other MetaMorpheus tasks. I will figure this out and get back to you ASAP.

**Comment by rmillikin** [comment]
Status on this issue?

**Comment by lonelu** [comment]
Please close this one. Thanks.
