### ISSUE TITLE
No loop-links or mono-links/deadends reported in pepXML file

### ISSUE THREAD

**Issue by mriffle** [smith-chem-wisc/MetaMorpheus#1036]
I am unable to find any loop-links or mono-links reported in the pepXML file after performing a cross-linking search--however, I do see them in the allPsms.mytsv file. 

Thanks.

**Comment by lonelu** [comment]
Hi mriffle, MetaMopheusXL currently doesn't report loop-links and mono-links in pepXML. Thoes information are not as valueable as inter- or intra-links. 
As there is a need for thoes, we will include them in pepXML and let you konw.

**Comment by mriffle** [comment]
Thanks for the response. As for value, we have found having the loop-links, mono-links, and unlinked identifications are very important for evaluating the experiment. PepXML does support including these, so hopefully it won't be too hard to implement.

I could, in theory, just use the outputted PSM text file (which does contain everything), but would prefer to parse pepXML if possible as the data is much more reliably organized than a tab delimited text file.

**Comment by lonelu** [comment]
Hi mriffle. I think I solved the two request. I need to do some uint tests to better maintain the code. Please wait for the a release in a few days. Thanks

**Comment by rmillikin** [comment]
Is there a "maintainer" of pepXML? can we suggest/request that deadend be made a valid pepXML tag?

**Comment by mriffle** [comment]
Greetings, wasn't sure if I should start a new issue for this or report it as part of this thread.

I am looking at pepXML output with 0.0.273.0  I see loop-links and unlinked peptides in here now, which is fantastic.

However, for loop-links, the linked position in the peptide are not being reported. Here is an example:

        <search_hit hit_rank="1" peptide="NPPINTKSQAVKDR" peptide_prev_aa="K" peptide_next_aa="A" protein="A_6" num_tot_proteins="1" calc_neutral_pep_mass="1708.94189" massdiff="0.00672069323670144" xlink_type="loop">
          <modification_info />
          <xlink identifier="DSS" mass="138.068085">
            <linked_peptide num_tot_proteins="0" calc_neutral_pep_mass="0" complement_mass="0">
              <xlink_score name="xlscore" value="0" />
            </linked_peptide>
          </xlink>
          <search_score name="xlTotalScore" value="7" />
          <search_score name="Qvalue" value="0.0487804878048781" />
        </search_hit>

Here is how I have seen the linked positions of loop-links reported in other programs:

        <search_hit hit_rank="1" peptide="NPPINTKSQAVKDR" peptide_prev_aa="K" peptide_next_aa="A" protein="A_6" num_tot_proteins="1" calc_neutral_pep_mass="1708.94189" massdiff="0.00672069323670144" xlink_type="loop">
          <modification_info />
          <xlink identifier="DSS" mass="138.068085">
              <xlink_score name="link" value="8"/>         
              <xlink_score name="link" value="13"/>       
          </xlink>
          <search_score name="xlTotalScore" value="7" />
          <search_score name="Qvalue" value="0.0487804878048781" />
        </search_hit>

(Also note that there is no <linked_peptide></linked_peptide> element for loop-links in this example, but that's a minor thing.)

**Comment by lonelu** [comment]
Thanks for the comment. I will add that information.  What will be in ?

**Comment by mriffle** [comment]
In a similar vein as above, I think I see where deadends/mono-links are in the pepXML now, but the position isn't being reported. For example:

      <search_result>
        <search_hit hit_rank="1" peptide="WVQVHELKEHNGQVTGIDWAPDSNR" peptide_prev_aa="K" peptide_next_aa="I" protein="A_2" num_tot_proteins="1"
             calc_neutral_pep_mass="3074.519" massdiff="156.078884989733" xlink_type="na">
          <modification_info />
          <search_score name="xlTotalScore" value="7" />
          <search_score name="Qvalue" value="0.00916496945010183" />
        </search_hit>
      </search_result>

I think this is a deadend with a linker mass of 156.078884989733--but the actual residue with the linker isn't reported.

This is how I've seen it done:

      <search_result>
        <search_hit hit_rank="1" peptide="WVQVHELKEHNGQVTGIDWAPDSNR" peptide_prev_aa="K" peptide_next_aa="I" protein="A_2" num_tot_proteins="1"
             calc_neutral_pep_mass="3074.519" massdiff="156.078884989733" xlink_type="na">
         <modification_info>
             <mod_aminoacid_mass position="9" mass="156.078884989733"/>  
         </modification_info>
          <search_score name="xlTotalScore" value="7" />
          <search_score name="Qvalue" value="0.00916496945010183" />
        </search_hit>
      </search_result>

Hope this makes sense and is helpful.

There is some discussion on whether the reported mod masses are just the mass difference of the residue (like in the example above), or the total mass of the modded residue (residue mass + linker mass). I prefer the former, but I think the latter was used when pepXML cross-linking support was published--I don't really know if one or the other is formally expected.

**Comment by mriffle** [comment]
@lonelu re: "Thanks for the comment. I will add that information. What will be in ?"

Can you clarify what you mean by your final question?

**Comment by lonelu** [comment]
Sorry to confuse you, I have no question now. I just got the idea(" search_score name="xlTotalScore" value="7" " The value is the link position reported. ).
I actually used the Mod mass. (As depicted in the picture below)
![image](https://user-images.githubusercontent.com/10702896/37937479-7b3f92b4-311f-11e8-882c-2d67ec41cde0.png)

**Comment by mriffle** [comment]
Though I'm not 100% sure I understand correctly, I take your response to mean that for the following searchHit:

  <search_result>
    <search_hit hit_rank="1" peptide="WVQVHELKEHNGQVTGIDWAPDSNR" peptide_prev_aa="K" peptide_next_aa="I" protein="A_2" num_tot_proteins="1"
         calc_neutral_pep_mass="3074.519" massdiff="156.078884989733" xlink_type="na">
      <modification_info />
      <search_score name="xlTotalScore" value="7" />
      <search_score name="Qvalue" value="0.00916496945010183" />
    </search_hit>
  </search_result>

That this is a deadend/mono-link, where the linker has a mass of 156.078884989733 and it is at position 7 in the peptide.

If this is true, I just wanted to offer up an opinion that this is not really an optimal way to include deadend hits. By replacing the normal value of "xlTotalScore" with the position of the linker, the actual score for that PSM is no longer available. This means that the PSM score is available for every hit except for deadends... It also means that the massdiff is treated specially for deadends, and no longer means what it means for every other type of PSM.

I'd urge you to treat the massdiff and xlTotalScore the same as all other types of PSMs so that the file can be processed consistently for bioinformatics purposes (which I'm doing now). And that the mass and position of the dead-end linker be included as a modification like I suggested above.

**Comment by lonelu** [comment]
Thanks for your suggestions. I think your way is more clear. I am working with this now. Please wait for a new release.

**Comment by lonelu** [comment]
The new pep.XML output for loop and deadend crosslinks looks like:
        <search_hit hit_rank="1" peptide="LKKVEEEENAATLQLGQEFQLK" peptide_prev_aa="R" peptide_next_aa="Q" protein="P20433" num_tot_proteins="1" calc_neutral_pep_mass="2686.43359" massdiff="0.00292382131257796" xlink_type="loop">
          <modification_info />
          <xlink identifier="DSS" mass="138.068085">
            <linked_peptide num_tot_proteins="0" calc_neutral_pep_mass="0" complement_mass="0">
              <xlink_score name="link" value="2" />
              <xlink_score name="link" value="3" />
            </linked_peptide>
          </xlink>
          <search_score name="xlTotalScore" value="7.015700223807" />
          <search_score name="Qvalue" value="0" />
        </search_hit>

        <search_hit hit_rank="1" peptide="VVMMKYDR" peptide_prev_aa="R" peptide_next_aa="K" protein="P04050" num_tot_proteins="1" calc_neutral_pep_mass="1198.60718" massdiff="-0.000683485663103056" xlink_type="na">
          <modification_info>
            <mod_aminoacid_mass position="5" mass="156.0786" />
          </modification_info>
          <search_score name="xlTotalScore" value="2.01299051776669" />
          <search_score name="Qvalue" value="0" />
        </search_hit>

Please let me know if you have further suggestions. Or we will release a new version soon.

**Comment by rmillikin** [comment]
I think this is finished, yes? Let me know if I should reopen this issue, or feel free to make a new one.
