### ISSUE TITLE
XLSearch: Disulfide bond searches suffer from deconvolution issues

### ISSUE THREAD

**Issue by zrolfs** [smith-chem-wisc/MetaMorpheus#1037]
Disulfide bonds result in the loss of two hydrogen atoms. When a peptide of z=2 is incorrectly assigned as z=4, XLSearch incorrectly assigns the peptide as crosslinked to itself. This is currently intra, but should be inter (because the protein would have to xlink to a different protein). We need some sort of flag to prevent this, as it's rather common.

Shown below are top 20 intra XLPSMs
Pep1 Base   sequence(crosslink site) | Pep2 Base sequence(crosslink site)
-- | --
SNVNDGVAQSTRIIYGGSVTGATCKELASQPDVDGFLVGGASLKPEFVDIINAK(25) | SNVNDGVAQSTRIIYGGSVTGATCKELASQPDVDGFLVGGASLKPEFVDIINAK(25)
KELSEPSSTRIYAIAKALENNMSLDEIVRLTSIDK(1) | KELSEPSSTRIYAIAKALENNMSLDEIVRLTSIDK(1)
QHGIPIPVTPKSPWSMDENLMHISYEAGILENPK(11) | GRNDLMEYAKQHGIPIPVTPKSPWSMDENLMHISYEAGILENPK(21)
CDIDIRKDLYANNVMSGGTTMYPGIADRMQK(7) | CDIDIRKDLYANNVMSGGTTMYPGIADRMQK(7)
DGTTRTTSLELFMYLNEVAGK(21) | DGTTRTTSLELFMYLNEVAGK(21)
AGYTDQVVIGMDVAASEFYRSGKYDLDFK(23) | AGYTDQVVIGMDVAASEFYRSGKYDLDFKSPDDPSRYITPDQLADLYK(29)
GSINAMRFLTTVSMEQPEMLEK(22) | GSINAMRFLTTVSMEQPEMLEKVSREIWMRVWSRDEDITEYQSILAAAVK(50)
IPRSTLSALVNGKPYKVTPTIEDPSIFGHIEEVLK(13) | PYKVTPTIEDPSIFGHIEEVLK(3)
DAIIAKLANQAADYFGDAFK(6) | MKDAIIAKLANQAADYFGDAFK(2)
EQTKLKWMQSELNVEEVVNDRSWK(6) | EQTKLKWMQSELNVEEVVNDRSWK(6)
MKRLGSDLTSAQKEMK(2) | MKRLGSDLTSAQKEMK(2)
EEKGLSLEGFQLTGLSEPSLQKSSIDLSTEK(22) | EEKGLSLEGFQLTGLSEPSLQKSSIDLSTEK(22)
SLGGVQPSQTIQPKVETDAAQAAVQSAFAVLLTQLIKAQQSK(37) | SLGGVQPSQTIQPKVETDAAQAAVQSAFAVLLTQLIKAQQSK(37)
MRDILNMDKTLKGLNSDSVTEETLRK(9) | MRDILNMDKTLK(9)
GASLYDLLGKEVELRELRTEAIARPLEINETEKVMRIAIK(10) | GASLYDLLGKEVELRELRTEAIARPLEINETEKVMRIAIK(10)
EVDEQMLNVQNKNSSYFVEWIPNNVK(12) | NMMAACDPRHGRYLTVAAVFRGRMSMKEVDEQMLNVQNKNSSYFVEWIPNNVK(27)
ALVDKWPDFNTVVVRPQEQEMTDDLDFYINTYQVYSK(5) | ALVDKWPDFNTVVVRPQEQEMTDDLDFYINTYQVYSK(37)
LQGWTPMPNVRRATTQPPSLSLRKMKTALPQEEQK(26) | LQGWTPMPNVRRATTQPPSLSLRKMKTALPQEEQK(26)
SLTGAKDLTKNAEVVAGTGEQCLPFDEARCGDGGK(10) | SLTGAKDLTKNAEVVAGTGEQCLPFDEARCGDGGK(10)

**Comment by zrolfs** [comment]
One fix might be to remove MS2 fragments found by the alpha peptide to prevent rematching to that peptide in the beta search?

**Comment by rmillikin** [comment]
@zrolfs suggestion was implemented in #1449 

I don't really have enough disulfide data to test the results

**Comment by zrolfs** [comment]
I think it can be tested without disulfide data. The issue was that unmodified (not XL) peptides were being called as crosslinked, so we should no longer see this when analyzing alkylated peptides.

**Comment by rmillikin** [comment]
This was fixed a while back. We disallowed a beta peptide from matching to the same peak as an alpha peptide.
