### ISSUE TITLE
What is the difference between the .exe and .msi releases?

### ISSUE THREAD

**Issue by zrolfs** [smith-chem-wisc/MetaMorpheus#1038]
.msi is a nice installer, .exe is giving me weird issues.

**Comment by rmillikin** [comment]
Should be the same. I'll try out the .exe tonight on another machine

**Comment by lonelu** [comment]
.exe seems like not working on certain computer.  Also, if .exe exist, people won't use .msi

**Comment by rmillikin** [comment]
I've just nixed the .exe installer and recommended users use the .msi.
