### ISSUE TITLE
Save toml imidiately; 'file parameter' and 'task' confuse the 'search (task) parameter'

### ISSUE THREAD

**Issue by lonelu** [smith-chem-wisc/MetaMorpheus#1040]
.toml could be saved imidiately instead of starting run. 
Also, 'file parameter' and 'task' confuse the 'search (task) parameter'

**Comment by zrolfs** [comment]
This is somewhat tricky, as a spectra file is required to know where to make the output folder. We could have all of the tomls written as soon as "run all tasks" is pressed?

**Comment by rmillikin** [comment]
I'm attempting something in #1905 that should resolve this. you should be able to right-click a task in the GUI and export it as a .toml (even before the tasks are run). it will just pop up with a "save as" screen to let you pick a save location.

**Comment by rmillikin** [comment]
I successfully implemented right-click -> save .toml in #1905. i'll reopen this issue if there is some unforeseen problem that makes this not possible to release.
