### ISSUE TITLE
"Max Modification Isoforms" RAM problems

### ISSUE THREAD

**Issue by XRSHEERAN** [smith-chem-wisc/MetaMorpheus#1042]
With a GPTMD database (lots of PTMs annotated), the default number of mod isoforms (4096) is far too high. The RAM on our 128gb machine maxes out quickly even analyzing only one spectra file. The repercussions of setting the max mod isoforms lower (e.g., 20) is ??

**Comment by trishorts** [comment]
limit to two non-fixed mods per peptide by default

**Comment by trishorts** [comment]
eliminate or limit combinations notches.

**Comment by rmillikin** [comment]
fixed in #1044 by restructuring the parallelization of the classic search engine. also set the num mods per peptide (not counting fixed mods) to 2 by default (the user can change this in the GUI if desired). the number of mod isoforms has also been changed to 1024 by default
