### ISSUE TITLE
Better pre-processing of data

### ISSUE THREAD

**Issue by zrolfs** [smith-chem-wisc/MetaMorpheus#1056]
![image](https://user-images.githubusercontent.com/16883585/38049948-25c6e488-328f-11e8-9302-c0995734dc3a.png)

**Comment by trishorts** [comment]
step one is something close to deconvolution, correct? which i think we have tried and would like to continue to try. can you say more about the algorithm that clusters? I can think of good ways and bad ways of doing it. not convinced without data that it results in both more and better identifications.

**Comment by rmillikin** [comment]
is this similar to #673? should I close one?

**Comment by zrolfs** [comment]
You're right; this is a repeat.
