### ISSUE TITLE
Set default program for TSV files to Excel during installation

### ISSUE THREAD

**Issue by acesnik** [smith-chem-wisc/MetaMorpheus#1082]
http://proteomicsnews.blogspot.com/2018/04/boring-stuff-thursday-2-how-to-make.html

**Comment by zrolfs** [comment]
Wait, we output .psmtsv which is a different extension than .tsv (despite being the same structure). We could automatically (without asking for permission) make .psmtsv defaulted to excel in the installer. This requires that the user has excel installed, though.

**Comment by acesnik** [comment]
Yes, agreed! And yes, if they don't have Excel installed, there's not much to do here.

**Comment by acesnik** [comment]
https://stackoverflow.com/a/2808320/9454443

**Comment by rmillikin** [comment]
done in #1335
