### ISSUE TITLE
Modifications not making it into ProteinGroups

### ISSUE THREAD

**Issue by zrolfs** [smith-chem-wisc/MetaMorpheus#1086]
The below peptide was not included:
TSAK[UniProt:N6-acetyllysine]EEDAFHFVSYVPVNGR|TSAK[Mod:Acetyl on K]EEDAFHFVSYVPVNGR

Unsure if ambiguity issue or other. Unmodified version made it in.

**Comment by zrolfs** [comment]
Is there another issue open for Uniprot Acetyl vs Mod acetyl? We could tag it as that.

**Comment by rmillikin** [comment]
#819
