### ISSUE TITLE
should be discontinue releasing the portable version

### ISSUE THREAD

**Issue by trishorts** [smith-chem-wisc/MetaMorpheus#1096]
to mitigate user installation problems?  I'm not sure there is justification for keeping it. Not to mention, people may grab that version not know that .msi means installer. I didn't.

**Comment by rmillikin** [comment]
Yeah; all the old portable versions would still exist.

**Comment by rmillikin** [comment]
I've nixed the portable GUI, let me know if you want it enabled again
