### ISSUE TITLE
Peptide Output: Reclaim PSM information.

### ISSUE THREAD

**Issue by zrolfs** [smith-chem-wisc/MetaMorpheus#1098]
We currently show the highest scoring scan for a unique peptide. Have a separate column that includes all scans the peptide was identified in (not just the highest scoring) as well as how many PSMs it was found in.

**Comment by rmillikin** [comment]
isn't this in the PSMs file?

**Comment by zrolfs** [comment]
It is present in the PSMs file as separate row entries. It would be convenient to have it all in one place when looking at the peptide list, however.

**Comment by rmillikin** [comment]
see #752
