### ISSUE TITLE
Don't overwrite CustomMods.txt on update

### ISSUE THREAD

**Issue by trishorts** [smith-chem-wisc/MetaMorpheus#1129]
i have a user that is adding their own custom mods. We worked through how to do that. But, then I had to caution him about what happens when there is an update. Currently his option is to save a copy elsewhere and then re-copy them into the appropriate location each time. That is not great. 

Can we have a CustomMods.txt file in the usr/local/app/mm/mods/ folder where users can add their mods and this particular file never gets overwritten? That would solve the problem.

**Comment by rmillikin** [comment]
Sounds good to me

**Comment by rmillikin** [comment]
I took a look at this today. The following .txt files are overwritten on update currently:

aListOfmods.txt
detachers.txt
fallOff.txt
glyco.txt
missing.txt
Mods.txt
substitutions.txt
surfactants.txt
tmt.txt

These files to be overwritten are defined in `MetaMorpheusSetup/Product.wxs` .

So, if you want to add custom mods, don't append them to the end of these existing text files; they will be overwritten. Make a new text file called (for example) CustomMods.txt and this text file will NOT be overwritten. This is the behavior in the current version, so this issue requires no code change, technically.

So it's more of a communication problem than an actual coding problem. We should help people add custom mods in a way that will not be frustrating.
