### ISSUE TITLE
Move "Open mods folder" button in GUI

### ISSUE THREAD

**Issue by rmillikin** [smith-chem-wisc/MetaMorpheus#1131]

**Comment by zrolfs** [comment]
Isn't this already accomplished by going to Data-> Open folder with Mods?

**Comment by rmillikin** [comment]
Sure; I just think it should be in a more prominent location. Specifically the "modifications" section in the task window.

**Comment by rmillikin** [comment]
I'm actually going to close this because I'm not sure users should be monkeying around with these text files unless they're power users who REALLY know what they're doing. Let's just stick to an "add custom mod" button in the GUI (#1130) and MetaMorpheus will write a CustomMods.txt file that will not be overwritten on update (#1129).
