### ISSUE TITLE
warning: non-specific enzyme designed for classic/modern search not non-specific search

### ISSUE THREAD

**Issue by trishorts** [smith-chem-wisc/MetaMorpheus#1141]
seems counter-intuitive to me.

**Comment by zrolfs** [comment]
"Please use 'SingleN' or 'SingleC'" 
Them's the rules.
I could make non-specific protease default to SingleN or SingleC when doing a non-specific search mode?

**Comment by trishorts** [comment]
I guess I don't understand non-specific search, or at least I don't understand why it is named that if it is not actually a non-specific search. Also don't know why you'd specify an enzyme or something like it (SingleN or SingleC) for a non-specific search. while I'm at it, what do SingleN and SingleC mean? I think more real-time support for these options by way of tool tips, or more accurate and obvious naming would help.

**Comment by zrolfs** [comment]
Let me know if that's coherent or if something needs more elucidation.

**Comment by trishorts** [comment]
Seems like a "Proteoform Fragment Search" might be a better name, since you are looking for a single cleavage in a proteoform either from the N or C terminus. I could be wrong, but I think that in common usage, non-specific search is used more for ID of peptides, which are often internal proteoform fragments produced enzymatically by, for example, the proteasome.

**Comment by zrolfs** [comment]
Perhaps I was not clear... We are looking for peptides. The output of this search is the same as if you selected classic/modern+non-specific protease. The cleavage of the proteins is simply the algorithm that is a means to obtain the peptide ids. They do not need to be on the termini of the protein.

**Comment by trishorts** [comment]
even more confusing. What does picking singlen or singlec do then? and why bother with that? and why not allow picking non-specific enzyme for non-specific search?

**Comment by zrolfs** [comment]
I will allow non-specific protease to by used in the GUI be defaulting to SingleN or SingleC behind the scenes. That should prevent this confusion.

**Comment by zrolfs** [comment]
I understand your frustration.
""SingleN" or "SingleC", which cleaves only once per residue and uses either N- or C-terminal ions, respectively."
These proteases cleave each residue only once, leaving either the C or N terminus fixed. These are needed for the algorithm, as explained above. Using the non-specific protease cleaves every residue hundreds of times, where the gains made by the algorithm would be mute. The choice between SingleN and SingleC does not particularly matter, as both methods give similar results. The user does not need to know about these proteases; they can be left in the background.


If you would prefer, I can wipe Non-Specific Search Mode from the GUI until further revision.

**Comment by zrolfs** [comment]
There was/is an existing tool tip for the Non-Specific search mode...

**Comment by trishorts** [comment]
do you mean here? cuz nothing is popping up for me. 
![image](https://user-images.githubusercontent.com/16841846/39317025-3b33eb64-4940-11e8-90f5-4c2826a8025d.png)

**Comment by zrolfs** [comment]
Yes, there should be something there. I'll investigate.

**Comment by zrolfs** [comment]
Should be working. Are you using 0.0.278?

**Comment by trishorts** [comment]
yes

**Comment by rmillikin** [comment]
#1143 should help clarify things.
