### ISSUE TITLE
Refactoring parallelization

### ISSUE THREAD

**Issue by acesnik** [smith-chem-wisc/MetaMorpheus#1168]
Nested `Parallel.ForEach` and `Parallel.For` loops are really tough to cancel. They also don't use 100% of CPU in some instances. I'd suggest refactoring using Thread objects (which can be stored and canceled individually) to enable a cancel button and to improve CPU usage.

**Comment by acesnik** [comment]
I'm pretty sure that's easier. For some reason, when it's nested, it doesn't pay attention to the Parallel state variable that flags a canceled loop. Both Connor and I tried that, I believe...

We could write a simple unit test to find out.

**Comment by rmillikin** [comment]
nested parallel loops are no longer a thing, hopefully should be easier to cancel the parallelized loops
