### ISSUE TITLE
The old switcheroo: SNV discovery, are they real?

### ISSUE THREAD

**Issue by trishorts** [smith-chem-wisc/MetaMorpheus#1181]
see examples:

DFPEEVAIVEELGRR | DFPEEVAIVEELG[1 nucleotide   substitution:G->R]R[1 nucleotide substitution:R->G]R | DFPEEVAIVEELG[1 nucleotide   substitution:G->R]R[1 nucleotide substitution:R->G]R | G->R R->G

VINEPTAAALAYGLDK | VINEP[1 nucleotide substitution:P->A]TA[1 nucleotide   substitution:A->P]AALAYGLDK | VINEP[1 nucleotide substitution:P->A]TA[1 nucleotide   substitution:A->P]AALAYGLDK | A->P P->A

**Comment by acesnik** [comment]
Didn't you recently show that the SNV discovery isn't great using just mass differences of peptides?

**Comment by rmillikin** [comment]
merged with #308
