### ISSUE TITLE
Lots of PSMs/peptides but only 2 proteins?

### ISSUE THREAD

**Issue by zrolfs** [smith-chem-wisc/MetaMorpheus#1192]
http://proteomicsnews.blogspot.com/2018/05/boxcarboxfahrt-real-data-and-new.html

**Comment by rmillikin** [comment]
MetaMorpheus protein analysis is very different than Morpheus, but regardless, it's possible to get only a couple proteins at a given FDR just like it's possible to get a couple PSMs at a low FDR simply because of one high-scoring decoy. I'd be curious how these runs do in MetaMorpheus though

**Comment by zrolfs** [comment]
Still following up on this. Ben Orsburn was fantastic in quickly responding and providing us with the .raw files. Quantification caused a crash, so I unchecked it. MM got <100 PSMs @ 1% FDR, which I hope is from the data being ion trap. It's 60K Res. ion trap, though.

**Comment by trishorts** [comment]
https://www.ncbi.nlm.nih.gov/pubmed/21917720

**Comment by zrolfs** [comment]
Using MetaMorpheus, I found 5688 PSMs, 3953 peptides, and 1230 proteins from “HeLa_BoxCar_tests_IonTrap_60k” when using precursor and product mass tolerances of 10 ppm and 200 ppm. I tried to reproduce mystery #1 on Morpheus v272, but didn’t get very many PSMs (~100). 

It looks like there were only two reported proteins because there were only three PSMs at a 1% FDR. The wide product tolerance used (0.600 Da), coupled with a lack of peak filtering, allowed for lots of random matches. Morpheus outputs all PSMs/Peptides (thus the large file sizes), but restricts protein output to the specified confidence. MetaMorpheus outputs all proteins, regardless of confidence, so we’ve already made that change. 😊
Morpheus is unfortunately optimized for high resolution MS2 spectra, but we’re actively working on better accommodating ion trap data in MetaMorpheus.

**Comment by rmillikin** [comment]
How many PSMs/peptides/proteins do you get at 1% FDR?

**Comment by zrolfs** [comment]
> Using MetaMorpheus, I found 5688 PSMs, 3953 peptides, and 1230 proteins from “HeLa_BoxCar_tests_IonTrap_60k” when using precursor and product mass tolerances of 10 ppm and 200 ppm.

**Comment by zrolfs** [comment]
It was tricky finding a decent product mass tolerance.
I tried calibrating, but calibration couldn't find enough points. I believe because there were no MS1 scans in the file. It was a little weird seeing calibration say "opening up tolerances" when it would then shrink the product mass tolerance.

**Comment by rmillikin** [comment]
I thought you meant at any FDR for those stats. I'm confused by "Morpheus outputs all PSMs/Peptides (thus the large file sizes), but restricts protein output to the specified confidence. MetaMorpheus outputs all proteins, regardless of confidence, so we’ve already made that change." Shouldn't we get the same number of PSMs/peptides as Morpheus, since our search algorithm and scoring are identical? And regarding protein identification, the above quote makes it seem like the ~1k proteins you see are low-confidence

**Comment by zrolfs** [comment]
Sorry for the confusion, the reported PSMs/Peptides/Proteins are at a 1% FDR. I believe the differences between the two are in peak filtering (their default is 400 and ours is 200). More peaks = more random matches.

**Comment by zrolfs** [comment]
I wonder if MM would be able to better handle low res data if we were more stringent on the number of peaks when filtering?

**Comment by rmillikin** [comment]
probably. I think we need to use machine-learning to figure out how much to weight peaks based on intensity. in high mass-accuracy cases I assume the contribution from intensity to score would be negligible, much as we're scoring things now, but in low-mass accuracy situations it would probably help tremendously
