### ISSUE TITLE
How to use correctly the experimental design tab?

### ISSUE THREAD

**Issue by Dmorgen** [smith-chem-wisc/MetaMorpheus#1208]
assuming I have an analysis with biological replicates and no fractions - how would I write the table correctly?

Thanks!
David.

p.s. Liked the ASMS talk.

**Comment by Dmorgen** [comment]
never mind - missed the tab in the wiki somehow. thanks!

**Comment by trishorts** [comment]
Consider it a victory that people are reading the wiki
