### ISSUE TITLE
new scoring modes to access low-res data

### ISSUE THREAD

**Issue by trishorts** [smith-chem-wisc/MetaMorpheus#1210]
let's try andromeda 1.0 and 2.0 scoring to see if we can get those low res scans done right. we can review the asms talk by Petra Gutenbrunner to see the actual procedure.

**Comment by rmillikin** [comment]
see #300 
I suspect weighting intensity more will mean more IDs for low-res data while probably decreasing very slightly high-res data PSMs

andromeda 2.0 seems very similar to andromeda 1.0 except with fragment ion intensity prediction, which seems to (currently) only work well for unmodified trypsin-digest peptides. I'm not a fan of limiting our scoring algorithm to that subset of peptides, or having two separate scoring algorithms, etc, though I can see the merits of it
