### ISSUE TITLE
consider default max peptide length. 

### ISSUE THREAD

**Issue by trishorts** [smith-chem-wisc/MetaMorpheus#1213]
there are some whoppers in human canonical 

![image](https://user-images.githubusercontent.com/16841846/41182017-8e208b32-6b39-11e8-806d-2413e1756768.png)

**Comment by zrolfs** [comment]
Default max of 50 (or 4500 Da) is pretty common in other search software.

**Comment by rmillikin** [comment]
50 is fine with me. I tried to implement that a while ago and stefan vetoed it. I think these large-mass species are probably prone to deconvolution errors. though I suspect the scores would be quite poor. are you observing any high-scoring, very long peptides in your samples?

**Comment by zrolfs** [comment]
There are a dozen or so high scoring 50-60 mer PSMs when digestion efficiency is low or a non-tryptic digest is used, but typically we don't observe things that long in bottom-up.

However...
There aren't any apparent benefits to using a max length. There's a tiny decrease in search time, but it's unlikely to improve the results, as I haven't observed a long, high scoring decoy.

**Comment by trishorts** [comment]
I'm sheepish about  setting the max. I do see some longer identified peptides.

**Comment by rmillikin** [comment]
So is the consensus to leave it as-is, with no upper limit to peptide length?
