### ISSUE TITLE
Nonspecific tomls are being reset to defaults whenever opened.

### ISSUE THREAD

**Issue by zrolfs** [smith-chem-wisc/MetaMorpheus#1217]

**Comment by zrolfs** [comment]
They appear to be reset every time, regardless of if it's opened or not, so the lengths can't be changed from the default of 8-25...

**Comment by rmillikin** [comment]
Just making a quick note that I tried to reproduce this bug and couldn't. The search task window saves settings, saves the toml, and MM reads the toml all ok as far as I can tell

**Comment by zrolfs** [comment]
Classic Search -> non-specific protease -> modify the max length and save
Reopen, max length is default of 25

**Comment by zrolfs** [comment]
I'm working on a fix right now

**Comment by rmillikin** [comment]
any update on this? maybe Ian can finish it up?

**Comment by rmillikin** [comment]
done in #1284
