### ISSUE TITLE
Number of Mods should impact the score

### ISSUE THREAD

**Issue by zrolfs** [smith-chem-wisc/MetaMorpheus#1221]
There are cases where I'll have two mods that could be explained by one:
RT[Mod:Formylation on T]K[Mod:Methyl on K]AWNRQLYPEWTEAQR
vs
[N-Acetyl]RTKAWNRQLYPEWTEAQR

or where ambiguity "exists" but it seems much more likely to be the peptide with fewer (or no) modifications:
GEKLNGTDPEDVIRNA
vs
[PeptideTermMod:Carbamidomethyl of peptide N term]EKLNGTDPEDVIRNA
OR
ATYHGSFSTK
vs
[PeptideTermMod:Propionamide]TYHGSFSTK

**Comment by rmillikin** [comment]
instead of affecting the score, I'd go for an Occam's razor approach where the simpler answer is chosen in these types of ambiguous cases

**Comment by zrolfs** [comment]
I agree that works well when there's ambiguity, but I feel that a 3 mod peptide that scores 0.01 more than an unmodified peptide shouldn't win out. It would be nice to have a spectrum for these instead of a cut and dry rule.

**Comment by rmillikin** [comment]
we could increase the score difference for ambiguity (e.g. 0.05 instead of whatever the current one is)

**Comment by zrolfs** [comment]
Current one is 1e-9 😆

**Comment by trishorts** [comment]
one the machine learning spectrum matching get's going well, it could be that intensities of ptm containing fragments are predictable and that intensity matching can be the decider between options with the same total number of binary peak matches.

**Comment by trishorts** [comment]
also, I think acetyl may have diagnostic ions. Not sure if/how we consider diagnostic ions now.

**Comment by trishorts** [comment]
I do like active discriminttion (using intensity matching and diagnostic ions) a little better than simply deciding against a cluttered candidate over a non-cluttered candidate. But, I would take it if it works.

**Comment by rmillikin** [comment]
I'm guessing it'll be at least a year or two before fragment ion intensity prediction is reliable for PTM-containg peptides. That would be nice though...

Diagnostic ions would be nice. we're not using those at all right now

**Comment by rmillikin** [comment]
number of mods is part of the PEP calculation. we could add additional features to train on, like diagnostic ion observations, etc. I think issue #1259 is a more appropriate discussion for that topic, though.
