### ISSUE TITLE
Non-specific crash

### ISSUE THREAD

**Issue by zrolfs** [smith-chem-wisc/MetaMorpheus#1223]
Not sure what's up, but I'll fix it this weekend.

**Comment by rmillikin** [comment]
any update?

**Comment by zrolfs** [comment]
No, this slipped my mind. It's a bit tricky, so probably something I have to do and not something we can outsource to Ian.

**Comment by zrolfs** [comment]
I couldn't reproduce this in 0.0.286.

**Comment by zrolfs** [comment]
Outsourcing from graduate students to undergraduate students was the subtext, but I suppose it's insourcing if your frame of reference is to the group.

**Comment by zrolfs** [comment]
Alright, I got the crash again. Still an issue. Still working on it...

**Comment by zrolfs** [comment]
It was whoever added  PostSearchAnalysisParameters. MetaMorpheusTask already has a CommonParameters as a property, but it was also added in the PostSearchAnalysisParameters. The other SequencesToActualPeptides was updated, but not the nonspecific one...

**Comment by rmillikin** [comment]
you mean there is a CommonParameters object in the PostSearchAnalysisParameters and the MetaMorpheusTask, when there should only be one in the MetaMorpheusTask?

**Comment by zrolfs** [comment]
Yes

**Comment by rmillikin** [comment]
fixed in #1329
