### ISSUE TITLE
Empty results from SCIEX 5600 mzML data

### ISSUE THREAD

**Issue by ftwkoopmans** [smith-chem-wisc/MetaMorpheus#1229]
Searching SCIEX 5600 DDA data yields empty results (0 peptides/proteins identified) using MetaMorpheus 0.0.282.

**Data**
A SCIEX TripleTOF 5600 DDA WIFF file was converted to mzML using msconvert (ProteoWizard 3.0.18172.e4a23b1bb) with peakpicking/centroiding enabled. We validated the mzML file by searching with Morpheus (version 272) with (near) default settings and find expected amount of peptides/proteins.

**MetaMorpheus settings**
Loading the same fasta file and mzML as tested with Morpheus, we create a default MetaMorpheus search task (only changing; precursor & product mass tolerance to similar settings as Morpheus). The report states zero peptides/proteins were identified. I tried searches with and without the MetaMorpheus setting "Use Provided Precursor", to no avail.

Are there any special settings required for mzML generated from SCIEX WIFF? If not, I can privately share mzML files for testing (please send me an email; frank.koopmans at vu.nl ).

**Comment by trishorts** [comment]
What were the ms1 and ms2 resolutions?

**Comment by ftwkoopmans** [comment]
The SCIEX 5600 in "high-sensitivity" mode yields a resolution of ~30k at FWHM.

Setting mass tolerances to precursor:25ppm and product:0.025Da in Morpheus works fine (and varying both between 20~50 ppm has only minor impact). I've tried similar settings in MetaMorpheus.

**Comment by rmillikin** [comment]
This is likely a problem with how MetaMorpheus reads some mzML files. Specifically, some mzML are formatted unexpectedly and are missing information like the precursor scan number, etc, which can cause 0 PSMs in the results. I'm going to release a new version today that may fix this, but if it doesn't, are you able to share a data file with us so we can fix this? I can set up a Box folder for you to drop it in to.

**Comment by rmillikin** [comment]
This is fixed in #1222 and is included in the new version 0.0.283!
