### ISSUE TITLE
SemiSpecific/NonSpecific confusion

### ISSUE THREAD

**Issue by acesnik** [smith-chem-wisc/MetaMorpheus#1232]
Why is there both `ProteinDigestion.SemiSpecificDigestion()` and `Protease.SemiSpecificDigestion()`? The latter even says it's for nonspecific digestion in the description, yet it's used when "semi-trypsin" is selected as the protease. The former is used when "semi-specific search" is selected.

![image 5](https://user-images.githubusercontent.com/16342951/41875905-e1a26342-7891-11e8-8b54-a7d0cfeada38.png)

Can we try to add to the descriptions what exactly these methods do? Can we also consider renaming the two methods above to differentiate them, especially if `Protease.SemiSpecificDigestion()` actually performs nonspecific digestion?

**Comment by zrolfs** [comment]
@acesnik Is this still an issue?

**Comment by acesnik** [comment]
Yes.

**Comment by acesnik** [comment]
I'm no longer working on them, though, so it's no longer a priority for me.

**Comment by rmillikin** [comment]
more of an mzLib issue I think?
