### ISSUE TITLE
Neutral losses

### ISSUE THREAD

**Issue by Dmorgen** [smith-chem-wisc/MetaMorpheus#1252]
Hi,

the wiki says neutral losses for modifications is for MS1 losses - how about MS2 neutral losses? 

Cheers,
David.

**Comment by zrolfs** [comment]
At this time, MetaMorpheus does not look for neutral losses in MS2 spectra and they have no influence on the score. We experimented with using them for scoring some time ago and found they yielded fewer PSMs, but new scoring methods (and ion types) are certainly still on the table.

**Comment by trishorts** [comment]
could look for NL and report them in the output w/o using them for scoring. To aid in validation/annotation.

**Comment by trishorts** [comment]
same for diagnostic ions

**Comment by rmillikin** [comment]
see #1259
