### ISSUE TITLE
Missing Data Validity Check in XLSearch Task

### ISSUE THREAD

**Issue by ianhirsch** [smith-chem-wisc/MetaMorpheus#1253]
The XLSearch task is missing user input handling and response for user assigned parameters. A similar infrastructure does exist in the other tasks.

**Comment by zrolfs** [comment]
The purpose of this is to sanitize the input and prevent program crashes. For example, if a user entered a double where an int is expected or a string where a double is expected, we should block the save instead of allow a crash.

**Comment by rmillikin** [comment]
done in #1261
