### ISSUE TITLE
mzML loading uses maximum threads regardless of Max Threads setting

### ISSUE THREAD

**Issue by rmillikin** [smith-chem-wisc/MetaMorpheus#1290]
probably same for mgf. Thermo loading is not parallelized because of restrictions from MSFileReader.

This change needs to be made in mzLib.

**Comment by rmillikin** [comment]
We should also check mzLib for other `Parallel` loops to make sure the number of threads is limited appropriately

**Comment by acesnik** [comment]
Maybe make a static object in mzLib (`ParallelizationVariables`?) with the number of threads and also the Boolean for stopping loops, and then the cancel button could be used to stop flashLFQ and such.

**Comment by rmillikin** [comment]
not sure when this was done but it's in #1406 at least
