### ISSUE TITLE
Run failed, Exception: Index was out of range. 

### ISSUE THREAD

**Issue by talpa25** [smith-chem-wisc/MetaMorpheus#1336]
Dear Developer,
after the spectra were searched i get a window with the following error:
Run failed, Exception: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index

What could this possibly mean?

Best

**Comment by trishorts** [comment]
Thanks for the report. We are all at a proteomics meeting today. We will respond as quickly as we can. Is there some way you could share the data file that caused the problem? We can provide a folder you can use to upload the file.

**Comment by talpa25** [comment]
i loaded a couple of spectra files in Thermo raw and mgf (~6), but this doesn't make a difference.

**Comment by rmillikin** [comment]
Hi there,

There should be a results.txt file with a more detailed error message. Can you attach that file here please?

Have you tried searching the [demo files](https://uwmadison.box.com/s/7rjo9sohki6xrgltr0r56fjpyb9ni8cp)? Do these cause a crash?

If not, are you able to share one of your mgf or raw files with us so we can diagnose the problem? I can set up a Box folder to upload to.

Thanks,
Rob

**Comment by talpa25** [comment]
Hi,
this is the result file. 
[results.txt](https://github.com/smith-chem-wisc/MetaMorpheus/files/2282444/results.txt)

I hope this wíll tell you a bit more. In the mean time i'll try the demo files and other settings.
Best

**Comment by rmillikin** [comment]
Thanks for the results file, I've figured out the crash from that. It occurs because the XL task (crosslink task) finds no PSMs, and when trying to write a empty output, MetaMorpheus crashes.

Are you searching a cross-link data file? https://uwmadison.box.com/v/MetaMorpheusXL has some example files to try our cross-link search.

@lonelu maybe you can help figure out settings that will help him?

**Comment by lonelu** [comment]
Hi, can you clarify what you mean by skipping it? The open-mass search is built into the XL search; there shouldn't be an option to skip that

**Comment by rmillikin** [comment]
crash fixed in #1337 . Thanks again for the report!

**Comment by rmillikin** [comment]
this is in the latest release (287), by the way!
