### ISSUE TITLE
zero length crosslinker configuration / adding

### ISSUE THREAD

**Issue by talpa25** [smith-chem-wisc/MetaMorpheus#1339]
Dear all,

I've tried to configue MM for  zero-length Crosslinkers like DMTMM. The make a covalent bound between K and DE with loss of water. 
But unfortunately MM cannot take a minus in the crosslinker total mass box.

Would you mind providing that feature?

Best
Roman

**Comment by lonelu** [comment]
Definitely! I need to make sure that the fragments are the correct masses with water loss on the correct position. I'll look into this - hopefully in a few weeks we will have this ready.

**Comment by lonelu** [comment]
Hi, the next release of MM will be able to take a minus in the crosslinker total mass box. As you mentioned the mass will be a loss of water. The H2O-dead-end mass will be considered to have a proper parameter setting. 
I am willing to code your crosslinkers into MM if you like it (just need the user-defined crosslinker information).

**Comment by rmillikin** [comment]
done in #1355

**Comment by rmillikin** [comment]
this feature is in v288!

**Comment by talpa25** [comment]
Dear https://github.com/lonelu

thank you very much for your offer. Below you'll find some crosslinkers that are commonly used in the field.

DMTMM crosslinks  K or N-terminus with DE (or C-terminus) by mass change of -18.011 monomass: 140.046 

BMOE crosslinks C with C by mass change of 220.048 monomass: 220.115

SDA cleavable crosslinks KSTY or N-terminus with DE (or C-terminus) by mass change of 82.042 (monomass of 125.059) and a cleaved long fragment mass add of 100.052 and short of 82.042

DHSO cleavable crosslinks DE and C-terminus with DE and C-terminus by mass change of 222.063 (monomass 221.071) and a cleaved long fragment mass add of 100.01 and short of 68.037

CDI cleavable crosslinks K and N-terminus with KSTY and N-terminus by mass change of 25.979 (monomass of 43.006) and a cleaved long fragment mass of 25.97926454 and a short mass of 0.

PDH crosslinks DE and C-terminus with DE and C-terminus by mass change of 152.106 (monomass of 170.117)

ADH crosslinks DE and C-terminus with DE and C-terminus by mass change of  138.09055 (monomass of 156.10111)

If you have question don't hesitate to contact me.

Best

Roman

**Comment by rmillikin** [comment]
Thanks for your detailed work Roman. We're hoping to add a place to store crosslinkers in a text file that is user-editable (#1398 ) - that way you can add custom crosslinkers without having to type the details in all the time. We can add these crosslinkers to that text file. I'm hoping to have that done in 2-3 weeks.

I don't think we allow generic N-term or C-term as valid crosslink sites (only specific amino acid residues right now). That's an important thing to add...
