### ISSUE TITLE
search crashed during assignment of peptides to proteins.

### ISSUE THREAD

**Issue by Dmorgen** [smith-chem-wisc/MetaMorpheus#1340]
please see the attached files.

Cheers,
David.
[SearchTaskconfig.toml.txt](https://github.com/smith-chem-wisc/MetaMorpheus/files/2286083/SearchTaskconfig.toml.txt)

[results.txt](https://github.com/smith-chem-wisc/MetaMorpheus/files/2286079/results.txt)

**Comment by rmillikin** [comment]
Thanks for the report David.

@zrolfs is this the same crash in #1223 ? Fixed in #1329 ?

**Comment by zrolfs** [comment]
Yes, this is fixed in the next release!

**Comment by rmillikin** [comment]
Great! I'll make a new release tomorrow or Thursday. I'll keep this issue open for now until the next release is out.

**Comment by rmillikin** [comment]
fixed in the latest version (0.0.287)!
