### ISSUE TITLE
GPTMD is slow

### ISSUE THREAD

**Issue by rmillikin** [smith-chem-wisc/MetaMorpheus#1341]
Somewhere around 7/24/18 GPTMD became slow (slower than calibration)

![unnamed](https://user-images.githubusercontent.com/24705713/44092637-ac931c88-9f96-11e8-9e0e-26a0d1bb556f.png)

**Comment by acesnik** [comment]
Strange! Was that because calibration got faster or because gptmd got slower, I wonder.

**Comment by zrolfs** [comment]
@acesnik You can see from the chart that GPTMD got slower by x2.5.
Not sure what calibration has to do with it.

**Comment by zrolfs** [comment]
Could be any of these:
MetaMorpheus Add for maxThreads in MzLib change 
#1310 by ianhirsch was merged 22 days ago • Review required  

File Output Reorganization 
#1309 by ianhirsch was closed 23 days ago • Review required  

Small fix ensures that crashes in entering indistinguishable proteins are handled 
#1307 by rmmiller22 was merged 23 days ago • Review required  

Rob's MetaDraw... 
#1306 by rmillikin was merged 22 days ago • Review required  

File specific overwrote all other parameters to default 
#1305 by zrolfs was merged 23 days ago • Approved

**Comment by rmillikin** [comment]
I think this is a false-positive issue here, actually. I ran GPTMD on the same 2 calibrated files with v0.0.284 and v0.0.288 and it took about 15min both times. I think because #1310 correctly limited the number of threads used, and the .toml file Jenkins uses limits the threads to use per file to 3, the search slowed down from using unlimited threads to using 3 threads. GPTMD must be most affected by using fewer threads?
