### ISSUE TITLE
Run failed, Exception: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by talpa25** [smith-chem-wisc/MetaMorpheus#1348]
Dear Developer,

I've tried to set up a custom Crosslinker DSBU search and in runs lamost to the end but gives this error prompt:
Run failed, Exception: Object reference not set to an instance of an object

here is the detailed description:
[results.txt](https://github.com/smith-chem-wisc/MetaMorpheus/files/2293264/results.txt)

What could that possibly mean?

Best

**Comment by rmillikin** [comment]
Thanks for the crash report. @lonelu will need to check this one out, he's the crosslink expert. Hopefully we'll have a new release out soon with this fix.

**Comment by lonelu** [comment]
Hi, can you also upload your .toml file? Thanks. I will figure this out ASAP.

**Comment by talpa25** [comment]
[XLSearchTaskconfig.zip](https://github.com/smith-chem-wisc/MetaMorpheus/files/2297388/XLSearchTaskconfig.zip)
i zipped it for file type reasons

best

**Comment by lonelu** [comment]
Hi, Thanks for the information. The bug has been fixed. I will contact our code manager, and get a new release ASAP.

**Comment by rmillikin** [comment]
should be fixed in #1355 - I'll make a new release tomorrow with this change

**Comment by rmillikin** [comment]
fixed in v288!
