### ISSUE TITLE
Allow customized defaults

### ISSUE THREAD

**Issue by zrolfs** [smith-chem-wisc/MetaMorpheus#1349]
We're partial to our defaults, but it's likely that not every user agrees. Maybe some labs never use trypsin, so they have to switch their protease each time they open a new search task. The other option users currently have is to track down an old toml and drag it in, but this can be a pain.

Instead, it'd be nice if we made a button in each task window that said "save as default", which writes the toml to a data folder so that it can be used anytime a new task is made.

**Comment by acesnik** [comment]
Brian, that's a great first step. Thanks for the suggestion. 

"Save as Default" would be a bit tougher to implement.
