### ISSUE TITLE
Duplicate ExcelDefaults wix property?

### ISSUE THREAD

**Issue by acesnik** [smith-chem-wisc/MetaMorpheus#1356]
The issue goes away if I delete the second ExcelDefaults fragment. Otherwise, it won't build.

https://github.com/smith-chem-wisc/MetaMorpheus/blob/master/MetaMorpheusSetup/Product.wxs#L445

![image](https://user-images.githubusercontent.com/16342951/44362256-074f2380-a486-11e8-87ba-90e601af999a.png)

**Comment by rmillikin** [comment]
fixed in #1357
