### ISSUE TITLE
Write peptide pruned database

### ISSUE THREAD

**Issue by Dmorgen** [smith-chem-wisc/MetaMorpheus#1369]
Hi,

Is it possible to export the identified proteins and/or peptides as a fasta database? this should be particularly useful for peptidomics experiments.

Thanks!
David.

p.s. pressed Enter by accident while writing the header...

**Comment by zrolfs** [comment]
That's an awesome idea! It should be pretty easy to implement.
Outputting a "pruned" protein database (containing only proteins identified) is already supported. It's in the "post-search analysis" tab of the search task window.

For outputting a database of peptides, do you have any input on the preferred names for the peptides? We would want them to be unique, such that two unique peptides from the same protein don't have the same accession number.

**Comment by Dmorgen** [comment]
Hi, 

i think the names should be the name/uniprot of the protein + the position of the first aa of the protein (i.e. S307) +a serial number in case there are a few such peptides.

Thanks!
David.

**Comment by trishorts** [comment]
could be the range (first and last aa). Snag with protein groups and shared peptides, which would have multiple proteins and multiple ranges, but could be enumerated.

**Comment by trishorts** [comment]
not sure this is a good general feature for MM. It's something that could be done pretty easy in mzlib. We could make a little script for processing the psms file from MM.

**Comment by rmillikin** [comment]
We'll probably be able to get started on this program in about a week. Seems fairly easy to write, it's just parsing text and then writing a fasta database. Updates to come soon...

**Comment by rmillikin** [comment]
I haven't put the code on github yet but here's a program that turns MetaMorpheus .psmtsv results into .fasta:
https://github.com/smith-chem-wisc/MetaMorpheus-Peptide-Database-Generator/releases

I did a search of a yeast file, converted the results to a .fasta, then searched again. I went from 17k to 19k PSMs. So maybe the results seem a bit overconfident. But still, it works...

**Comment by zrolfs** [comment]
The psms should go up, because the false positive targets were written, but the decoys were not. This results in an underestimated FDR. Tread lightly...

**Comment by Dmorgen** [comment]
it's a good method for de-novo assemblies from RNAseq or metaproteomics.

**Comment by trishorts** [comment]
FYI. we have a new feature in metamorpheus to use data from multiple proteases in a single parsimony event. peptides from different proteases overlap, and we use this to get improved protein inference. In this case, I can imagine that if you are trying to performm de-novo assembly, overlapping peptides from that would be a big bonus in terms of assigning them to a particular possible rna isoform

**Comment by Dmorgen** [comment]
Awesome, thank!

**Comment by trishorts** [comment]
Hey Dmorgan (we have a new peak annotation viewer in metamorpheus). download the new release. Select Data/MetaDraw from the menu. load a raw file and a psms file (wait) and then start clicking. let us know what you think.

**Comment by Dmorgen** [comment]
will do, thanks!
