### ISSUE TITLE
"ProteinTermMod: Met loss + Acetylation" is present when there aren't methionine

### ISSUE THREAD

**Issue by zrolfs** [smith-chem-wisc/MetaMorpheus#1374]
This mod should require an M OR should not be a modification. This mod is only useful if the protein methonine setting is set to retained, which is pretty uncommon.

**Comment by zrolfs** [comment]
Also, "ProteinTermMod: Acetylation + Methionine" currently has two neutral losses, "0", and "173.05". There shouldn't be a neutral loss?

**Comment by rmillikin** [comment]
I'd vote to get rid of this mod. This situation is taken care of by setting M cleavage to variable and having protein N-term acetylation checked, right?

**Comment by rmillikin** [comment]
done in #1396
