### ISSUE TITLE
Bug in TestClassicSemiProtease()?

### ISSUE THREAD

**Issue by acesnik** [smith-chem-wisc/MetaMorpheus#1385]
https://github.com/smith-chem-wisc/MetaMorpheus/blob/master/Test/SearchEngineTests.cs#L802

Shouldn't this be using `CommonParameters2`, not `CommonParameters`? It's crashing for me when I add in my variant protein stuff, but somehow not on the master branch.

**Comment by acesnik** [comment]
@zrolfs

**Comment by zrolfs** [comment]
I think you're right; it should be CommonParameters2.

**Comment by acesnik** [comment]
Thanks for taking a look!

**Comment by rmillikin** [comment]
fixed in #1395
