### ISSUE TITLE
Calibration still not reproducible

### ISSUE THREAD

**Issue by zrolfs** [smith-chem-wisc/MetaMorpheus#1389]
The MS2 fragments (stored in "PeptideSpectralMatch.MatchedFragmentIons") are not reproducible between runs. Specifically, ~1% of the psms have different number of fragment ions between identical calibration tasks. This is not an ordering issue, as the summed number of fragment ions is also different.
The issue is occurring before "allPsms" has been defined in CalibrationTask.cs.

**Comment by rmillikin** [comment]
seems to be fixed in #1408
