### ISSUE TITLE
Store user-defined crosslinkers in a text file

### ISSUE THREAD

**Issue by lonelu** [smith-chem-wisc/MetaMorpheus#1398]
Make adding user-defined crosslinker like adding a new protease.

**Comment by rmillikin** [comment]
Reading/writing to/from a user-editable .tsv file

**Comment by bintiibrahim** [comment]
do we still want to add this feature?

**Comment by rmillikin** [comment]
definitely

**Comment by rmillikin** [comment]
done in #1584
