### ISSUE TITLE
Number of Spectra and Number of Precursors not always listed in Results txt file

### ISSUE THREAD

**Issue by blfrey** [smith-chem-wisc/MetaMorpheus#1401]
Mark and I really like that you added these outputs to the txt file a few months ago.
But, I am getting cases where it does not output these numbers.
It is when I only search one data file. Then, the "all results" text file only lists PSMs, peptides, and proteins. I have attached an example.  (I also checked the "results" text file within the SearchTask sub-folder, and that doesn't have these outputs either).  

I think it used to output number of spectra even when only one file was searched, but now it isn't doing that anymore.

Thanks!    Not a big time rush on this, but it would be helpful info to have.

[allResults.txt](https://github.com/smith-chem-wisc/MetaMorpheus/files/2362654/allResults.txt)

**Comment by rmillikin** [comment]
fixed in #1426
