### ISSUE TITLE
Complementary Spectra Needs Different Implementation

### ISSUE THREAD

**Issue by zrolfs** [smith-chem-wisc/MetaMorpheus#1407]
Complementary spectra are being treated with the ppm tolerance of the complementary ion instead of the tolerance of the original ion. A different method than generating a complementary spectrum is preferred.

**Comment by rmillikin** [comment]
is this done in #1406 ?

**Comment by zrolfs** [comment]
yep, done in commit da040bdd28c72181f901b9fbd54ea79fe6404834
