### ISSUE TITLE
XL-search cancel

### ISSUE THREAD

**Issue by talpa25** [smith-chem-wisc/MetaMorpheus#1411]
Dear developers,

during the crosslink search run of a couple of raw files the search was canceled by the program by an unspecific error. I don't know whether it is caused by the specific raw file or other circumstances so i attached the results file:
[results.txt](https://github.com/smith-chem-wisc/MetaMorpheus/files/2408019/results.txt)
[XLSearchTaskconfig.zip](https://github.com/smith-chem-wisc/MetaMorpheus/files/2408020/XLSearchTaskconfig.zip)
If you think it is caused by the raw file, let me know. I'll upload them if so. 

Best
Roman

P.S.: Would you mind thinking about to implement a dialog that prevents unintended closing of MetaMorpheus during run by clicking "Close"?

**Comment by rmillikin** [comment]
Thanks for the crash report Roman. I'll look into this this week. I don't think I need your raw file, but if I do I'll let you know.

By dialog, you mean when you close the program a dialog pops up and says "Are you sure you want to close MetaMorpheus?" We could do that, it should be pretty straightforward

**Comment by talpa25** [comment]
Hey Robert. Thank you for taking care.

> By dialog, you mean when you close the program a dialog pops up and says "Are you sure you want to close MetaMorpheus?" We could do that, it should be pretty straightforward
Exactly, this would help a lot.
Thx & Praises

**Comment by rmillikin** [comment]
This should be fixed in a large code overhaul that we just implemented (#1406). We're still working out a few kinks but I plan to make a new release this week. Thanks for your patience!
