### ISSUE TITLE
Crash/Freeze during Calibration with no error message

### ISSUE THREAD

**Issue by talpa25** [smith-chem-wisc/MetaMorpheus#1417]
Dear Developers,

I experienced a crash/freeze when doing the calibration task. Metamorpheus stopps proceeding the calibration with no error message except:

> Could not find enough PSMs to calibrate with; opening up tolerances to 20 ppm precursor and 50 ppm product
Could not find enough PSMs to calibrate with; opening up tolerances to 30 ppm precursor and 100 ppm product
Could not find enough PSMs to calibrate with; opening up tolerances to 40 ppm precursor and 150 ppm product
Calibration failure! Could not find enough high-quality PSMs. Required 20, saw 15

After this the Tasks seem to run but there is no progress.

I do fractionate my peptides according to their charge by SCX to gain better resolution for quantitative MS/MS  and enrich crosslinked peptides when performing XL-MS data acquisition.
This behavior is occuring more often  when i do not do the G-PTM-D in advance but use a normal FASTA. Calibration with the G-PTM-D database this error is occuring less.

When there are not enough peptides to calibrate on Metamoprheus should proceed with the next spectra file, right?

Best
Roman

[CalibrationTaskconfig.zip](https://github.com/smith-chem-wisc/MetaMorpheus/files/2418676/CalibrationTaskconfig.zip)
[prose.txt](https://github.com/smith-chem-wisc/MetaMorpheus/files/2418677/prose.txt)
[results.txt](https://github.com/smith-chem-wisc/MetaMorpheus/files/2418678/results.txt)

**Comment by rmillikin** [comment]
Hmm - ok, thanks for the report. I'll see if I can reproduce this with my own spectra files and then if I can't I'll ask for your help there

**Comment by rmillikin** [comment]
The calibration task ended after a failed calibration (I'll fix that) but I didn't get any freezing or a crash - if this fix doesn't work (it'll be in the next release), let me know and I'll check that out.

**Comment by rmillikin** [comment]
Fixed in #1418. If a file fails to calibrate, the calibration will continue to calibrate other files. Subsequent tasks will include the uncalibrated original spectra file that failed to calibrate, along with any successfully calibrated files. This will be included in the next release - I plan to make one later this week
