### ISSUE TITLE
wipe temporarily stored data in unit tests to prevent future fails

### ISSUE THREAD

**Issue by trishorts** [smith-chem-wisc/MetaMorpheus#1424]
SemiSpecificTest generated fragment and precursor indexes several days ago. These indexes were not updated during current unit testing. The old style digestionparams caused current mm tests to fail. I spent a long time chasing a bug that didn't exist. Maybe, let's wipe these and other folders following each unit test.

**Comment by rmillikin** [comment]
I think we should probably add a line at the end of each unit test that wipes that unit test's output. 

I also really prefer to have each unit test write output to a folder with that unit test's name. Keeps things nice and organized when you're debugging and looking for unit test output.

**Comment by rmillikin** [comment]
fixed in #1436
