### ISSUE TITLE
XL search output

### ISSUE THREAD

**Issue by talpa25** [smith-chem-wisc/MetaMorpheus#1431]
Dear developers,

I have a couple of questions concerning the XL search output allPsmsXLFDRGroup.tsv

1) the target/decoy column reports unlike the normal search just a number 1, which i guess stands for target. Is it possible to include the contaminant (T/D/C) labeling like in the normal search? Sometimes there may be crosslinks between target and contaminant, but i think they can be labeled as false positive C or so...
2) sometimes i see the same peptide crosslinked to it self reported at the same position. this cannot be true. I guess it's more likely to have miscleaved consecutive peptide(s) with a monolink somewhere. What do you think? Does the XL search aims to identify the exact crosslink site by comparing the calculated masses of crosslink peptid fragments (or give a probability value for the crosslink site like pLink and MeroX/StavroX do?)? Why is it not possible anymore to input a monolink mass in the user defined crosslinker definition? 
[allPsmsXLFDRGroup.xlsx](https://github.com/smith-chem-wisc/MetaMorpheus/files/2435173/allPsmsXLFDRGroup.xlsx)
3) how is the fasta file parsed? Unfortunately i have to take a non uniprot file which  i would like to foramt according to the rules so MM can include the header informations directly.

**Comment by rmillikin** [comment]
Regarding 3, we use [regular expressions](https://en.wikipedia.org/wiki/Regular_expression) to parse the fasta header, and assume the fasta comes from UniProt. 

We use the following regex to parse the respective fields:
Accession: `([A-Z0-9_.]+)`
Full Name: `\s(.*?)\sOS=`
Name:  `\|([^\|][A-Z0-9_]+)`
Gene: `GN=([^ ]+)`
Organism: `OS=(.*?)\sGN=`

To test out a header, go to https://regex101.com/ and put in one of the above regex patterns where it says "insert your regular expression here". Then in the "insert your text string here", put in the header you're trying to parse. Here's a UniProt one:

`>sp|P38013|AHP1_YEAST Peroxiredoxin type-2 OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) GN=AHP1 PE=1 SV=4`

You can see on the right what it's grabbing out of that header for each field (accession, name, etc) by looking at the "Group 1", highlighted in green.

Regarding the other two, I can investigate those. A peptide crosslinked to itself is a problem in the disulfide search, too.

**Comment by rmillikin** [comment]
Couple of updates:
1. I've fixed the labels of the target/decoy/contaminant in the output to report T/D/C, respectively. The CSM is reported as a decoy of either of the peptides is a decoy, contaminant if either of the peptides is a contaminant, and target if they're both targets. Seems reasonable if it's a T+C to label it T but I'm not sure. Is that what you're suggesting? I could report both as well. (e.g. D+T or T+T or C+T or whatever).

2. I've excluded fragments that matched to the alpha peptide from also matching to the beta peptide. There seems to be a small bug somewhere because I still am noticing the occasional peptide crosslinked to itself, but it seems more rare than before. I'll look into that more.

"Why is it not possible anymore to input a monolink mass in the user defined crosslinker definition?"
Do you mean the deadend masses? I've added those textboxes back so you can input user-defined deadend quench masses. If that's not what you mean, let me know.

**Comment by talpa25** [comment]
Hi Robert,

thank you very much for the updates.

1) The T/D/C labeling. Thanx for the fix. I'd like to suggest to keep the rules for a CSM containing a decoy sequence, but for the contaminant it's a bit tricky, because sometimes contaminants can be target as well. For instance if you work with E. coli or Human proteome. Here a T+T or C+T labeling would be beneficial. Yes, it is also depending on the database you work with or one has created, but by doing a quick and dirty analysis this may help to improve the database aspect later. Decoy is in any way to be discarded, so i think a D label is sufficient.
2) Concerning the "same peptide crosslink".  I think there is a small chance that there are true positives "same peptide crosslink" from e.g. homodimeric proteins. But in most cases they seem to be false positive. Did you checked for miscleaved peptides resembling crosslinked peptides, especially when there is a mass shift by a monolink/deadend and somewhere in the peptide e.g. a waterloss or similar modification artefact? I think the only chance to differ between this case and a true CSM is the identfication of crosslinker containing alpha+beta peptide containing fragment peak.    

Nice to here that there is a chance to enter der deadend/monolink masses again. I'm really looking forward to the next update 👍 :)

**Comment by rmillikin** [comment]
please give the new version a try :)

Regarding the missed cleavage+deadend vs. crosslink ambiguity, I guess the score would be a tie. We haven't tackled ambiguity too thoroughly in the XL search, but we could prioritize single > deadend > XL in cases of score ties?
