### ISSUE TITLE
Vignette for Linux commandline should have mzML instead of RAW files

### ISSUE THREAD

**Issue by acesnik** [smith-chem-wisc/MetaMorpheus#1468]

**Comment by rmillikin** [comment]
I've uploaded .mzML to the vignette folder.

Need to update the readme. It would be nice to have a guide for how to get .NET core working for linux, etc. and then running MM on the .mzML files.

**Comment by acesnik** [comment]
You could dockerize MetaMorpheus in this repository and have it build on Docker's site after each release. That might be easier for others than getting netcore up and running.

**Comment by acesnik** [comment]
Docker Hub has an automatic build thing that I haven't figured out. I think it's based on when tags are updated in GitHub repositories.

**Comment by trishorts** [comment]
Very first time I converted a Thermo raw binary file to mzML on a Linux computer. Did it using ThermoRawFileParser from @compomics - very neat! 
https://github.com/compomics/ThermoRawFileParser

**Comment by rmillikin** [comment]
Linux systems should be able to read .raw soon, so I'm closing this issue; if there is some hitch in implementing Linux-based .raw reading, I'll reopen this
