### ISSUE TITLE
add comp ions check box to gptmd task gui

### ISSUE THREAD

**Issue by trishorts** [smith-chem-wisc/MetaMorpheus#1472]
3% more psms for 33% for time. default should probably be to OFF

**Comment by zrolfs** [comment]
How many more modified psms, though? If people are using GPTMD to find modified peptides, a 3% increase in total PSMs might by a lot more modified peptides.
In other words, we do GPTMD for a 5-10% increase in psms, so 33% longer for 8-13% increase doesn't seem so bad.

**Comment by trishorts** [comment]
3% modified psms (not total psms). smaller increase in total psms.

**Comment by trishorts** [comment]
actally, not psms but 3% more modified PEPTIDES

**Comment by rmillikin** [comment]
done in #1477
