### ISSUE TITLE
Resolve ambiguities with other ion types

### ISSUE THREAD

**Issue by zrolfs** [smith-chem-wisc/MetaMorpheus#1476]
I'm interested in if we can search for other ion types to resolve peptide ambiguity. It shouldn't add that much search time if we only dive into other ion types when ambiguity arises. 

If this is useful, it might be worthwhile to apply these additional ion types in situations where the delta score is within a range (0-2? 0-1?) instead of when it's just 0.

**Comment by rmillikin** [comment]
also would help with PTM localization
