### ISSUE TITLE
Add "Auto" fragmentation type

### ISSUE THREAD

**Issue by rmillikin** [smith-chem-wisc/MetaMorpheus#1479]
Reads fragmentation info from scan header. Would enable searching mixed fragmentation mode data.

**Comment by lonelu** [comment]
Or combine information of scans (ETD and HCD) for same precursors.

**Comment by rmillikin** [comment]
I think this is actually incompatible with Modern Search. To build the fragment index, the dissociation type(s) must be known; to get those, you'd need to open up every data file you're searching and look at every scan header, which would be far too slow. 

There are a few problems making this compatible with Classic Search also, but those are not as fundamental and can be worked around.

Having the user specify the dissociation type(s), perhaps via the experimental design window, seems like the best solution.
