### ISSUE TITLE
Metamorpheus crashes during Quantification (not responding)

### ISSUE THREAD

**Issue by Peer2011** [smith-chem-wisc/MetaMorpheus#1492]
Dear rmillikin,
I would like to analyze 38 Files of Q-Exactive HF. Calibration works perfectly. However, when I search files and would like to do LFQ with normalization and match between runs, after classic search RAM usage ramps up to 12,5 GB  during the quantification process and the program stops responding.  However, it still calculates somehow but I can't do anything anymore. Its running for two days in quantification now. 
I used the two variable modifications for deamidation besides standard settings and run metamorpheus with the most updated Thermo raw file reader. mzml files are generated during calibration process. 
So this looks all fine. 
Do I have too little RAM (I thought 16 GB should be enough)? Any help would be very much appreciated because I think that your software could be become a viable alternative to MaxQuant which we routinely use currently. If you need further information. Please let me know. 

Best regards, 
Peer

**Comment by rmillikin** [comment]
Hi Peer,

Matching between runs is a memory hog right now, unfortunately. Fixing this has been on my to-do list for a while. I'm hoping to have time in the next week or two to take a look at it. It'll hopefully be in the next release - I'll try to keep you posted. Thanks for the crash report!

**Comment by rmillikin** [comment]
This has proven to be more difficult than I thought, but I've got it mostly working in my test code. I'm wrapping it up now and it will be in the next release. Stay tuned :) apologies for the delay.

**Comment by Peer2011** [comment]
Really looking forward!!! 

Von meinem iPhone gesendet

**Comment by rmillikin** [comment]
This is finally out in a new release. If you still encounter RAM issues, it's probably due to MetaMorpheus search and not FlashLFQ quantification. We're still planning on making RAM improvements to the search in the future. Can you give the new version a try?

Thanks,
Rob

**Comment by Peer2011** [comment]
Of course.

Best, Peer

Von meinem iPhone gesendet
