### ISSUE TITLE
Auto updater is broken

### ISSUE THREAD

**Issue by trishorts** [smith-chem-wisc/MetaMorpheus#1497]

**Comment by rmillikin** [comment]
fixed in #1493 

the autoupdater is functional but was accidentally disabled by default in v0.0.290. To fix this, go to Settings -> Close MetaMorpheus and open GUI settings file. Change the value of AskAboutUpdating from "false" to "true".

**Comment by rmillikin** [comment]
new release is out with this fix (0.0.292)

**Comment by acesnik** [comment]
Looks like another break in the 301 -> 302 transition
![image](https://user-images.githubusercontent.com/16342951/66365415-b3c9be80-e941-11e9-9077-8da94b6a8dad.png)

**Comment by acesnik** [comment]
Yeah, 302 is missing the MSI file

**Comment by rmillikin** [comment]
the autoupdater is fine, appveyor is having issues building the installer for this version though. working on it
