### ISSUE TITLE
Uninstalling MetaMorpheus removes Excel .tsv association

### ISSUE THREAD

**Issue by rmillikin** [smith-chem-wisc/MetaMorpheus#1502]

**Comment by acesnik** [comment]
I wouldn't call this a bug. If MetaMorpheus sets defaults in the registry, they should be removed when it's uninstalled.

**Comment by zrolfs** [comment]
How does this work? It would have to set the default to something else (notepad? notepad++?). Do we store in memory what program was originally used?
This feels a little unnecessary. If the user picked this option in installation, why wouldn't they want it for other tsvs, even if they're no longer using metamorpheus?

**Comment by rmillikin** [comment]
Well, there's a couple of perspectives and a reality check here in my opinion.
1. We could save the program used for .tsv opening before installing MetaMorpheus, and revert to that program after uninstalling MM
2. We could keep the .tsv associated with Excel. I think since the user has wanted to associate .tsv with Excel, that's sort of independent of using MM in my opinion. In other words, MM and wanting to associate .tsv with Excel are not related in my brain

The reality check is that the installer is (to me) very difficult to change and test, and trying to store what the default program was before installation is going to be hard and probably not a great use of time. I'd rather just nothing happen on MM uninstall, and then the user can change the .tsv association if they want separately.

**Comment by zrolfs** [comment]
Can we close this issue if we agree on option 2?

Also, somewhat unrelated, but the current default for updating MetaMorpheus has the excel option checked automatically. This means that, if a user does NOT want to use excel, they must uncheck that option every time that they update. I maintain that the option should be unchecked by default.

**Comment by zrolfs** [comment]
Oh, maybe I misunderstood. Do you mean that MetaMorpheus currently removes the excel tsv on uninstall, or that you wanted that as a feature?

**Comment by rmillikin** [comment]
The behavior right now is that MM removes the Excel .tsv association which is annoying to me. I'd rather it just do nothing to the .tsv association

We can change it to unchecked by default too
