### ISSUE TITLE
Peak Trimming MS2 Top N peaks with multiple windows

### ISSUE THREAD

**Issue by lonelu** [smith-chem-wisc/MetaMorpheus#1503]
Another way of trimming peaks is to divide the peaks into small windows and then to filter for n most intense peaks in each small window.

**Comment by rmillikin** [comment]
this is sort of already in mzLib but I implemented it differently and it's a little buggy and we don't use it. you could just edit what's there already and enable it in MM

**Comment by trishorts** [comment]
added an extension method to mzlib that partitions list into equal segments that might be valuable here:

public static IEnumerable<List<T>> Partition<T>(this IList<T> source, Int32 size)
        {
            for (int i = 0; i < Math.Ceiling(source.Count / (Double)size); i++)
                yield return new List<T>(source.Skip(size * i).Take(size));
        }

**Comment by rmillikin** [comment]
merged with #621
