### ISSUE TITLE
Cleavable crosslinker with DissociationType

### ISSUE THREAD

**Issue by lonelu** [smith-chem-wisc/MetaMorpheus#1509]
Need to consider the situation of cleavable crosslinker with DissociationType.
For example, HCD cleavable DSSO under ETD condition. The function 'XlGetTheoreticalFragments' is wrong.

**Comment by rmillikin** [comment]
@lonelu is this implemented now?

**Comment by lonelu** [comment]
Fixed in pull request #1664
