### ISSUE TITLE
Match fragment ions with multiple charges or not

### ISSUE THREAD

**Issue by lonelu** [smith-chem-wisc/MetaMorpheus#1513]
Currently, MetaMorpheus matches deconvoluted masses. If one fragment ion has multiple charge states, only the closed one will be matched. 
'Matching all charge states' is not evaluated.
Annotation of all charge states should be included.

**Comment by zrolfs** [comment]
I notice that charge 2 fragment ions are being searched/matched, even when the precursor charge is <3. Is there a rhyme or reason as to which fragment ions are searched now? Historically, we only looked at +1 fragment ions. Do we always look for +1 and +2 now?

**Comment by rmillikin** [comment]
The fragment charge needs to be less than or equal to the precursor charge.

Line 124 of MetaMorpheusEngine:

`if (commonParameters.ProductMassTolerance.Within(closestExperimentalMass.monoisotopicMass, product.NeutralMass) && closestExperimentalMass.charge <= scan.PrecursorCharge)`
