### ISSUE TITLE
Commandline help information

### ISSUE THREAD

**Issue by acesnik** [smith-chem-wisc/MetaMorpheus#1519]
We should to polish this up. I don't see anywhere that notes that `-o` is an option for the output folder and such.

`CMD.exe --help` should return more thorough help information.

**Comment by rmillikin** [comment]
look at [FlashLFQ command line](https://github.com/smith-chem-wisc/FlashLFQ/blob/master/CMD/FlashLFQExecutable.cs) for some inspiration. though apparently it prints help twice on Linux. not sure what's up with that. newer versions of fluent command line parser (beta versions) work better on Linux.

**Comment by acesnik** [comment]
https://github.com/smith-chem-wisc/MetaMorpheus/pull/1591
