### ISSUE TITLE
Stripped mod information

### ISSUE THREAD

**Issue by vokelvin** [smith-chem-wisc/MetaMorpheus#1532]
When I search within a MM raw output file in Excel by "Mod:", I can see 
mods everywhere in column K. For example in column K, row 6 there is:

NTISKDNN[Mod:Deamidation on N]MLVSQALNSVANR(5)

This is a peptide that lacks an amide group on asparagine 8.

But if I search my file formatted for Percolator, the word "Mod:" 
doesn't appear at all: This notation has been completely stripped out, 
though there are the same number of rows overall.

If I look on row 6 of 'interlinks' scan number (col B) is 11252. This 
scan number is on row 5 also. Now in column K of these two rows:

NTISKDNNMLVSQALNSVANR(5)
NTISKDNN[Mod:Deamidation on N]MLVSQALNSVANR(5)

Look in column S of these two rows:

PINGISYDMKLQAAPYIVVNPMK(10)
PINGISYDMKLQ[Mod:Deamidation on Q]AAPYIVVNPMK(10)

In other words:

Row 5 has NTISKDNNMLVSQALNSVANR(5) crosslinked to 
PINGISYDMKLQAAPYIVVNPMK(10)
Row 6 has NTISKDNN[Mod:Deamidation on N]MLVSQALNSVANR(5) crosslinked to 
PINGISYDMKLQ[Mod:Deamidation on Q]AAPYIVVNPMK(10)

Now in the percolator input file for scan 11252: This scan# appears 
(incorporated into ScanID in column A) on rows 1194 and 1195, and in 
column M we have the crosslinked peptide pair:

-.NTISKDNNMLVSQALNSVANR5--PINGISYDMKLQAAPYIVVNPMK10.-
-.NTISKDNNMLVSQALNSVANR5--PINGISYDMKLQAAPYIVVNPMK10.-

In other words, to put the peptide into Percolator input format 
(-.peptide1#--peptide2#.-), MM has stripped out the modification 
information and both rows now look identical.

Nonetheless, the percolator input file has preserved the peptide mass in 
column H and the peptide score in column D. But, the Percolator output 
file does not preserve either of these, so the information, as to which 
of the two peptides the output file refers to seems to be lost.

So overall, my question is: can MetaMorpheus can preserve this modification information in files formatted for Percolator? In addition, does MM search L/H separately, or together?

Many thanks!

**Comment by acesnik** [comment]
Good questions! This sounds like a question for @lonelu or @rmillikin. We'll get back to you soon.

**Comment by rmillikin** [comment]
apologies for the delayed response, and thanks for the bug report. it looks like this is only in the XL task output - the regular search appears to annotate mods properly in the Percolator output. We can fix this in the next release.

**Comment by rmillikin** [comment]
> In addition, does MM search L/H separately, or together?

can you clarify what you mean by this? Light/heavy label? If you mean your sample is mixed heavy/light isotope label, we search them separately. we don't have any processing code for paired samples yet

**Comment by lonelu** [comment]
I don't think ambiguity is handled very well in Crosslink search. It is weird to me that there are 2 rows with same scan number.

**Comment by rmillikin** [comment]
I fixed the mod display in #1544 . I'm making a new release later today with this change

**Comment by rmillikin** [comment]
New release is out :)
