### ISSUE TITLE
Why do we do parsimony with all PSMs instead of all peptides?

### ISSUE THREAD

**Issue by acesnik** [smith-chem-wisc/MetaMorpheus#1534]
It seems like we do FDR filtration on all PSMs and then call them peptides in the parsimony engine. Won't this lead to redundancy in the list of peptides?

**Comment by rmillikin** [comment]
in the `ProteinParsimonyEngine` constructor, `_fdrFilteredPeptides` is filled with non-redundant peptide sequences from the list of FDR-filtered PSMs (lines 49-74)
