### ISSUE TITLE
Targeting difference between EngineLayer and TaskLayer

### ISSUE THREAD

**Issue by acesnik** [smith-chem-wisc/MetaMorpheus#1537]
I don't see any errors because of this, but it seems odd that EngineLayer and TaskLayer target different frameworks.

![image](https://user-images.githubusercontent.com/16342951/49319186-39c6de80-f4c1-11e8-8298-b36a997d7f1d.png)
![image](https://user-images.githubusercontent.com/16342951/49319194-421f1980-f4c1-11e8-82e9-d6ea6a26109d.png)

**Comment by rmillikin** [comment]
This might be a holdover from Stefan's first iteration of MM - either way I'm not sure what the repercussions (if any) are if it's changed. I'm not super interested in finding out tbh
