### ISSUE TITLE
Automate Rachel's multiprotease coverage plots in MetaDraw

### ISSUE THREAD

**Issue by acesnik** [smith-chem-wisc/MetaMorpheus#1538]

**Comment by lonelu** [comment]
Does the output of multiprotease search already contain the coverage information?

**Comment by acesnik** [comment]
Not sure. @rmmiller22 ?

**Comment by rmillikin** [comment]
the protein tsv output contains coverage % and the peptide sequences. and the actual residues covered/not covered in the protein. it doesn't tell you which peptides belong to which protease(s)

**Comment by rmmiller22** [comment]
Correct. I have searched for the sequences in the psms file and peptide files to generate the sequence coverage plots
