### ISSUE TITLE
MetaMorpheus still runs in the background on closing because of custom fragmentation window

### ISSUE THREAD

**Issue by rmillikin** [smith-chem-wisc/MetaMorpheus#1548]
At least in visual studio the process does not fully end when you open the new task window (e.g., search) and then "X" out of the window, and close MM. Pretty minor bug. But I'd prefer a more robust solution to making sure we handle closing windows properly. Potentially could cause annoying RAM issues.

**Comment by bintiibrahim** [comment]
i thought this was already resolved? when a task window is opened, and then "X", it stops running on visual studio

**Comment by rmillikin** [comment]
To reproduce:
Open MM
Add search task
Custom dissociation type
Cancel
X out of search task
X out of MetaMorpheus

Ideally we'd have a more robust system for handling this... trying to catch all the weird ways this could go wrong seems prone to error. Not exactly sure how to do this more robustly, though...

**Comment by bintiibrahim** [comment]
> To reproduce:
> Open MM
> Add search task
> Custom dissociation type
> Cancel
> X out of search task
> X out of MetaMorpheus
> 
> Ideally we'd have a more robust system for handling this... trying to catch all the weird ways this could go wrong seems prone to error. Not exactly sure how to do this more robustly, though...

**Comment by bintiibrahim** [comment]
ah ok. MM is still running in this case bcs the custom frag window is open. it's cus our solution only closes the window when

- search task is **added**
- search task is **cancelled**

all i need to is close window if search task is **"X" out**. unless there are other ways to close the **search task window**, this should do it. i'd have to do this for calibrate task, xl search & ptm search.

**Comment by rmillikin** [comment]
fixed in #1575
