### ISSUE TITLE
MetaDraw Glycan

### ISSUE THREAD

**Issue by lonelu** [smith-chem-wisc/MetaMorpheus#1552]
Draw glycan tree in the standard way. 
Try to represent glycans the same was as 'GlycoWorkBench' (Another software program)

**Comment by trishorts** [comment]
https://www.ncbi.nlm.nih.gov/glycans/snfg.html

**Comment by trishorts** [comment]
![image](https://user-images.githubusercontent.com/16841846/50350188-f382ff00-0503-11e9-9572-485e7664929a.png)
