### ISSUE TITLE
FlashLFQ proteome fractions recombining

### ISSUE THREAD

**Issue by talpa25** [smith-chem-wisc/MetaMorpheus#1553]
Dear developers,

when i fractionate peptides with e.g. SCX to gain a greater/deeper proteome coverage i want to recombine the several fractions with the FlashLFQ function to get the quantities of proteins of each replicate, not the fraction. 
I'll tried to configure the experimental design, but it gives me always the filename as the sample and does not recombine several fractions into one replicate/experiment like MaxQuant does. 
 
Do I just failed in configuration of the experimental design? Is there any way to achieve my way of thought?

Best
Roman

**Comment by rmillikin** [comment]
Hi Roman,

Currently there's no automatic recombination of fractions into replicates, but if you simply sum the fraction intensities that will get you the replicate intensity. That's true for both peptides and proteins. We are planning on adding this functionality (automatic summing) but I'm unsure of the ETA.
