### ISSUE TITLE
Multiple delimiters for quantification?

### ISSUE THREAD

**Issue by zrolfs** [smith-chem-wisc/MetaMorpheus#1555]
For protein/gene groups, I'm seeing multiple unique delimiters. Do these mean different things?
Example: "ACTB|ACTG1;ACTA2;ACTA1"
Specifically, I'm looking at "AllQuantifiedPeptides.tsv" from 0.0.296.

**Comment by rmillikin** [comment]
The "|" delimits proteins within a protein group. The ";" delimits protein groups

**Comment by zrolfs** [comment]
So "|" means the peptide sequence is found in multiple proteins and ";" means that the actual peptide sequence is ambiguous and we're not quite sure what we found.

**Comment by rmillikin** [comment]
no; in all cases, the peptide sequence is unambiguous. but it may belong to more than one protein group

**Comment by zrolfs** [comment]
I'm still a little confused. "|" seems intuitive (multiple proteins that can explain the peptide). ";" is confusing. How can there be multiple protein groups if only a single peptide sequence exists?

**Comment by rmillikin** [comment]
a peptide sequence can be shared between protein groups. For example, let's say we detect:
protein 1: peptides A, B, C
protein 2: peptides B, C, D

protein 1 and protein 2 are both protein groups that have one protein in them. they each have a unique peptide (A or D, respectively). peptides B and C are shared between them. so in the peptide quant results you'd see:
A   Protein 1
B   Protein 1;Protein 2
C   Protein 1;Protein 2
D   Protein 2
