### ISSUE TITLE
Crash during quantification

### ISSUE THREAD

**Issue by xxonxio** [smith-chem-wisc/MetaMorpheus#1557]
The program crashes during quantification step when the match between runs is selected. 
An error prompt is presented: Run failed, Exception: Index was outside the bounds of the array
More info:
[results.txt](https://github.com/smith-chem-wisc/MetaMorpheus/files/2791657/results.txt)

Best
Johannes

**Comment by rmillikin** [comment]
Thanks for the crash report Johannes. I've fixed this crash in FlashLFQ but it hasn't percolated through to MetaMorpheus yet. I'll make a new release in the next few days with this fix.

**Comment by rmillikin** [comment]
This is fixed in the latest version (0.0.297) which I just released. If you get another error please let us know!
