### ISSUE TITLE
Protease Configuration w/ Multiple Cleavage Restrictions

### ISSUE THREAD

**Issue by mamccabe** [smith-chem-wisc/MetaMorpheus#1558]
Hi all,

I have samples that are digested with both Hydroxylamine (HA) and Trypsin and am trying to set up a user defined protease to search these samples but am having some trouble with the notation. While hydroxylamine canonically cleaves at N|G sites, we also see cleavage between N and a number of other residues. I would like to define the protease as cleaving C-terminal of K and R (for Trypsin) as well as C-terminal of N, except when the following residue is C, F, H, or M. I am able to successfully search the desired raw file using the same FASTA database with trypsin as the enzyme, so I am sure the problem lies in the protease configuration. Additionally, I am finding conflicting reports of how the syntax should be structured from different posts on the Github forum. Some posts describe the syntax using only the "Sequences Inducing Cleavage" column with additional brackets for excluding residues, while other posts appear to also use the "Sequences Preventing Cleavage" and "Cleavage Terminus" columns with residues separated by | characters. I have tried the following syntax with no success (for the ones using 3 columns, columns are separated by a single space):
K|,R|,N|[CFHM]
K|,R|,N[CFHM]|
K|,R|,N|[C][F][H][M]
K|,R|,N[C][F][H][M]|
K|,R|,N|[C],N|[F],N|[H],N|[M]
K|,R|,N|G
K|R|N P|P|CFHM C|C|C
K|R|N P|P|C C|C|C

as well as a few others. All of these return a runtime error that says the index is out of bound of the array. I'm unsure were to go from here after reading all related posts I can find, any help would be much appreciated!

**Comment by rmillikin** [comment]
Hello,

K|,R|,N|[C],N|[F],N|[H],N|[M]

is the correct syntax. We'll have a new version out with a fix for this bug pretty soon (next few days). I'll post here when the new version is out. 

If you're curious, the issue was that we weren't properly reading in multiple motifs with the same sequence inducing cleavage but different motifs preventing cleavage. So N|[C] is fine, but N|[C],N|[F] wouldn't be read in properly because there are two N's with different sequences preventing cleavage.

**Comment by mamccabe** [comment]
Thanks for the prompt response! That does seem to be a part of the issue but I believe the problem goes a little further based on the testing I've been doing. Defining the protease as K|,R|,N|[C] (using a single exception) returns the same index out of bounds error as using multiple selections. Additionally, chymotrypsin (don't cleave before proline) and Lys-C (don't cleave before proline) are defined as F[P]|,W[P]|,Y[P]| and K[P]|, respectively, in the default proteases file and return the same error as my user-defined protease, suggesting the error may be due to all exceptions. The syntax of these proteases in the default file seems to be a little muddled, with the | character on the other side of the cleavage exception from the way described by you and in the protease wiki page. However, if I correct these proteases to the seemingly correct format of K|[P], it returns the same error. Again, trypsin and a new protease with the same rules as trypsin both work without issue. 

As a final consideration, defining my new protease as K|,R|,N|G returns the same error, suggesting the issue may not be limited to the syntax involving exceptions. However, K|,R|,N| works just fine. Hopefully this gives you some insight into where the problem lies! Again, thanks for the quick assistance.

**Comment by rmillikin** [comment]
interesting - thanks, we'll include that in our list of things to check for this issue. Thanks for being the guinea pig :) apologies for the bug.

I'm told the | can be on either side of the "preventing cleavage". i.e. K|[P] and K[P]| are the same thing. This doesn't quite satisfy my desire for order in the world so we may change that at some point, but for now they're interchangeable.

**Comment by mamccabe** [comment]
No problem, eager to get using the program if we can sort this out! Seem like it has a lot of benefits for our workflow, thanks for the help!

**Comment by rmillikin** [comment]
This is fixed in the latest version (0.0.297) which I just released. If you get another error please let us know!
