### ISSUE TITLE
create a wiki page for common error messages and how to fix them.

### ISSUE THREAD

**Issue by trishorts** [smith-chem-wisc/MetaMorpheus#1564]

**Comment by rmillikin** [comment]
I'd prefer to handle these via the actual client. Navigating to the wiki page is sort of cumbersome and expects a lot from the user, I think. If there are complex problems that need navigation (i.e., how do I set up a notch search) I'm fine with having a wiki page for this. But known, relatively un-fixable crash messages should be descriptive enough for the user to fix it without further lookups.
