### ISSUE TITLE
Super long full sequence bug?

### ISSUE THREAD

**Issue by acesnik** [smith-chem-wisc/MetaMorpheus#1567]
This 39mer has a bizarre and repetitive modified full sequence that's super long.

Data: U2OS Mann data
Workflow: calibration, GPTMD, search with defaults

![image](https://user-images.githubusercontent.com/16342951/52515390-bc5dcf80-2bcf-11e9-8fb9-66f878316d9a.png)

**Comment by acesnik** [comment]
![image](https://user-images.githubusercontent.com/16342951/52515447-8ff68300-2bd0-11e9-9a54-58e48500c63c.png)

**Comment by acesnik** [comment]
Column 2 is the length

**Comment by acesnik** [comment]
It's the third non-header row in this spreadsheet.
[BizarreLongFullSequence.xlsx](https://github.com/smith-chem-wisc/MetaMorpheus/files/2847437/BizarreLongFullSequence.xlsx)

**Comment by rmillikin** [comment]
Is this just a PTM (or 2, I guess) that can't be localized? The "|" delimits ambiguity. Is this just a highly ambiguous sequence?

**Comment by acesnik** [comment]
The file for this is on the bison if someone wants to help with this...

**Comment by acesnik** [comment]
Um wow, you're right. It's the same sequence pipe-separated 132 times, and then two others.

**Comment by acesnik** [comment]
Thanks for thinking about that.
