### ISSUE TITLE
co isolation

### ISSUE THREAD

**Issue by stefanks** [smith-chem-wisc/MetaMorpheus#157]
For each identification, say if it could have come from a co-isolation

**Comment by stefanks** [comment]
There are two approaches:
1. Have each MS2 scan have _mulitple_ possible precursor masses, that correspond to peaks in the isolation range of the MS1 scan. This way even a narrow 5ppm search could identify these co-isolated peptides.
2. After a 3.1 Dalton tolerance search is complete, consider the PSMs that do not have zero mass error (within some tolerance). For those PSMs, look back at the corresponding MS1 spectra to look for peaks that could explain the shifts better. Annotate those on the PSMs tsv file.

**Comment by trishorts** [comment]
This is going to be very powerful for top-down searches. The window around the precursor is many daltons wide. The modern search will be really ideal.

**Comment by stefanks** [comment]
Approach 2 implemented in https://github.com/smith-chem-wisc/MetaMorpheus/pull/292
