### ISSUE TITLE
crosslink with low res data

### ISSUE THREAD

**Issue by lonelu** [smith-chem-wisc/MetaMorpheus#1576]
In ms2-ms3 fragmentation type of data. The ms3 scans are always in low res with ion-trap. Morpheus score not working in such a situation.

**Comment by trishorts** [comment]
we have low res xcorr in metamorpheus now and that works

**Comment by lonelu** [comment]
Make low res xcorr work for a combination of high and low res data.

**Comment by lonelu** [comment]
#1806
