### ISSUE TITLE
XL issue: By default DSSO is not cleavable

### ISSUE THREAD

**Issue by mriffle** [smith-chem-wisc/MetaMorpheus#1578]
I don't know this is intentional or not, but the default settings for DSSO are not as a cleavable cross-linker as of the latest version of MetaMorpheus. Users need to set up User Defined cross-linker with DSSO as a cleavable linker.

**Comment by trishorts** [comment]
That's strange. Which version of MetaMorpheus are you using. I looked at the code I have downloaded and it is specified as cleavable there.  How are you noticing this problem on your end? 
![image](https://user-images.githubusercontent.com/16841846/53518249-3deda280-3a96-11e9-9366-37ed9f703f67.png)

**Comment by mriffle** [comment]
Here is the appropriate section of the toml file gets created when using the built-in DSSO linker. Using 0.0.297

[XlSearchParameters]
DecoyType = "Reverse"
CrosslinkerType = "DSSO"
CrosslinkSearchTopNum = 300
CrosslinkerResidues = "K"
CrosslinkerResidues2 = "K"
IsCleavable = false
RestrictToTopNHits = true
WriteOutputForPercolator = false
WritePepXml = true
XlQuench_H2O = true
XlQuench_Tris = true
XlQuench_NH2 = false

**Comment by trishorts** [comment]
ok. I see. we'll get right on it.

**Comment by rmillikin** [comment]
This seems to be an issue writing the .toml, not with the internal definition of DSSO. I performed the search and got the expected number of CSMs, but the .toml did indeed read "Cleavable = false". I dragged this .toml into MetaMorpheus and ran the search, and got the same result as before (correct CSMs, incorrect .toml written).

I'll investigate further, but this doesn't appear to be a major problem in terms of the actual search. Just something funky going on with writing the .toml.

**Comment by mriffle** [comment]
Ah cool, thanks

**Comment by lonelu** [comment]
Currently, the "IsCleavable = false" is only for User-Defined crosslinker. This is confusing. We plan to make change of it #1398. Again, thanks for pointing this out.

**Comment by lonelu** [comment]
fixed
