### ISSUE TITLE
XL Search question: How are cleavable cross-link results reported? I see no MS3 hits

### ISSUE THREAD

**Issue by mriffle** [smith-chem-wisc/MetaMorpheus#1580]
Not a bug report, but a question, and my apologies if this is documented somewhere. And I'm willing to concede that there's something I'm not understanding about how MS3 cleavable searches work...

When I do a DSSO cleavable cross-linker search, all of the cross-linked results I get seem to be hits to MS2 spectra and the linker mass reported is the uncleaved linker mass for DSSO. (using PepXML output)

Is MetaMorpheus, in fact, searching the MS3 spectra for peptide matches, and reporting the results at the MS2 level using the scan number for the MS2 scan that was the parent of the MS3 scans?

Or are these MS2 hits separate from MS3 ones, and I'm just not finding these in the results for some reason?

Are the scan numbers for the MS3 scans used to ID each peptide available?

**Comment by rmillikin** [comment]
Currently MS3 data isn't searched, but it's in the pipeline (PR #1551). Hopefully this version will be out within a month or so - it's got to go through code review and bug testing.

**Comment by mriffle** [comment]
Ah OK, that would explain it! If you want some feedback about how the new data are being output to PepXML, just let me know. I'm currently adding in native support for cleavable cross-linkers and MS2 into proxl so am thinking about it quite a bit.

**Comment by rmillikin** [comment]
I think that would be very helpful, thanks. I think after US HUPO we'll have a bit more bandwidth to push some new stuff through the pipeline. 

I definitely want to make sure our XL input is still readable into ProXL after these changes.

**Comment by mriffle** [comment]
Actually followup question then: how are cleavable cross-linkers handled at the MS2 level? Is it looking in the MS2 spectra for the cleaved products and the uncleaved products for the same scans?

**Comment by rmillikin** [comment]
I believe we look for: cleaved products (short-cleave product, long-cleave product), cleaved precursor (M-short, M-long), but not uncleaved products or uncleaved precursor in the MS2 scan. I can double-check that with @lonelu .

**Comment by lonelu** [comment]
Yes, That is what we do currently. It would be easy for us to search uncleaved products (peptide bond breaks but not crosslink bond) or uncleaved precursor but we don't do that now. I guess it depends on crosslinker bond strength and the dissociation type. We have plans to make the crosslinker cleave with certain dissociation types (i.e., HCD but not ETD) (#1509) instead of just having a true/false value in the future also.

**Comment by mriffle** [comment]
Thanks for all the details. For the record, not suggesting that it looked for uncleaved products, just curious if it id. Thanks again.

**Comment by lonelu** [comment]
Hi @mriffle ,
sorry for the delay of this issue. We didn't get any good MS2-MS3 type of data previously, and MS3 in general is in low res CID which is not working well for MetaMorpheus. Anyway, it is working now and we are optimizing the matching and the scoring. 
Could you let me know what should I do about the output for proxl? Thanks

**Comment by mriffle** [comment]
This sounds great, I'll get back to you soon!

**Comment by rmillikin** [comment]
Update on this issue - the XL task now reports child scan matched ions in the .tsv output, whether they be MS2 or MS3. Here's an example. It doesn't seem to be reported in the .pep.XML output, though, which I think is probably needed by proxl to interpret correctly?


[Task1-XLSearchTask.zip](https://github.com/smith-chem-wisc/MetaMorpheus/files/5548689/Task1-XLSearchTask.zip)
