### ISSUE TITLE
XL Search: mono-links being reported twice in PepXML

### ISSUE THREAD

**Issue by mriffle** [smith-chem-wisc/MetaMorpheus#1581]
Hi, from a DSSO search I see the following result:

    <spectrum_query spectrum="redacted.5580" start_scan="5580" end_scan="5580" precursor_neutral_mass="1216.57434" assumed_charge="2" index="18">
      <search_result>
        <search_hit hit_rank="1" peptide="HSVVNEKTK" peptide_prev_aa="K" peptide_next_aa="R" protein="P33203" num_tot_proteins="1" calc_neutral_pep_mass="1216.57434" massdiff="-176.015692486448" xlink_type="na">
          <modification_info>
            <mod_aminoacid_mass position="7" mass="176.0143" />
            <mod_aminoacid_mass position="7" mass="176.0143" />
          </modification_info>
          <search_score name="xlTotalScore" value="6.12028713773577" />
          <search_score name="Qvalue" value="0.0239234449760766" />
        </search_hit>
      </search_result>
    </spectrum_query>

Looks like the 176.0143 is being reported twice for position 7.

**Comment by lonelu** [comment]
I just check our result, and deadend mods showed twice. There is a bug there!!! Thanks for reporting this.

**Comment by rmillikin** [comment]
status on this bug?

**Comment by lonelu** [comment]
Find the bug. Previous all modifications are added before everything. the deadend crosslinker was added in pepxml output seperately.
Then the matching algorithm changed, the deadend crosslinker was transferred to a modification. 
Solved in pullrequest #1678
