### ISSUE TITLE
crosslink position can not be modified

### ISSUE THREAD

**Issue by lonelu** [smith-chem-wisc/MetaMorpheus#1582]
For example, if K is not in protein N-terminal, if it is acetylated, it cannot be used as crosslink site.

**Comment by rmillikin** [comment]
I think we would only want to allow XL sites to be modified in the case of C or N term modifications, right?

**Comment by lonelu** [comment]
The problem was solved before. Check function CrosslinkSpectralMatch.GetPossibleCrosslinkerModSites.
