### ISSUE TITLE
Hardware question + crosslinking question

### ISSUE THREAD

**Issue by Dmorgen** [smith-chem-wisc/MetaMorpheus#1585]
Hi again :)
I've a 4 processor computer with 144 logical cores, but for some reason I'm getting only 36 cores used. the other issue is that I observe under-utilisation of both RAM and CPU. the CPU and RAM hover at 5% usage.
is there anyway to improve the utilization (thereby performance)?

The second question relates to cleavable xlinker: I've a linker that cleaves at the same energy as the peptide - thus I'm getting mixed spectra of the two peptides, each carrying a part of linker. Any special setting to run the search?

Thanks!
David.

**Comment by lonelu** [comment]
Hi Dmorgen,
There is no special setting for your type of crosslinker. 
As you know, we are going to change the 'user-defined crosslinker' setting recently to make it more user-friendly. Let us know if you have any suggestions or requirements.
About the cores, there is a "Max Threads" under "Search Parameters" which you can set. Can you tell us about your database size, like protein numbers or so?
Lei

**Comment by rmillikin** [comment]
Not sure about the threading issues - the number of threads detected is determined by .NET (so, Microsoft).  I can look into this issue to see if anyone else has experienced it.

In terms of the crosslinker question. There are four fragmentation possibilities: a) no fragmentation (precursor ion), 2) crosslinker cleavage only ("signature" ions, or each intact peptide plus a piece of the crosslinker on each peptide), 3) peptide bond cleavage only, or 4) peptide bond cleavage + crosslinker cleavage. We look for 2 and 4 but not 1 and 3. If you want to look for 2 and 4 then you don't need to anything special. If you want to look for type 4, we can add this as an option.

**Comment by acesnik** [comment]
What type of processor do you have?

**Comment by Dmorgen** [comment]
@lonelu : sure, thanks! the searched are usually human proteome XML and the likes, but with multiple samples - up to 90. I've tried to use modern search but it crashes, even with multiple partitions (despite 128GB RAM) the classic works really fast, but again, not utilizing fully the server's capability.

@rmillikin does 4 mean that you look for the crosslinker linker as a point modification? if so, that's what I need.

@acesnik its Xeon Gold 6136

**Comment by lonelu** [comment]
![xlkeranalysis2](https://user-images.githubusercontent.com/10702896/53995540-ec2ec300-40fa-11e9-8d4f-0a74a97ad7ce.png)
Yes. Here is an example, PEPTIDE is crosslinked with SEQUENCE. For alpha b4 ions, we look for PEPT-S, PEPT-L. We don't look for PEPT-SEQUENCE or others. We also look for signature ions PEPTIDE-S, PEPTIDE-L.

**Comment by acesnik** [comment]
That's a great processor; the web says it has 24 virtual cores, which makes it even more confusing why it would be running 36 threads.

We have a couple computers running Windows 10 with 2 CPUs running 20 threads each (40 threads total), and we do see MetaMorpheus running 40 threads. 

Is this a Windows machine or a Linux cluster running MetaMorpheus with .NET Core? 

If it's a Linux cluster, this may be a problem with .NET Core, since we build MetaMorpheus in .NET Framework 4.7 instead for Windows machines.

**Comment by Dmorgen** [comment]
we've got 4 processors on the machine (and it's 18 physical core each). we're using Windows server 2016 for it.

Thanks!
