### ISSUE TITLE
Viewing XL results but not with ProXL?

### ISSUE THREAD

**Issue by Dmorgen** [smith-chem-wisc/MetaMorpheus#1589]
Hi Guys,

I've got some XL data searched, but not with supported by ProXL (the linkers). any other viewers? would metaDraw be useful?

Thanks!
D.

**Comment by lonelu** [comment]
MetaDraw only annotates the spectrum.
The developers of ProXL are very supportive. I will contact them and ask for help.
XiNET will be supported in the next version.

**Comment by Dmorgen** [comment]
@mriffle  Hi Michael, We're developing multiple crosslinkers, with various reactivities, handles, mass tags etc. In many cases we're going to abandon the linker. would it be possible in some way to allow user definition for linkers?

**Comment by mriffle** [comment]
Absolutely, that is something we're literally working on right now. If you're willing, I'd love to collaborate with you on getting that nailed down.

**Comment by Dmorgen** [comment]
That would be awesome! thanks!

**Comment by mriffle** [comment]
Great, created an issue over at proxl: https://github.com/yeastrc/proxl-web-app/issues/7  --we can discuss over there.
