### ISSUE TITLE
Commandline improvements

### ISSUE THREAD

**Issue by acesnik** [smith-chem-wisc/MetaMorpheus#1593]
- [x] Dockerize it
- [x] Make smithchemwisc Docker account
- [x] Automatic builds of docker image from the release branch on Docker Hub
- [x] Update readme for .NET Core vignette for mzMLs and using docker on Linux (or any) system
- [x] Add capability to generate default tomls from the commandline
- [x] Make a tutorial for MetaMorpheus Docker (see https://github.com/smith-chem-wisc/FlashLFQ/wiki/Docker-Image for similar docker tutorial template)

Any other things I'm missing?

**Comment by acesnik** [comment]
Not sure how to deploy docker builds from GitHub organization repo https://forums.docker.com/t/cant-access-new-github-organization-for-automated-builds/1080/11

**Comment by acesnik** [comment]
I made a smithlab account on Docker Hub, though, if anyone wants to use it for some reason.

**Comment by acesnik** [comment]
Thanks for adding the default toml option. Just used it!

**Comment by acesnik** [comment]
- [ ] note how to specify multiple files in the help menu (separated by space following the flag, e.g. -t toml1.toml toml2.toml -s spect1.mzML spect2.mzML)

**Comment by rmillikin** [comment]
docker hub deployments are automatic as of v0.0.306. also all merged PRs create a dev build which is also auto uploaded to docker hub.

**Comment by rmillikin** [comment]
the "latest" tag on dockerhub is also the latest release version

**Comment by acesnik** [comment]
I checked off the "Update readme for .NET Core vignette for mzMLs and using docker on Linux (or any) system" -- I think that was before the .NETCore version could read RAW files.

**Comment by acesnik** [comment]
@rmillikin You also ticked off the space-delimited issue. Feel free to close the issue 👍

**Comment by rmillikin** [comment]
sure. i think we still need a docker tutorial though

**Comment by rmillikin** [comment]
see https://github.com/smith-chem-wisc/FlashLFQ/wiki/Docker-Image for similar docker tutorial template

**Comment by acesnik** [comment]
- [ ] Make a tutorial for MetaMorpheus Docker

**Comment by acesnik** [comment]
Added a tutorial for Docker here, https://github.com/smith-chem-wisc/MetaMorpheus/wiki/Docker-Image
