### ISSUE TITLE
Searches Stuck on "Constructing Protein Groups"

### ISSUE THREAD

**Issue by mamccabe** [smith-chem-wisc/MetaMorpheus#1594]
Hello,

I have recently been attempting to use MetaMorpheus for a typical searching workflow, searching a set of 10 raw files using a calibrate task, a GPTMD task with the default modifications, and a search task. I am not using any custom proteases or settings outside of the defaults. When I perform most searches in this format, all of the tasks complete but the search task remains stuck on "constructing protein groups" indefinitely. I have left this final task to complete for at least 5 days multiple times and have seen no changes in progress, leading me to believe the process has stalled entirely and is not just taking longer than expected. 

I have been able to run successful searches if I include only a single raw file or if I remove the GPTMD task entirely but both of these solutions largely remove the utility of using MetaMorpheus. I am running version 0.0.297 on a computer with 64 virtual processing cores and 32 gb of RAM. During the stalled process, MetaMorpheus will continue to utilize the majority of the available RAM until the process is manually ended. 

Thanks for any help! 

Max

**Comment by rmillikin** [comment]
Unfortunately our parsimony can run into trouble when there are a lot of highly redundant protein sequences. We've encountered this problem once or twice when searching larger datasets, but 10 files is pretty small. It's actually not stalled, just quite slow at the last protein grouping stage. It's a known issue and we're working on fixing it; the only solution currently is patience. I wish I had better news for you, but there it is.

**Comment by acesnik** [comment]
If you want to test our software without that parsimony step for now, you can uncheck "perform protein parsimony" in the Search Task. I do that pretty often to just get peptide-level results.

**Comment by rmillikin** [comment]
Are you willing to share your data (these 10 files)? I can work on a fix for this issue more easily if you are. We have a large dataset in which this problem occurs, but it takes ~2 days to search. I can set up a Box folder for you to drop the files into.

**Comment by mamccabe** [comment]
Hello,

I did a little more testing and was able to get the 10 file data set searched successfully over the weekend by editing some search parameters. However, I am still having the issue with another vary large data set containing 50 raw files. It seems that we are in the same place now, only having the issue with very large data sets. If you would like me to send this data set I can, but I am not sure how helpful it would be if you have a large set that replicates the same issue. Let me know if you'd like it, otherwise I will be awaiting a solution whenever you get it resolved! 

Thanks.

**Comment by rmillikin** [comment]
If you can give us the 10-file dataset along with the settings that caused the very long "constructing protein groups" problem, that would be ideal

**Comment by rmillikin** [comment]
fixed in #1701
