### ISSUE TITLE
Conserve memory option

### ISSUE THREAD

**Issue by trishorts** [smith-chem-wisc/MetaMorpheus#1598]
When and why did this go away?

![image](https://user-images.githubusercontent.com/16841846/54492276-19b20400-4893-11e9-9bab-8657010c8744.png)

**Comment by rmillikin** [comment]
This is always enabled now (i.e., "conserve memory" is always on). If it was disabled, the entire set of theoretical peptides was saved to a list, sort of like a peptide index, except it was used for classic search. We removed it for RAM-efficiency reasons, and to simplify the GUI.
