### ISSUE TITLE
Make a bioconda package for metamorpheus

### ISSUE THREAD

**Issue by acesnik** [smith-chem-wisc/MetaMorpheus#1607]
We can use maxquant as an example: https://github.com/bioconda/bioconda-recipes/tree/master/recipes/maxquant

But first, we'll need `dotnet` to create a conda package like there is for `mono` https://github.com/dotnet/core/issues/2518

**Comment by ypriverol** [comment]
Hi, do you have any progress here? Im interested to use a conda package

**Comment by trishorts** [comment]
I wish that we had. But, sadly no. We are really understaffed at the moment. I think this is something that would not take much time at all. But we haven't done this ever before as a group. So, there is no-one here with the knowledge. Building the knowledge is the thing that would take the most time I guess. 

We would gladly take outside assistance.

**Comment by acesnik** [comment]
I might actually be willing to take this on in March. I want to learn python & conda packaging. By the way, `dotnet-sdk` is in conda-forge, now, so that issue is solved. https://anaconda.org/conda-forge/dotnet-sdk

**Comment by ypriverol** [comment]
I think should be bioconda. More than willing to help!!!

**Comment by ypriverol** [comment]
@trishorts @acesnik have you tested the tool on Mono 5.14.0.177?

**Comment by trishorts** [comment]
Anthony, i would be immensely grateful if you could find time to do this. And Yasset, if you'd be an alpha tester, that would really be helpful. 

I don't know if mono would work or not. MM requires dotnet compatibility for every environment. I don't know if mono has that or not.

**Comment by bernt-matthias** [comment]
I also guess that conda-forge has the needed packages:

- dotnet 
- dotnet-aspnetcore 
- dotnet-runtime
- dotnet-sdk 

These should be available in version 3.1 and 5.0

If you already have a script to compile from source a conda package at bioconda it might actually be easy to get this done ... 

Feel free to ping me if you have questions.

**Comment by trishorts** [comment]
What a great offer. Thank you. This is something that I did not know.

**Comment by bernt-matthias** [comment]
Sure, https://anaconda.org/ offers a great way to search for packages. But I would not go beyond the conda-forge and bioconda channels.

**Comment by ypriverol** [comment]
We have a team here @bernt-matthias @trishorts. @bernt-matthias can you point us to a recipe of a dotnet bioconda package for @trishorts and me to see how it looks.

**Comment by bernt-matthias** [comment]
Seems that there is no package in bioconda yet that uses dotnet (so we could be the first .. I guess we will see some exciting problems LOL). 

But we might start of with any package I guess. 

Just take for instance https://github.com/bioconda/bioconda-recipes/blob/master/recipes/bamtools/. Essentially you need two files:

- `meta.yaml`: Contains all the needed metadata. The most important part is probably the requirements section. Where you list which software is needed for building and running the software. Specs are here https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html 
- build.sh: A shell script that will build the package. 

For a start you can create a PR at bioconda that: creates a folder in recipes containing these two files ... just adapt them to metamorpheus.

**Comment by acesnik** [comment]
Yes, the `dotnet` package in bioconda is pretty new, and it doesn't work on OSX yet, but I've made an issue for that on GitHub for the people who created that. 😄 

Here's another example for MaxQuant, which is available in Bioconda https://github.com/bioconda/bioconda-recipes/tree/master/recipes/maxquant

**Comment by acesnik** [comment]
https://github.com/bioconda/bioconda-recipes/pull/27130

**Comment by acesnik** [comment]
One thing to note is that `bioconda` doesn't support Windows. If anyone intends to use conda for fetching MetaMorpheus for the Windows commandline, we should consider sending the PR to conda-forge.

**Comment by acesnik** [comment]
Adding this other issue here for reference https://github.com/smith-chem-wisc/MetaMorpheus/issues/2036

**Comment by acesnik** [comment]
I tried making a PR to conda-forge (https://github.com/conda-forge/staged-recipes/pull/14252) and ran into the same issues with the `__glibc >= 2.17` requirement for using `dotnet` that I ran into with bioconda (https://github.com/bioconda/bioconda-recipes/pull/27130).

I opened an issue on the `dotnet-feedstock` for conda-forge to ask for advice on how to proceed with this. https://github.com/conda-forge/dotnet-feedstock/issues/16

**Comment by acesnik** [comment]
I got some feedback from the developer of the `dotnet` conda-forge package:
![image](https://user-images.githubusercontent.com/16342951/111064308-8e849c80-84b3-11eb-9fe9-01d7bdf43970.png)

**Comment by acesnik** [comment]
Hi all, I finished a PR to create a metamorpheus feedstock in conda-forge using `dotnet` that's awaiting review. https://github.com/conda-forge/staged-recipes/pull/14252

**Comment by acesnik** [comment]
MetaMorpheus is now in conda-forge using `dotnet`. This makes it available on Windows, Linux, and macOS via conda.

MetaMorpheus PR:
https://github.com/smith-chem-wisc/MetaMorpheus/pull/2050

PRs for the history of merging it into conda-forge:
https://github.com/conda-forge/staged-recipes/pull/14252
https://github.com/conda-forge/staged-recipes/pull/14623

Where to find it in conda-forge:
https://github.com/conda-forge/metamorpheus-feedstock
https://anaconda.org/conda-forge/metamorpheus

**Comment by bernt-matthias** [comment]
Hi @acesnik I just checked with a colleague who is using windows. I could not figure out how to run metamorpheus from the anaconda explorer or a command line with enabled environment. Do you have any tipps for us?

**Comment by acesnik** [comment]
Thanks for checking. I'm traveling this week, but I'll try to take a look. 

Did `conda install -c conda-forge metamorpheus` work for installing it?

Were there any error messages? Running the command should be `metamorpheus` instead of `dotnet CMD.dll`, in case that's the issue.

**Comment by bernt-matthias** [comment]
@acesnik I installed via the anaconda GUI manager. I was also able to obtain a command prompt with activated environment, but unable to run the CLI, the binary / script was not found. 

Btw. is it possible to run the GUI version from the conda package?

For linux everything worked fine.

**Comment by acesnik** [comment]
Good to know!

I'm currently traveling, so I'll be able to take a closer look in a couple weeks.

**Comment by acesnik** [comment]
It looks like this was an environment variable issue. I've fixed the Windows executable issue here: https://github.com/conda-forge/metamorpheus-feedstock/pull/4.
