### ISSUE TITLE
Empty results from Waters Synapt HDMS (G1) data

### ISSUE THREAD

**Issue by DavidGZ1** [smith-chem-wisc/MetaMorpheus#1614]
Searching Synapt HDMS (G1)  DDA data (without ion mobility) yields empty results (0 peptides/proteins identified) using MetaMorpheus 0.0.297.

Data
Acquired in a Synapt HDMS (G1) Survey (DDA) in V mode (resolution = 9,000 FWHM), continuum. The .RAW data file was converted to mzML using msconvert (ProteoWizard 3.0.18353-2de7e414e) with peakpicking/centroiding enabled. I have already obtained identifications with MS-GF+ (R package) with a tolerance of 20 ppm.

MetaMorpheus settings
protease = trypsin; maximum missed cleavages = 2; minimum peptide length = 7; maximum peptide length = unspecified; initiator methionine behavior = Variable; fixed modifications = Carbamidomethyl on C, Carbamidomethyl on U; variable modifications = Oxidation on M; max mods per peptide = 2; max modification isoforms = 1024; precursor mass tolerance = ±20.0000 PPM; product mass tolerance = ±20.0000 PPM; report PSM ambiguity = True. The combined search database contained 35663 non-decoy protein entries including 230 contaminant sequences. Data files were processed on a ASUSTeK COMPUTER INC. K45VD computer using Windows version 6.2.9200.0 with a 64-Bit processor and 8 cores operating at 2,295GHz and 6GB installed RAM. The total time to perform the Search task on 3 spectra file(s) was 13,84 minutes.

**Comment by rmillikin** [comment]
Thanks for the bug report - MSConvert .mzML is supported and almost always works in MM, though we've gotten one report where recent versions of MSConvert create .mzML files that cause issues in MM. Can you share this file with us for debugging purposes?

**Comment by DavidGZ1** [comment]
Thank you for answering. Please find the .RAW and .mzML files in the following [link](https://cinvestav365-my.sharepoint.com/:f:/g/personal/david_gomez_zepeda_cinvestav_mx/EhYwJjCAnOtIvDGsCS1_mbMBPzcOi5AmUSMvUfuUvDPySA?e=bLwfMR). The RAW is too big to be attached.

**Comment by rmillikin** [comment]
Sorry this has taken so long to investigate. This issue looks like it's being caused because of problems getting the precursor ion's mass. An m/z is reported, but no charge, and the isolation window itself is not reported so there's no easy way to get precursors via deconvoluting the isolation window.

Usually MSConvert provides this info to us via the mzML file, but it looks like it's not there. I guess in these cases we could deconvolute a static 1 or 2 m/z window around the isolated m/z and report the most probable charge/mass. Fair warning, it may be a while before this is working, though.

**Comment by rmillikin** [comment]
This file has some weird looking MS1 data, so even the "deconvolution guess" approach I discussed above probably won't work. I suppose you could just blindly guess at charge states randomly but this seems like a poor approach. Do you know why this MS1 data is so strange looking, and why the instrument controller doesn't guess precursor charges?

**Comment by DavidGZ1** [comment]
Hello Robert,
I’m sorry for the delay on my answer .

We have recently obtained Progenesis for Proteomics (Waters – NonLinear
Dynamics), thus I will be using this software to obtain my identifications.
Anyway, *I sincerely appreciate your help and the time you took to evaluate
the problem.*

I agree in the fact that the problem may come from the absence of charge
state annotation in the MS1 because I have encountered a similar problem
when using SearchGUI. This happens even when I use charge prediction in
MS-convert. Nevertheless, SearchGUI do make an automatic assignment of the
charge and it is working correctly.

What do you mean with weird looking MS1?
I had some problems with the nanospray, which was clogged several times
during the analysis (it was one of my first times using this nanoLC which
was not used for 10 years). I think the instrument controller (MassLynx
from Waters) do guess precursor charge, but maybe it is not being saved or
it is not recovered when converted to mzML. I don’t know if this is a
specific problem of my instrument of it is general to Waters data, which is
often difficult to convert to open formats.

Kind regards,
David

Le ven. 14 juin 2019 à 14:44, Robert Millikin <notifications@github.com> a
écrit :
