### ISSUE TITLE
Separate settings into basic/advanced

### ISSUE THREAD

**Issue by rmillikin** [smith-chem-wisc/MetaMorpheus#1620]
I think we're reaching the point where we have a lot of search settings that most people probably don't really care about or want to mess with, and it's cluttering up the GUI. I'd like to keep all the current settings (and be more comfortable with adding additional settings in the future), but simply rearrange them. My ideal is to open a new task window and have the basic settings immediately visible instead of in a series of dropdown menus. There would be one dropdown tab at the bottom that contains all the advanced settings (probably with additional sub-menus).

Here's what I'd like to see in the basic settings, with the remaining settings under the "advanced" tab. Feel free to voice your opinion if you feel strongly that a setting should be in one category or another.

```
Deconvolute precursors
Precursor Mass Tolerance
Product Mass Tolerance
Protease
Max mods per peptide
Min/max peptide lengths
Max missed cleavages
Initiator methionine behavior
Dissociation type
Modifications (Fixed/Variable/GPTMD)
Protein parsimony options
Quantification options
Output options
```

One problem with this is that if you want to do a fairly common but not ultra-basic search like semi-specific, non-specific, notch, or open-mass search, it becomes more difficult (albeit not that much more difficult). I think these searches are core parts of MM and should somehow be included in the basic settings section, but I also think they're currently a bit hard to figure out how to use. What "Search Mode" to use is likely somewhat confounding to new users, since there isn't an analogous option in other programs to choose your search algorithm.

**Comment by trishorts** [comment]
in advanced add option to turn off final search in gptmd

**Comment by rmillikin** [comment]
done in #1645 . Happy to move things around if desired. I'll keep this issue open for discussion.
