### ISSUE TITLE
"Slided Decoys" is extremely slow in some cases

### ISSUE THREAD

**Issue by rmillikin** [smith-chem-wisc/MetaMorpheus#1641]
Katie reports ~12h and counting for the "Loading Proteins" stage, using a GPTMD database with "Slided Decoys" instead of reversed. database is at \\bison\share\Users\Katie\MM Issues\042619

**Comment by acesnik** [comment]
Why is she using slided decoys?

**Comment by rmillikin** [comment]
misclick

**Comment by acesnik** [comment]
I think we should ditch slided decoys. That fixes the bug, too. 😅

**Comment by rmillikin** [comment]
I'm inclined to agree - though it would be nice to have reverse decoys and random decoys. @zrolfs thoughts? is there even documentation describing what slided decoys are?

**Comment by rmillikin** [comment]
I believe @zrolfs fixed this

**Comment by zrolfs** [comment]
This is kinda funny. I'm pretty sure I've fixed this twice and then people add unintentional "while(true)" loops in the code.
