### ISSUE TITLE
Transition to .NET Core 3.0

### ISSUE THREAD

**Issue by rmillikin** [smith-chem-wisc/MetaMorpheus#1671]
.NET framework is being deprecated in Nov 2020 and .NET core will be the sole supported .NET after that.

Currently we release builds in both .NET framework 4.9 and .NET core 2.0. The .NET core is cross-platform (can be used in Linux/Mac).

.NET core 2.0 does not support WPF (what we use for our GUI). But .NET core 3.0 does (but only in windows).

So we should wait for .NET core 3.0 to be released (Sept 2019), then transition to that exclusively, moving out of the soon-to-be deprecated .NET framework.

So currently we do:
.NET framework for windows GUI and command line
.NET core for cross-platform command line

In the future:
.NET core for cross-platform command line, and windows GUI

**Comment by acesnik** [comment]
Will .NET Core have tools for cross-platform GUIs like Java?

**Comment by rmillikin** [comment]
No. There are third party GUI packages that are compatible with .NET core, like https://github.com/AvaloniaUI/Avalonia . But no Microsoft-supported solutions.

**Comment by rmillikin** [comment]
I'd like to do a Linux/Mac GUI. Avalonia could be an option. Probably a ways in the future, though

**Comment by acesnik** [comment]
Could also make it a web application. 

My colleague is working on this to make visualizations for deep learning models. Maybe we could write a 
JavaScript kind of thing as a front end for MetaMorpheus. https://imjoy.io/#/app

**Comment by acesnik** [comment]
Then, we could run it on our phones, like @trishorts has always dreamed.

**Comment by trishorts** [comment]
Winner winner chicken dinner

**Comment by rmillikin** [comment]
https://blog.lextudio.com/offline-publishing-asp-net-core-apps-cf22f45158af

seems hard

**Comment by rmillikin** [comment]
I've gotten MM (CMD, GUI, installed GUI) working with .NET core. One positive is that Thermo .raw files can be read in Linux/Mac. I'd like to test these in a Linux system.

**Comment by rmillikin** [comment]
done in #1807
