### ISSUE TITLE
Lots of redundancy in ModsInfo in Protein Groups output

### ISSUE THREAD

**Issue by acesnik** [smith-chem-wisc/MetaMorpheus#1677]
Makes me wonder if we're counting them right if we're encountering the same modification site a bunch of times, each with 1 observation...
![image](https://user-images.githubusercontent.com/16342951/59885324-bf33b280-936f-11e9-98dd-9eb151208401.png)

**Comment by acesnik** [comment]
It also seems like this is only a problem with some modification types...

**Comment by acesnik** [comment]
It happens whenever there are two different modifications at the same site. Every mod after the first one isn't summed. It's just initialized in the dictionary with a count of 1 each time.
![image](https://user-images.githubusercontent.com/16342951/59885926-d83d6300-9371-11e9-9f7b-6f286bb39c0f.png)

**Comment by acesnik** [comment]
We should also sort by the aa# before writing to output

**Comment by acesnik** [comment]
I also don't get why there are no bar characters '|' in this column for protein groups with multiple members.

**Comment by rmillikin** [comment]
@lonelu can you take a look at this bug?

**Comment by acesnik** [comment]
Anyone tackling this bug?

**Comment by trishorts** [comment]
you've added the bars in the occupancy with multiple proteins but there is an extra semicolon. 
![image](https://user-images.githubusercontent.com/16841846/61242496-78856e00-a70b-11e9-89d8-7ae8aa7b813e.png)

**Comment by rmillikin** [comment]
fixed in #1695
