### ISSUE TITLE
System.ArgumentException: An item with the same key has already been added

### ISSUE THREAD

**Issue by talpa25** [smith-chem-wisc/MetaMorpheus#1683]
Dear Developer,

i have a bug when trying to run a XL-Search for disulfid-crosslinks. on the base of a GPTM-D database.

the report:
[results.txt](https://github.com/smith-chem-wisc/MetaMorpheus/files/3321542/results.txt).

Which information do you need more?

Best
Roman

**Comment by trishorts** [comment]
Thanks for notifying us of this error and thanks for sending us the results.txt file. We are reviewing the information that you sent to identify and fix the bug. We'll post a note here when we create a fix.

**Comment by talpa25** [comment]
Hi there,

did you make progress here?

best
Roman

**Comment by lonelu** [comment]
Hi,
Thanks for the message. We haven't test crosslink search with GPTMD database before. We figure out what happened here but don't have a chance to fix the bug because we cannot repeat it with our data. Could you please share your data and database to us?

**Comment by talpa25** [comment]
thx for the message, I'll leave you the files here:
https://drive.google.com/open?id=0B0VKdZCKDItLUU9ZakV6WHlxdzQ
enjoy and good luck - the option of GPTMD in combination with crosslinksearch is a standalone feature and will be very helpful not only for me!
best
Roman
