### ISSUE TITLE
Sequence Coverage Column in Protein Group Results

### ISSUE THREAD

**Issue by acesnik** [smith-chem-wisc/MetaMorpheus#1688]
We should change "Sequence Coverage %" to "Sequence Coverage Fraction" and then rows should be a fraction with more precision (e.g. 0.45827). It can come up as zero with long proteins and cause some confusion. Also, removing the % from the row entries will make it less annoying to format.

**Comment by rmillikin** [comment]
Sure. should be pretty easy

**Comment by rmillikin** [comment]
@acesnik can you make a PR with this change?

**Comment by acesnik** [comment]
Task an undergrad with it, por favor. 😄

**Comment by trishorts** [comment]
this is now in a pull request. anthony, would you review it?

**Comment by acesnik** [comment]
Resolved
