### ISSUE TITLE
MetaDraw: Load Spectrum stays overlayed when the window is minimized

### ISSUE THREAD

**Issue by zrolfs** [smith-chem-wisc/MetaMorpheus#1712]
![image](https://user-images.githubusercontent.com/16883585/63531971-4a940600-c4cf-11e9-95c4-b0054c66bd90.png)

**Comment by rudderbucky** [comment]
Could you give me steps to replicate the issue? When I minimize MetaDraw the loading window minimizes alongside it.

**Comment by rmillikin** [comment]
fixed in #1752
