### ISSUE TITLE
Modification Search Boxes Do Not Filter

### ISSUE THREAD

**Issue by mobiusklein** [smith-chem-wisc/MetaMorpheus#1713]
OS: Windows 10

I set up a Calibrate task and the modification search boxes filtered the modification list. However, typing in the search boxes on the GPTM-D and Search task windows did not filter the lists.

![image](https://user-images.githubusercontent.com/1426041/63595225-67d7db80-c586-11e9-9113-504b4fafe597.png)

![image](https://user-images.githubusercontent.com/1426041/63595525-2b58af80-c587-11e9-85ec-17a156ee1f39.png)

After restarting MetaMorpheus, the first task I opened was the Search window, and the search box worked.

![image](https://user-images.githubusercontent.com/1426041/63595691-8d191980-c587-11e9-9bc4-f733b7fb3fa6.png)

I can't see any sort of shared state in the GUI code that would explain this doing a cursory examination.

**Comment by rmillikin** [comment]
Thanks for the report! I was able to reproduce this bug.

Step 1: Open a task. Doesn't seem to matter what task it is, if you search for a mod or not, whether or not you cancel or add the task
Step 2: Open a different task. Search for mod. Search doesn't work

**Comment by rmillikin** [comment]
fixed in #1739
