### ISSUE TITLE
Calibrating a Non-specific Digest Finds No Peptides

### ISSUE THREAD

**Issue by mobiusklein** [smith-chem-wisc/MetaMorpheus#1714]
Running the Calibrate task with a non-specific digest failed to match any peptides, even after expanding its tolerance several times. I have insufficient information from the log to determine if there were matches but they failed to pass the FDR threshold. The search also runs unexpectedly quickly, but I do not know if the Calibrate task takes some shortcuts.

I know the sample has around 3000 good spectra and ~1250 reasonable peptide IDs from searching it with other tools.

**Comment by rmillikin** [comment]
Thanks for the report - @zrolfs can you comment on this?

**Comment by zrolfs** [comment]
Hi mobiusklein,
It sounds like the maximum number of missed cleavages wasn't changed to accomodate the non-specific digestion. For these digestions, each residue can be cleaved, so each if the max missed cleavage parameter is set to 2 (which is the default for fully-specific digestions), then the search will only include 3-mers and will run very fast. Let me know if this resolves your issue. 
![image](https://user-images.githubusercontent.com/16883585/63605219-1e41bd80-c593-11e9-9839-c20b766e3fde.png)

**Comment by rmillikin** [comment]
@zrolfs  I thought there was some "reasonable" default value set here for the max missed cleavages upon selecting the non-specific search. If you select non-specific search is the max missed cleavages still set at 2?

**Comment by zrolfs** [comment]
@rmillikin The functionality described is implemented in the search task, but not Calibration, GPTMD, or XL.

**Comment by rmillikin** [comment]
sounds good. maybe @bintiibrahim can change this with your guidance
