### ISSUE TITLE
Another crash - this time during FDR calculation

### ISSUE THREAD

**Issue by Dmorgen** [smith-chem-wisc/MetaMorpheus#1744]
please see attached files. thanks!

[Task2-GPTMDTaskconfig - Copy.toml.txt](https://github.com/smith-chem-wisc/MetaMorpheus/files/3693392/Task2-GPTMDTaskconfig.-.Copy.toml.txt)
[Task3-SearchTaskconfig - Copy.toml.txt](https://github.com/smith-chem-wisc/MetaMorpheus/files/3693393/Task3-SearchTaskconfig.-.Copy.toml.txt)
[Task1-CalibrateTaskconfig - Copy.toml.txt](https://github.com/smith-chem-wisc/MetaMorpheus/files/3693394/Task1-CalibrateTaskconfig.-.Copy.toml.txt)
[results.txt](https://github.com/smith-chem-wisc/MetaMorpheus/files/3693396/results.txt)
[results.txt](https://github.com/smith-chem-wisc/MetaMorpheus/files/3693398/results.txt)

**Comment by trishorts** [comment]
I'll make sure we are on top of this. Thanks for the report!

**Comment by trishorts** [comment]
I notice you were using single nucleotide substitutions. It's my experience that these can be very error prone.

**Comment by Dmorgen** [comment]
Yeah, I know – I manually validate such ID’s. thanks!

D.

**Comment by trishorts** [comment]
Related....If you have general interest in detecting all manner of sequence variants, we have a new tool that's is nearly ready to be sent for publication that creates sample specific proteogenomic databases from RNA seq. This database is written to be read by MM, of course, and can contain known PTMs (which is different from other proteogenomic databases). If you have RNA seq data for your sample, or you are using a cell line with RNA-seq data from GEO, I'd be happy to assist you with a test drive. This database is yielding superior results to our prior efforts in proteogenomics.

**Comment by Dmorgen** [comment]
That’s very interesting, thanks! We have a few such projects in the pipeline. Our biggest challenge now is working with orgnisms which don’t have any DB, and we’re using a DB from a near species/genus. This is me testing MM for the suitability of such analysis. ☺

Cheers,
D.

**Comment by trishorts** [comment]
One new feature, which you may not have noticed yet is that we added some post processing that computes PSM-level posterior error probabilities. This computation considers multiple factors beyond psm score (e.g. number of consecutive fragment ions, delta score, peptide retention time, etc.). It should work well for the types of peptides you are examining. In this case, look at the far right column of output (PEPQvalue) and consider those PSMs with QValue < 0.01. You'll find some PSM have traditional q-value below 0.01 do not have PEPQvalue below 0.01 and vice versa. I think those variants that make the PEP cut will be more worth your time w.r.t. validation.

**Comment by Dmorgen** [comment]
Awesome, thanks!
D.

**Comment by rmillikin** [comment]
Apologies for the late reply. I believe this crash is the same as #1606 . The e-value calculation was removed in v0.0.302 in favor of a PEP (posterior error probability) calculation, so I think the crash should no longer occur with the new version. Can you run the search with the new MM and see if it works?

As a side note, @zrolfs recommended to me that you try the "Semi-Specific Search" instead of "Modern" because it should be faster. He can chime in if you need help setting that up.

**Comment by zrolfs** [comment]
Hello! 
Here's a quick wiki if you decide to try out the Semi-Specific Search: https://github.com/smith-chem-wisc/MetaMorpheus/wiki/Speedy-Semi--and-Non-Specific-Enzyme-Searches

As always, I'm happy to help answer any questions!

**Comment by zrolfs** [comment]
One last thing: If you do use the Semi-Specific Search, set your protease to "trypsin" instead of "semi-trypsin" (counter-intuitive). I'm not sure what the behavior will be otherwise.

**Comment by Dmorgen** [comment]
Thanks to both of you! 
one question - do I need to match the same parameters in the GPTMD search? does it matter at all?

D.

**Comment by zrolfs** [comment]
The searches operate independently, so you don't need to match the same parameters. I would just reuse the GPTMD database for the search, rather than redoing the GPTMD task.

**Comment by rmillikin** [comment]
I'm going to close this because I suspect this crash has been fixed, but feel free to reopen this issue or open a new one if you encounter this problem again.
