### ISSUE TITLE
running MetaMorpheus is command line

### ISSUE THREAD

**Issue by SimionKreimer** [smith-chem-wisc/MetaMorpheus#1753]
When I unzip "MetaMorpheusDotNetFrameworkAppVeyor.zip" it looks like an empty folder, the file itself is only 22 bytes. Also not sure how running CMD.exe -t would work, isn't CMD.exe the command line editor. Sorry, a bit of a newb here.

**Comment by trishorts** [comment]
We're working on that right now. Please use the previous version until we can make a new release. This is only a command line issue and there have been no really big changes that would alter your results. There are some small bug fixes and addition of new features. Let us know if you have trouble to get the previous release.

**Comment by rmillikin** [comment]
We're having an issue building the command-line version via our pipeline, sorry about that. I have built+uploaded 0.0.302. Please let us know if you encounter any issues.
