### ISSUE TITLE
Crash when entering custom cross-linker

### ISSUE THREAD

**Issue by mriffle** [smith-chem-wisc/MetaMorpheus#1754]
Greetings, when I go to: "Data" -> "Create new crosslinker" and enter the following parameters, and click "Save Crosslinker", all windows for the program close (ie crashes) and the cross-linker is not saved.

Crosslinker Name: EDC
Crosslinker Total Mass: -18.0105633
Crosslinker Amino Acids: K
Crosslinker Amino Acids 2: DE
H2O Quench Mass: -0.9837153

Using:

MetaMorpheus 0.0.302.
Windows 10 Pro

**Comment by mriffle** [comment]
Thinking it might be the negative values, also tested with values corresponding to DSS, and the same crash still happens.

**Comment by trishorts** [comment]
Thanks. We'll look at it this morning. Should be another release soon so we can get that fixed up.

Thanks also for the Proxl update. Your website is amazing. I think that I'm going to add a link to proxl in the metamorpheus GUI so folks can find it easier. what do you think of that?

**Comment by mriffle** [comment]
Great, thanks for taking a look.

Adding a link to Proxl from the GUI would be amazing, thanks so much.

**Comment by lonelu** [comment]
Thanks for the issue report. This is a GUI bug, which I haven't consider default empty DissociationType for the crosslinker.
You can input "HCD" now as a 'fake' dissociation type to use it. The bug will be fixed in the next release.

**Comment by rmillikin** [comment]
has this crash been fixed?

**Comment by lonelu** [comment]
Fixed
