### ISSUE TITLE
GUI updates

### ISSUE THREAD

**Issue by trishorts** [smith-chem-wisc/MetaMorpheus#1772]
I'd like mouse-over text for number of partitions.
![image](https://user-images.githubusercontent.com/16841846/68775371-f98a3e80-05f3-11ea-8488-6cc11d59cc98.png)

**Comment by zrolfs** [comment]
There is mouse-over text for the partitions, but you can't view it when the box is disabled. I don't think we're able to assign the tool-tip to a label.
