### ISSUE TITLE
Cali and GPTMD non-specific proteases have an immutable max length and number of cleavages

### ISSUE THREAD

**Issue by zrolfs** [smith-chem-wisc/MetaMorpheus#1774]

**Comment by rmillikin** [comment]
what does this mean?

**Comment by zrolfs** [comment]
There is a bug where you can't change the max length or number of missed cleavages when the nonspecific protease is selected. You can change it, but it gets reset upon reopen.

**Comment by zrolfs** [comment]
Found it: https://github.com/smith-chem-wisc/MetaMorpheus/pull/1770/commits/656bf1ddbc7a66dcb8a7a08d3d98188bc5326357

You can change the params, but, when you reopen the toml in the GUI, the params are overwritten.
