### ISSUE TITLE
couple of requests re metadraw

### ISSUE THREAD

**Issue by Dmorgen** [smith-chem-wisc/MetaMorpheus#1791]
Hi Guys,

Long time!

couple of requests: 
1. would it possible to allow to load more than 1 raw/mzml files? 
2. would it be possible to make "fuller" annotations? sometimes it looks like mixed spectra where it is actually neutral losses 

Thanks!
D.

**Comment by trishorts** [comment]
Good morning from Wisconsin. Rob has been tinkering with MetaDraw lately. I'll see if these are changes that he can integrate with the next release. Loading data from multiple raw files might be tricky. We'll see.

**Comment by Dmorgen** [comment]
Thanks! And good luck ☺

**Comment by rmillikin** [comment]
Hi there @Dmorgen ,

We have plans to load more than 1 file into MetaDraw. Really, it would be loading the metadata for an essentially unlimited number of spectra files into MetaDraw, and then upon you selecting a scan to draw, the scan is grabbed out of the corresponding file and plotted. The "hard part" is done for the most part but it has sort of stalled a bit and requires some internal discussion about how to proceed. I can make this a priority next week.

As for neutral losses - do you mean that some spectra look like co-isolated peptides, but it's really just one peptide with water loss, ammonia loss, etc. on the fragments? Or are you referring to neutral losses on modifications?

**Comment by Dmorgen** [comment]
Hi,

That’d be awesome! We’ve used the software this week for a proteoinformatics course we’re running and that would make life easier.

Re neutral losses – the former. I’m using Byonic viewer as a comparison, and it’s really detailed. This is super important when inspecting any unique modification MM finds.

If we’re at it, another request – the search produces individual mzID files. Can you generate one that combines them all?

Thanks!
D.
