### ISSUE TITLE
Automatically save protease as a file specific setting when files are calibrated

### ISSUE THREAD

**Issue by rmmiller22** [smith-chem-wisc/MetaMorpheus#1800]
When files are calibrated, a fail specific toml is automatically created to save the search tolerances. When this is created we should just automatically save the protease that was used for the calibration as well.

**Comment by rmillikin** [comment]
if the file was calibrated with a file-specific protease, the file-specific protease should get carried over to the new file-specific toml. can you test this functionality on 0.0.303 and the current master? if it's missing, it's a bug

**Comment by trishorts** [comment]
Also add separation mode to file specific settings
