### ISSUE TITLE
Mono (linux)

### ISSUE THREAD

**Issue by rmillikin** [smith-chem-wisc/MetaMorpheus#1801]
MM works well with .NET core in Linux but I'd like to check that it also works well with Mono, since some people are using that

**Comment by acesnik** [comment]
Why are they using mono? I know `conda` doesn't have dotnetcore, so mono is the only option there at the moment.

**Comment by acesnik** [comment]
(Although I found a workaround in Spritz to get dotnetcore anyway.)

**Comment by acesnik** [comment]
https://github.com/smith-chem-wisc/MetaMorpheus/issues/2036
