### ISSUE TITLE
How to install  MetaMorpheus on Linux?

### ISSUE THREAD

**Issue by lhuangjs** [smith-chem-wisc/MetaMorpheus#1808]
The command-line version is supported on Linux. However, I cannot find an Installation Manual. Can anyone help me？ 
Thanks！

**Comment by rmillikin** [comment]
Welcome to MetaMorpheus!

I've just added a new Wiki page describing how to use MetaMorpheus via command-line: https://github.com/smith-chem-wisc/MetaMorpheus/wiki/Using-the-Command-Line

Note that you'll need to install .NET Core version 2.1. I found it a bit difficult to get that particular version installed, as the current version is 3.0 or 3.1. MetaMorpheus will soon be updated to that version of .NET Core. Feel free to post here for more help or email us at mm_support at chem dot wisc dot edu :)

**Comment by rmillikin** [comment]
I should probably mention - to download MetaMorpheus for Linux, go to the [latest release](https://github.com/smith-chem-wisc/MetaMorpheus/releases/latest) and download the "MetaMorpheusDotNetCoreAppveyor.zip" package. This contains the .NET Core command-line version of MetaMorpheus.
