### ISSUE TITLE
Crash when trying to write long file paths; error message not informative

### ISSUE THREAD

**Issue by rmillikin** [smith-chem-wisc/MetaMorpheus#1815]
@blfrey got this error

When trying to write a filename, Windows has a maximum path length of 260 characters. If a filepath is longer than that, an exception is thrown with the message that "part of the path could not be found". We should check to see if the path length is >260 characters, catch the exception, perhaps write the file with a truncated name, and/or display a more meaningful error message

**Comment by rmillikin** [comment]
fixed in #1868

**Comment by rmillikin** [comment]
i've actually decided against fixing this. windows 10 and up no longer has this issue (paths >260 characters are allowed) and so it's difficult to figure out when this error is going to occur before it happens. the exception thrown is sort of a generic error message and i think is difficult to handle. and it's rare enough that i think it's not a major problem. could revisit it at some point though.

**Comment by blfrey** [comment]
OK. that is fine by me.   But, just saying, that I'm pretty sure Artemis already had Windows 10 when this issue came up.

**Comment by acesnik** [comment]
Does this file need to be updated somehow? https://github.com/smith-chem-wisc/MetaMorpheus/blob/master/GUI/app.manifest

That's how Stefan fixed this way back.
