### ISSUE TITLE
GPTMD pruned database does not follow parameters

### ISSUE THREAD

**Issue by lschaffer2** [smith-chem-wisc/MetaMorpheus#1820]
Photo shows the parameters selected for the pruned database, however other mod types appeared (artifacts, etc). The protein-pruned database seems to accurately prune PTMs, so it's just the regular pruned database. 
![image](https://user-images.githubusercontent.com/16846041/73297508-5055ec00-41d1-11ea-8f20-6d349cd997a2.png)

**Comment by lschaffer2** [comment]
This functionality is important for subsequent top-down/intact-mass searches to prevent a huge DB increase while not taking out proteins not seen in BU. Observed PTMs means those at 1% FDR.  Want to keep all proteins and any UniProt mods because of low BU sequence coverage for a typical experiment.

**Comment by rmillikin** [comment]
fixed in #1831
