### ISSUE TITLE
Incorrect ambiguity reporting for N-term mods

### ISSUE THREAD

**Issue by lschaffer2** [smith-chem-wisc/MetaMorpheus#1821]
For a top-down search with N-term acetyl as a variable mod, I notice this being reported as ambiguous. Note there's also a repeat for some reason. 

[Common Biological:Acetylation on X]AGQAFRKFLPLFDRVLVERSAAETVTKGGIMLPEKSQGKVLQATVVAVGSGSKGKGGEIQPVSVKVGDKVLLPEYGGTKVVLDDKDYFLFRDGDILGKYVD|[Common Biological:Acetylation on X]AGQAFRKFLPLFDRVLVERSAAETVTKGGIMLPEKSQGKVLQATVVAVGSGSKGKGGEIQPVSVKVGDKVLLPEYGGTKVVLDDKDYFLFRDGDILGKYVD|[UniProt:N-acetylalanine on A]AGQAFRKFLPLFDRVLVERSAAETVTKGGIMLPEKSQGKVLQATVVAVGSGSKGKGGEIQPVSVKVGDKVLLPEYGGTKVVLDDKDYFLFRDGDILGKYVD|[UniProt:N-acetylalanine on A]AGQAFRKFLPLFDRVLVERSAAETVTKGGIMLPEKSQGKVLQATVVAVGSGSKGKGGEIQPVSVKVGDKVLLPEYGGTKVVLDDKDYFLFRDGDILGKYVD

**Comment by rmillikin** [comment]
this was fixed in mzlib by @bintiibrahim  ( https://github.com/smith-chem-wisc/mzLib/pull/533 ) and will be included in MM in an mzLib update (probably #1863 )
