### ISSUE TITLE
MetaMorpheus for HLA peptide search

### ISSUE THREAD

**Issue by fazeliniah** [smith-chem-wisc/MetaMorpheus#1822]
Hi, 
We would like to try MetaMorpheus for searching MS2 data for HLA class I peptides. Is there any good reference that I can follow? The searches should be "unspecific" for protein digestion. Our Fasta databased includes ~96000 entries.
Thanks

**Comment by trishorts** [comment]
You certainly can do HLA searches. Here are the settings that I use, which will get you out to 25 (which is pretty far out as most will be 9,10,11mers ) 
![image](https://user-images.githubusercontent.com/16841846/73544789-92fd0b80-43ff-11ea-818e-7839e1b12235.png)

**Comment by trishorts** [comment]
I also set the precursor to "exact" in advanced options. 
![image](https://user-images.githubusercontent.com/16841846/73544911-cfc90280-43ff-11ea-88f2-1d2e1fdf0bf6.png)

**Comment by trishorts** [comment]
Keep your eye out for a new release of MetaMorpheus. We're adding a machine learning tool computes peptide identification probabilities. This tool really improves the yield and quality of HLA peptides. An early version is currently implmented (and you can see its output in the rightmost column). But, consider that a beta. The better version will be out soon hopefully.

**Comment by fazeliniah** [comment]
This is really useful. Thank you very much for your quick reply.  I will give it a try next week and let you know how it goes.

**Comment by trishorts** [comment]
great. please stay in contact. really want to hear about your experience and make sure that you are successful. let us know of any problems that you run into

**Comment by fazeliniah** [comment]
I just finished running MetaMorpheus for our HLA class I searches. We had been using MaxQuant for the same purpose and now I have the results to compare. Here are couple of questions/comments. 
1- MetaDraw is very useful for visualization of the annotated spectra but can we import the MetaMorpheus into PDV? (https://github.com/wenbostar/PDV)
2- Is there a way to sort the PSMs in MetaDraw (based on score/PEP)? This will help to inspect the spectra. 
3- Is there any program that can help with visualization of the output? We found PTXQC to be very useful for visualization of MaxQuant tables. Similar program will be really useful for MetaMorpheus.
4-  In one of my samples there are  550 "peptides within 1% FDR". However, there are 511 "target PSMs within 1% FDR". I am wondering why there are more peptides than PSMs? 
5- In the PSM/peptide/proteins lists, how can I select the ones that are within the 1% FDR?
Thanks for your help in advance.

**Comment by zrolfs** [comment]
Hi fazeliniah!
Thanks for trying out our software! We have a few recommendations for HLA searches, which you can find here: https://github.com/smith-chem-wisc/MetaMorpheus/wiki/Non-specific-cleavage-(%22No-Enzyme%22,-%22Non-specific%22)-searches

1- PDV should be able to accept the .mzID result file. Let us know if you have any problems.
2-We currently don't have this functionality built in, but it's pretty easy for us to do so. We'll try to get this into the next release!
3-Not sure... @rmillikin  @trishorts ?
4- The PSM and peptide FDRs are calculated separately. It is possible (though unlikely) that of the 6 decoy PSMs identified, some of them were from the same peptide. In the peptide FDR, there may have been 550 unique peptide sequences before 6 unique decoy sequences were identified. If this is not the case, please let us know.
5-If you scroll over to the "QValue" column, you can select every peptide with an entry less than 0.01

**Comment by trishorts** [comment]
4. if you send us the psm/peptide files, i will review them and try to help you understnad.  use mm_support@chem.wisc.edu

5. I usually open in excel and use the Filter functionality. Filter based on target and also filter based on q value <=0.01. You could save that and load into metadraw.

Also, the PEP value functionality that I mentioned to you considers the retention time of each peptide in the score. To get that set use the group that are PEP QValue <= 0.01. Those should be more reliable peptides (also also more in number). If you can't figure that out. let me know i'll help.

SSRCalc is an excelllent way to confir as mentioned by zach above.
