### ISSUE TITLE
MetaDraw fragment annotation colors are inverse from SeeMS

### ISSUE THREAD

**Issue by zrolfs** [smith-chem-wisc/MetaMorpheus#1824]
Just kinda confusing. Example here: https://github.com/smith-chem-wisc/MetaMorpheus/issues/1823

**Comment by rmillikin** [comment]
isn't this subjective? or is there is a consensus in the field of what colors to annotate what ions?

**Comment by rmillikin** [comment]
for example http://www.interactivepeptidespectralannotator.com/PeptideAnnotator.html annotates y ions in red and b ions in blue

**Comment by zrolfs** [comment]
Sure, I agree it's subjective with no consensus. But it sure seems like whoever picked our default colors was referencing SeeMS. I would prefer the dark red (y) and blue (b), honestly.

**Comment by rmillikin** [comment]
I don't have a PR for it open yet but I have some metadraw edits coming soon™ and I can make this color change
