### ISSUE TITLE
syntax in MPI contaminants database

### ISSUE THREAD

**Issue by blfrey** [smith-chem-wisc/MetaMorpheus#1828]
The syntax in the MPI Contaminants DB does not completely mesh with MM.   The problem is that the contaminant protein names (and gene name and organism) don’t get listed in the AllProteins.tsv output file.    Those fields are in the FASTA entries, but not in the same way that UniProt FASTA lists them.    Where does that DB come from? Should we get an updated one? Should we use cRAP instead?  Should we change MM to output from that syntax, or change the database instead?    Willing to help if there is something I could do.

**Comment by trishorts** [comment]
this is one that was inside maxquant whenever that was added to MM

**Comment by rmillikin** [comment]
@blfrey made this new DB, just need to include it in MM

**Comment by trishorts** [comment]
are you going to take care of that rob?

**Comment by rmillikin** [comment]
yep

**Comment by blfrey** [comment]
Thanks @rmillikin.   I guess you could read my mind b/c I was just thinking that with all the MM updates, my new database should go in as default.  Are we making the .fasta one default or the .xml that includes methylations on trypsin (and also has GPTM mods from UniProt)?

**Comment by rmillikin** [comment]
My preference would be to make the XML default, but if other people want the fasta for some reason we could do that, or have a button for each one

**Comment by blfrey** [comment]
OK with me.  I do think the methylated trypsin is a big plus.

**Comment by rmillikin** [comment]
added the new .xml (+methylated trypsin) in #1924
