### ISSUE TITLE
Stuck on FDR analysis for TMT run

### ISSUE THREAD

**Issue by acesnik** [smith-chem-wisc/MetaMorpheus#1836]
![image](https://user-images.githubusercontent.com/16342951/74199820-e1de4880-4c2a-11ea-937e-eef0dfaccd5a.png)

It's been running for ~100 hrs

I put the files in \\bison\share\Projects\MetaMorpheus\TMTFdrAnalysisFrozen

**Comment by zrolfs** [comment]
I am 95% confident this is because of PEP and not TMT related. PEP currently sucks for multiple files (or large numbers of psms).

**Comment by acesnik** [comment]
Hmm, thanks for the perspective. I'm trying it with one file currently (fxn 9), and it's been FDRing for a day now.

**Comment by acesnik** [comment]
Looks like there are improvements coming down the pipe (this one, I think: https://github.com/smith-chem-wisc/MetaMorpheus/pull/1829/files). Looking forward to seeing what they can do!

**Comment by zrolfs** [comment]
> Hmm, thanks for the perspective. I'm trying it with one file currently (fxn 9), and it's been FDRing for a day now.
That sort of pokes a hole in my PEP suggestion. Do you have a file we could check out?

**Comment by trishorts** [comment]
Did you use tmt as fixed mod?

**Comment by acesnik** [comment]
I used TMT 6plex as a fixed mod. The files are located in  `\bison\share\Projects\MetaMorpheus\TMTFdrAnalysisFrozen` including the TOML. I'm using fraction 9 for the one-file test.

**Comment by trishorts** [comment]
I'll search.  What organism

**Comment by acesnik** [comment]
Human -- U2OS cells. I tried doing CPU profiling but VS 2019 errored out on me.

**Comment by trishorts** [comment]
This morning on my branch I performed GPTMD and Search with protein parisimony, etc. and the total search times was completed in under 11 minutes. I put the output with .tomls in that same folder on the bison.

**Comment by trishorts** [comment]
I did not use metals in gptmd but left the common biological and artifact as is.

**Comment by trishorts** [comment]
I did GPTMD and Search with parsimony on the file you tried and one other and the total time was < 26 minutes. I also put that folder on bison. Not sure what the delay on your end is. You used 23 cores and I used 27 or 28. not a big difference. I began w/ FASTA and not xml. Maybe there is something there. I'm using xml less lately because gptmd is working well and I don't really see much advantage keeping other mods around.

**Comment by acesnik** [comment]
Thanks for checking that out. That's impressively fast. Is the FDR analysis on your branch different than the current release?

**Comment by trishorts** [comment]
yes. the PEP is improved, but the branch I ran your stuff does not even have the advances from parallelization. 
the branch from this pull request would be fastest: https://github.com/smith-chem-wisc/MetaMorpheus/pull/1829

for your search I used the branch from this PR; https://github.com/smith-chem-wisc/MetaMorpheus/pull/1832

**Comment by acesnik** [comment]
Thanks! Your PR, https://github.com/smith-chem-wisc/MetaMorpheus/pull/1832, did fix whatever issue is going on here. I'm running the full dataset now.

**Comment by rmillikin** [comment]
resolved in #1832

**Comment by acesnik** [comment]
#1832 wasn't merged, so I wonder if this should be reopened. I'm testing v305 now. 

It'd be nice to have a MetaMorpheus version number to attach to a paper that may be coming back for revision later this month. :)

**Comment by acesnik** [comment]
https://github.com/smith-chem-wisc/MetaMorpheus/pull/1874 is the new PR... I haven't tested it for this bug, yet.

**Comment by trishorts** [comment]
i think thing PRs might have gotten crossed somewhere. I dont' think that the protein p-value PR is the solution to  your TMT woes. I do think that the current version, which has many updates included that to peptide PEP might solve the problem. Suggest you run a test search to see if the times look okay w/ version 305 before running a monster search. I think 305 will have solved your problems. I have a new version of a protein p-value calcuation that is now in a separate WIP PR that I am happy with (as of just a few moments ago). I am happy to test that out on your data if that would help you.  Please keep us informed on the status of your search. We want to make sure MM is working for you.

**Comment by acesnik** [comment]
Thanks for clarifying! It looks like v305 is indeed working for one file. Going to run the whole set through now.
