### ISSUE TITLE
PSM/Peptide output reporting "Num Variable Mods" incorrectly adds fixed mods to the number

### ISSUE THREAD

**Issue by trishorts** [smith-chem-wisc/MetaMorpheus#1849]
The output is reporting the sum of all mods on a peptide (fixed and variable). Maybe we need count of fixed, count of variable, and total mods. I'm not beholden to any particular solution. But, I would like this to be clarified and correctly reported.

**Comment by rmillikin** [comment]
I'm not observing this behavior in the current release - is this a bug on an unreleased branch?

![Capture](https://user-images.githubusercontent.com/24705713/78191415-929ee200-743b-11ea-8d8a-70b0a161121e.PNG)

**Comment by trishorts** [comment]
i will check myself quickly in latest release and close if error not present

**Comment by trishorts** [comment]
not trouble observed in release 305. closing.
