### ISSUE TITLE
Weird Sequence Coverage, Sequence Coverage with Mods, and Modification annotation MM v0.0.305 (and 0.0.304 too)

### ISSUE THREAD

**Issue by algom** [smith-chem-wisc/MetaMorpheus#1870]
Hello all,

I'm trying out MetaMorpheus v0.0.305, in Win10 (have tried too v0.0.304), I tried running the example vignette and it all goes through well, however upon inspection of the allProteinsGroup.tsv in Notepad++ and in R, the file seems to have some broken lines. I don't get the content of Sequence Coverage, Sequence Coverage with Mods, and Modification columns it is filled with annotations like:

mpkphseagtafiqtqqlhaamadtflehmcrLDIDSAPITARntgiictigpasrsvemlkemiksgmnvarLNFSHGTHEYHAETIKnvrEATESFASDPILYRPVAVALDTKgpeirtglikgsgtaevelkkgatlkITLDNAYMEKCDENILWLDYKnickVVEVGSKiyvddglislqvkekGADFLVTEVENGGSLGSKKGVNLPGAAVDLPAVSEK

Which I guess has some part of the sequence but I don't understand the rest. More over in some cases, it is so long that breaks the line so the new lines appear just filled with that:

mttqapmftqplqsvvvlegstatfeahvsgspvpevswfrdgqviststlpgvqisfsdgrarlmipavtkansgryslratngsgqatstaellvtaetappnfsqrlqsmtvrqgsqvrlqvrvtgiptpvvkfyrdgaeiqssldfqisqegdlyslliaeaypedsgtysvnatnsvgratstaelvvqgeevvpakktktivstaqisetrqtriekkieahfdarsiatvemvidgatgqlp
glkyriqefkggyhqliiasvtdddatvyqvratnqggsvsgtaslevevpakihlpktlegmgavhalrgevvsikipfsgkpdpvitwqkgqdlidnnghyqvivtrsftslvfsngverkdagfyvvcaknrfgidqktveldvadvpdpprgvkvsdvsrdsvnltwtepasdggskvtnyivekcattaerwlrvgqaretrytvinlfgktsyqfrviaenkfglskpsepseptvtked
glkyriqefkggyhqliiasvtdddatvyqvratnqggsvsgtaslevevpakihlpktlegmgavhalrgevvsikipfsgkpdpvitwqkgqdlidnnghyqvivtrsftslvfsngverkdagfyvvcaknrfgidqktveldvadvpdpprgvkvsdvsrdsvnltwtepasdggskvtnyivekcattaerwlrvgqaretrytvinlfgktsyqfrviaenkfglskpsepseptvtked

I tried with files of my own and the same happens as welll as with the 0.0.304 version.

Any hint what could it be?

Best,

Alejandro

**Comment by rmillikin** [comment]
Hi Alejandro,

I'm assuming you're using Excel to view these files (I do too). The line breaks occur because Excel only allows 32000 characters in a single cell. If the cell contains more than 32000 characters, the line wraps to the next line.

You can make MetaMorpheus write Excel-compatible output by going to Settings -> Close MetaMorpheus and open global settings file -> change "WriteExcelCompatibleTSVs" from "false" to "true". We may make this the default behavior for MetaMorpheus but there is some internal disagreement about what the default behavior should be.

That may solve your problem - can you change that and repost here if you still encounter problems?

**Comment by rmillikin** [comment]
Note that by enabling this setting, if the line is too long for Excel, "Too long for Excel" will be written instead of the expected output.

**Comment by rmillikin** [comment]
I don't know if there are similar limits for tab-delimited content in R. I'm not sure if Notepad++ has a tab-delimited viewing style.

In terms of interpreting the output:
mpkphseagtafiqtqqlhaamadtflehmcrLDIDSAPITARntgiictigpasrsvemlkemiksgmnvarLNFSHGTHEYHAETIKnvrEATESFASDPILYRPVAVALDTKgpeirtglikgsgtaevelkkgatlkITLDNAYMEKCDENILWLDYKnickVVEVGSKiyvddglislqvkekGADFLVTEVENGGSLGSKKGVNLPGAAVDLPAVSEK

The capitalized portions of the sequence were confidently observed but the lower case portions were not. If there are no mods annotated, it means that no mods were observed for that sequence. I'm not sure if fixed mods would be displayed but I'm guessing not.

**Comment by algom** [comment]
Thanks, setting up that doesn't break it anymore!
So, to get it correctly about the output. That would be the entire sequence of the protein taken from the FASTA file and in capital letters are the identified peptides?

Thank you!

**Comment by rmillikin** [comment]
Yep the entire sequence of the protein is displayed, and the capital letters are the identified peptides
