### ISSUE TITLE
AllProteinGroups.tsv output anomalies

### ISSUE THREAD

**Issue by bhampton-som** [smith-chem-wisc/MetaMorpheus#1871]
Hello,
When opening any AllProteinGroups.tsv with Excel there are certain lines that appear usually at the bottom that contain a large amount of amino acid sequence information not associated with a protein group all by itself.  If I open with Libreoffice Calc these line(s) appear at the top.  I am wondering if this affects the data integrity and whether it can be corrected on my end or yours.

Also, when I relabel the column headings of an AllProteinGroups.tsv file to be compatible with LFQAnalyst; the output from that R analysis shows certain protein groups appear to have data from many many protein groups contained within their columns as a single protein group.  Combined with the above there seems that maybe "garbage" characters or something is output from MetaMorpheus that causes misformatting of the data which causes problems in Excel and LFQAnalyst.  
I can provide a file if you think that can be of use.

**Comment by rmillikin** [comment]
Can you send me your AllProteinGroups.tsv file (via email)? That's pretty strange, I've never encountered that behavior before.

**Comment by bhampton-som** [comment]
Will do!  I’m doing bench work at the moment so I’ll send it later.

Cheers,
Brian
