### ISSUE TITLE
MS files don't always get added to the GUI.

### ISSUE THREAD

**Issue by zrolfs** [smith-chem-wisc/MetaMorpheus#1876]
This is a super weird bug where when I drag and drop a folder, only one of the files from that folder is added in the GUI. If I use the "Add" button instead of drag and drop, I get a crash.

Works fine for 3/4 of my folders. Reproducibly has this problem for one of them. File path length is <260 char.

**Comment by zrolfs** [comment]
This appears to occur because the (custom) protease specified in the file-specific toml is not present in the proteases.tsv file after updating. This is still a pretty strange behavior, though. I think we should throw a warning rather than just ignore it, and none of the files should be added if their tomls aren't valid?

**Comment by rmillikin** [comment]
fixed in #1877
