### ISSUE TITLE
Hitting script length limit in Powershell

### ISSUE THREAD

**Issue by acesnik** [smith-chem-wisc/MetaMorpheus#1901]
I just encountered a Powershell issue with the commandline program. Running 400 spectra files or so, and I run into this:
![image](https://user-images.githubusercontent.com/16342951/81959902-c68e2b00-95d5-11ea-869b-7ad551ea2e95.png)

Turns out there's a script length limit in Powershell.
http://systemcentersynergy.com/max-script-block-size-when-passing-to-powershell-exe-or-invoke-command/

Looks like the solution is to make the huge parameter list (spectra files) into a file. I think in this case we should allow the option of using a spectrum file list.
https://support.microsoft.com/en-gb/help/830473/command-prompt-cmd-exe-command-line-string-limitation

**Comment by rmillikin** [comment]
fixed in #1985 . you can just specify a directory w/ spectra files now.
