### ISSUE TITLE
Write Indexed mzML for Calibrated files

### ISSUE THREAD

**Issue by trishorts** [smith-chem-wisc/MetaMorpheus#1925]
We have the ability to write indexed mzML files but we do not after calibration. Non-indexed mzML files take longer to load with a dynamic connection. It would be nice to have fast dynamic connection for MetaDraw (and possibly for scan aggregation). Writing indexed is a small change but I don't know if there are other ramifications.

**Comment by rmillikin** [comment]
done in #1930
