### ISSUE TITLE
Experimental Design for samples with multiple fractions

### ISSUE THREAD

**Issue by CoCLu** [smith-chem-wisc/MetaMorpheus#1934]
Hi all, 
I have a few questions about the experimental design for samples with multiple fractions. 

I have 4 samples, and each sample was separated by SDS-PAGA resulting in 8 fractions. Thus, there are 32 RAW files for 4 samples in total. There is no BioRep or TechRep. Where should I put the sample name like MaxQuant? the Condition column?

One more question about 'match between run'. Does it work like MaxQuant using the fraction number to decide which files to match? 

Thank you. 

best, 
C

**Comment by rmillikin** [comment]
Hi C, sorry for the late reply. You can just number the samples such as sample 1, sample 2, sample 3, sample 4. Then each sample will have fractions 1 through 8. They can all be the same condition.

I believe the current release version of MM does not use the fraction number for MBR but the next release will only match fractions +-1. So fraction 4 will be matched to fractions 3, 4, and 5 of the other samples.

**Comment by CoCLu** [comment]
> Hi C, sorry for the late reply. You can just number the samples such as sample 1, sample 2, sample 3, sample 4. Then each sample will have fractions 1 through 8. They can all be the same condition.
> 
> I believe the current release version of MM does not use the fraction number for MBR but the next release will only match fractions +-1. So fraction 4 will be matched to fractions 3, 4, and 5 of the other samples.

Thanks for the explanation. I will try it.
