### ISSUE TITLE
TMT experiment search (and MS2-level quantitation) 

### ISSUE THREAD

**Issue by MiguelCos** [smith-chem-wisc/MetaMorpheus#1935]
Hello all,

I am testing MetaMorpheus for peptide variants detection and I wanted to check on the current state of the support for TMT quantitation. We are very interested on implementing MetaMorpheus in our data analysis pipeline and we use TMT for most of our experiments.

I would be happy to collaborate with some spectral TMT data for your tests ( #1933) and offer my input as a user.

Best wishes,
Miguel

**Comment by rmillikin** [comment]
Hi Miguel,

The current status is that we identify the MS2 fragment belonging to each TMT tag in the MS2 spectrum, and we annotate the m/z along with intensity in the PSM file(s) for each fragment. These will be labeled as diagnostic ions ("D"). Right now we don't try to interpret that for quantitative purposes but you can extract this information from the PSM text file.

**Comment by acesnik** [comment]
Here's an example of this information from a 6-plex experiment in the AllPeptides.psmtsv file:
![image](https://user-images.githubusercontent.com/16342951/91476776-103c1200-e863-11ea-9c2f-5ede38faafe0.png)

**Comment by trishorts** [comment]
There is a known issue with TMT labeling that considers isotopic purity of labels. MetaMorpheus does not correct for labeling in the reported intesnities that acesnik reported above. I think those intensities would be good for first pass analysis. But, we need to do a better job to really do this right.

**Comment by MiguelCos** [comment]
Many thanks for all for the input. Now I see that I can actually do some comparisons based on my multiplexed data sets. Awesome!

@trishorts ; I see. So it might be interesting to implement something like a precursor ion fraction (PIF) measurement as the one that MaxQuant implements now? We have indeed noticed a more accurate quantitation with TMT when we are able to select features with better PIF.
