### ISSUE TITLE
Add a .toml Editor to MetaMorpheus GUI

### ISSUE THREAD

**Issue by trishorts** [smith-chem-wisc/MetaMorpheus#1938]
Some users, like Tim, that use the commandline version want an easy way to make .tomls. Right now he opens the gui, creates a search and kills the search only to get a toml. Maybe we can make a toml editor, that would allow someone to create and store one without doing any search.?

**Comment by rmillikin** [comment]
The new GUI will let you right click -> save as .toml. There's no longer a need to run the task just to get the .toml out. So this will be fixed in #1905

**Comment by trishorts** [comment]
thats great i wll tell tim.
