### ISSUE TITLE
Open .MGF files in metadraw

### ISSUE THREAD

**Issue by trishorts** [smith-chem-wisc/MetaMorpheus#1943]
seems like we can search mgf but not visualize the results in metadraw because .mgf is not an accepted file type.

**Comment by rmillikin** [comment]
is this a bug in the current release? and can you open .mgf in MetaDraw in the current master build?

**Comment by trishorts** [comment]
yes. i just confirmed that it is a bug in the release
i don't know about master yet.

**Comment by rmillikin** [comment]
fixed in #1959
