### ISSUE TITLE
GUI Update - details

### ISSUE THREAD

**Issue by trishorts** [smith-chem-wisc/MetaMorpheus#1958]
1.   I miss having checkboxes by databases. I like to be able to mark which ones i want to use in a search, and leave them around so  i can use them later in a different search.

2.   I'd like to be able to delete a task. 
3.  I'd like to be able to re-order tasks.

**Comment by rmillikin** [comment]
Let's use this issue to centralize to-do items for the new GUI.

- Double-click doesn't seem to open stuff for me anymore, need to fix that
- Need a right click -> Delete All option (equivalent to "Clear" in the old GUI)

**Comment by rmillikin** [comment]
- Need to reset the output folder (to empty) when all spectra files are deleted from the GUI

**Comment by rmillikin** [comment]
- Font size needs to be bigger

**Comment by rmillikin** [comment]
- Add a resizing splitter thing between the spectra/proteinDB and task areas in the "Run" tab
