### ISSUE TITLE
Cross linking Memory issue, urgent

### ISSUE THREAD

**Issue by DaliJarboui** [smith-chem-wisc/MetaMorpheus#1962]
Trying to use MetaMorpheus from XL data analysis using RAW files, Search is taking so long for 1 file (2 days and counting).
Metamorpheus latest version W7 64 GB RAM intel 10 cores.
is this normal that It takes so long ?

**Comment by lonelu** [comment]
Hi, Thanks for reporting the issue. 
It is not normal. What database are you using? If you are using a large database, you may want to try to set Total Partition: 50 or 100. If that doesn't work, please let us know and we could run your data and find the problem.

**Comment by DaliJarboui** [comment]
Thanks a lot, Yes I was using a full database, will try to do it as you suggested and report again. 
thanks again

**Comment by DaliJarboui** [comment]
Thanks for your advice, I followed your recommendation about using the partition, and it worked, but still using multiple RAW files resulted in the software bugging and not responding. using only one RAW file worked nicely. Maybe the database I'm using is big, will try again with a reduced database and see how it goes, for now analyzing the results from the single RAW file. 
Do you have a newly updated user guide for the new version as you have quite new features that are not included in the first user guide version. for example keeping the option Keep top N candidate empty (no number specified) resulted in the software crashing when trying to save the parameters without warning. will be helpful to have a user guide for the updated features in the XLsearch.
Thanks

**Comment by lonelu** [comment]
Thanks for the information. May I know what type of data you are searching? MS2 only or MS2-MS3? Are you using the Uniprot Human database? 
Thanks for the suggestions. I will update the user guide soon and let you know.

**Comment by DaliJarboui** [comment]
Hi, I'm using MS2 and MS3 data and uniprot human database (but I figured out I was using the Uniprot with all the canonical and isoforms) will try to use next the canonical entries only.
thanks for the help.

**Comment by lonelu** [comment]
Hi DaliJarboui, Thanks for letting me know the information. It will help to speed up if you remove the isoforms. Otherwise you can try to change 'Top Search Candidate' to a small number such as 20. 
I've updated the user manual here: https://github.com/smith-chem-wisc/MetaMorpheus/wiki/1_NewTask:-Crosslink-Search, and updated a pdf manual. Please let me know if there is anything confusing. 
Just let you know, MS3 data is generally in low-resolution. So far, MM is not well supported for low-resolution data. The best fragmentation type for DSSO would be HCD only, EThcD or HCD-ms2ETD etc.

**Comment by DaliJarboui** [comment]
Hi Lei, 
So the analysis of 1 file run smoothly, however when using 4 files Metamorpheus seems to take longer (4days) with high load on the RAM, when stopping the software all the tmp files are deleted and it doesn't it even generate results for the other files, experimental setup was designed in a way that each sample was treated as a different experiment. the data were acquired using  HCD for DSSO fragmentation. thanks for your help and advice.

Best

**Comment by lonelu** [comment]
Hi Dali, The information you reported suggested a potential RAM usage related bug. This is very very useful to us! I will try some search similar to yours to see if I can repeat the issue. It may take us a long time to solve the issue. 
Just let you know, MM currently combine the results into one from several files. Based on your description, you may want to search them separately.

**Comment by khal3dj** [comment]
In the interest of providing more details: I face the same issue when using XL search over multiple large files, but not when searching separately. 
The first two files or so are searched normally, but by the third file, RAM is used up completely (all 128 GBs), effectively freezing the program/search progress. This has been ultimately true regardless of number of partitions (1-250).
Sequence of tasks: 1. Calibration, 2. GPTMD search, 3. Search, 4. XL search
Starting XL search separately using files from steps 1 and 2 has the same result.
Thank you for all your work on this software.

**Comment by lonelu** [comment]
Hi, thanks for following up on this issue. Please let us know if you have other suggestions about the program.
According to you and several others, the XL search has a memory issue. I will put this as my priority. 
If you don't mind, please share a few (seems like 3 ) of your file with me (llu56@wisc.edu) to test. I understand the privacy of your project. 
I will let you know when this is fixed.
Lei

**Comment by khal3dj** [comment]
I'll prepare a task set to reproduce the issue and send it with the files. Thank you!

**Comment by lonelu** [comment]
Problem targeted and will be solved in near future.

**Comment by jsalbin** [comment]
> 
> 
> In the interest of providing more details: I face the same issue when using XL search over multiple large files, but not when searching separately.
> The first two files or so are searched normally, but by the third file, RAM is used up completely (all 128 GBs), effectively freezing the program/search progress. This has been ultimately true regardless of number of partitions (1-250).
> Sequence of tasks: 1. Calibration, 2. GPTMD search, 3. Search, 4. XL search
> Starting XL search separately using files from steps 1 and 2 has the same result.
> Thank you for all your work on this software.

I have been having a similar issue with RAM in XL searches (tasks are just Calibration and then XL search). It will gradually creep up to use all 64 GB and then freeze, though changing partitions to 50-100 will just barely get it to complete on four .raw files for me in <90 minutes. I tried increasing virtual memory, but it doesn't seem to be using the virtual memory when it is about to max out the physical memory. I am using a large database (yeast + human). It's nice that MetaMorpheus can handle it under certain settings, but it seems like there ought to be a way to limit physical memory use so that more files can be analyzed together without freezing.

**Comment by trishorts** [comment]
let me check with the main contributor

**Comment by lonelu** [comment]
Hi @jsalbin. Thanks for reporting the issue. We targeted the RAM usage problem and are very close to solving it together with some other optimizations. Please wait for a few days. I or @trishorts will inform you here when we got a new release.

**Comment by jsalbin** [comment]
Thank you!
