### ISSUE TITLE
possible issue with editing save folder

### ISSUE THREAD

**Issue by trishorts** [smith-chem-wisc/MetaMorpheus#1966]
Found a small bug in metamorpheous. When I try and select a filepath to save the results to on the run tab (from the below screenshot) the dialog window that pops up will not let me choose a new output folder 

![image](https://user-images.githubusercontent.com/16841846/95902835-f8f5ad00-0d5a-11eb-83aa-ee56cc102f41.png)

**Comment by trishorts** [comment]
this was mailed to me by coner

**Comment by rmillikin** [comment]
that button opens the folder that's currently in the "output folder" textbox, it's not a folder selection dialog. so this isn't really a bug, it's maybe more of an unclear button purpose. we could add a dialog selector button though.
