### ISSUE TITLE
Modifying modification names

### ISSUE THREAD

**Issue by MiguelCos** [smith-chem-wisc/MetaMorpheus#1973]
Hello,

I am trying to get a pepXML file from the MetaMorpheus output for its integration with other search engine outputs via iProphet. 

My first approach has been to transform the .mzID output from MetaMorpheus into pepXML using IDFileConverter in OpenMS. But I am facing an error that seems to be related to a mismatch between the names of the modifications as defined in MetaMorpheus and as defined in OpenMS (` ... constModification not found: Carbamidomethyl on C... `).

If I check the modification file in OpenMS I see that the modification's name would only be "Carbamidomethyl".

I then tried to modify the modifications file (`aListOfmods.txt` and `Mods.txt`  in `AppData/Local/MetaMorpheus/Mods/`) in MetaMorpheus and run a new search, but even after renaming everything from i.e.: `Carbamidomethyl on C` to `Carbamidomethyl`. The generated mzid file is continuing to record the modification as: `Carbamidomethyl on C`; `Carbamidomethyl on U` and so on... 

Am I missing something? What would you recommend to circumvent this? 

Many thanks in advance!

Best,
Miguel

**Comment by rmillikin** [comment]
MetaMorpheus appends " on X" where X is the amino acid, to the modification name. It has to do with avoiding naming ambiguity when multiple mods have the same name. 

I think the simplest case would be just to delete " on C". Like open the file in Notepad++ and find+replace " on C" with "" (empty). Does that work?

Is this just that OpenMS and MetaMorpheus call the same mod by different names?

**Comment by lonelu** [comment]
I am trying to output pepXML directly from MM. This may help in the future.

**Comment by MiguelCos** [comment]
@rmillikin Many thanks for your suggestion!

> I think the simplest case would be just to delete " on C". Like open the file in Notepad++ and find+replace " on C" with "" (empty). Does that work?

I took this workaround and actually worked. Opened the mzID file in Notepad++ and modified as you suggested. Then no error was prompted on IDFileconverter in OpenMS. 

Although I must say I am still intrigued why the names are kept written the same even after modifying the` aListOfmods.txt` and `Mods.txt` files in `AppData/Local/MetaMorpheus/Mods/`. 

I would need to maybe write an R script or something to automatize this mzID file correction in some way to fit it into my pipeline. 

> Is this just that OpenMS and MetaMorpheus call the same mod by different names?

This is indeed the case. I discussed this with the OpenMS developers and this is how OpenMS expects definition of the feature to look like:

```
        <SearchModification fixedMod="true" massDelta="57.021464000000002" residues="C">
            <cvParam accession="UNIMOD:4" cvRef="PSI-MS" name="Carbamidomethyl"/>
        </SearchModification>
```

and this is how it looks like in MetaMorpheus

```
<Peptide id="P_7">
  <PeptideSequence>ALANVNIGSLICNVGAGGPAPAAGAAPAGGPAPSTAAAPAEEK</PeptideSequence>
  <Modification location="12" residues="C" monoisotopicMassDelta="57.021463721">
    <cvParam name="Carbamidomethyl on C" cvRef="PSI-MS" accession="UNIMOD:4" />
  </Modification>
</Peptide>
<Peptide id="P_8">
``` 
Isn't it redundant to set the name as `"Carbamidomethyl on C"` while the `C` is defined in the residues element?

@lonelu : it would be awesome to actually have the option to get a pepXML output from MetaMorpheus.

**Comment by rmillikin** [comment]
Glad to know that worked and it's at least solvable. I do agree that the " on C" is redundant in this case because the residue is already a separate field in the XML tag. In other files, though, this information is not listed (e.g., protein database XMLs) and so it's important instead of redundant. And we want to keep the names of our mods consistent across outputs. 

I really don't want users to have to edit our .mzID output to get it to work in other programs, though. For some people it's as easy as writing an R script, but for others it's an annoying Find+Replace every time. Maybe we can make this an output option. I imagine we would probably remove the " on C" by default and rely on the XML tag but you could enable keeping the " on C" in the name if desired.

**Comment by rmillikin** [comment]
this option is implemented in #1984

**Comment by lonelu** [comment]
Hi Miguel, @MiguelCos 
Just let you know that MetaMorpheus can directly output .pepXML now. Please let us know if you want to try it. It works for TPP so far as we tried. We haven't merged it in the release yet considering we are not sure if it works for other programs. I put a debug version here if you are interested: https://drive.google.com/drive/folders/1qhM2SLXUY1vVFDiArBg5695-0kpYSy3O?usp=sharing

**Comment by MiguelCos** [comment]
Hello @lonelu ,

This is amazing! Yes, I would definitely take a look at this during the next few days. Thank you for being so responsive!

I have to report a test that I made recently.

After manually transformed the mzID into pepXML by manually modifying the mzID file, I inputted the pep.xml into peptideProphet in TPP and I got an error as "search-engine: MetaMorpheus not recognized". I tried to trick it again by changing the definition of the search engine in the pepXML to a TPP one (i.e. Comet) and the peptideProphet analysis didn't go through. 

I haven't tried to directly merge it with pepXMLs from other search engines with iProphet though. 

I will send the specific errors that I received in a couple of minutes.

**Comment by MiguelCos** [comment]
### peptideProphet log after running it on the newly created pep.xml (manual modification of mzID -> IDFileconverter(OpenMS)) on TPP-peptideProphet. 

```
running: "C:/TPP/bin/DatabaseParser "/tmp/a28048/Miguel/HQ_HeLa_MetaMorpheus/Task1-SearchTask/HQ_HeLa_MetaMorpheus_interact.pep.xml""
command completed in 1 sec 

running: "C:/TPP/bin/RefreshParser "/tmp/a28048/Miguel/HQ_HeLa_MetaMorpheus/Task1-SearchTask/HQ_HeLa_MetaMorpheus_interact.pep.xml" "D:\data\Miguel\Databases\EBI_Human_reference_1protein_1gene_RELEASE_2020_02_w_iRTs_plus_wSCRAMBLED_named2.fasta""

  - Searching the tree...
  - Linking duplicate entries...
  - Printing results...
    Warning: could not map 16815 entries

  - Building Commentz-Walter keyword tree...command completed in 6 sec 

running: "C:/TPP/bin/PeptideProphetParser "/tmp/a28048/Miguel/HQ_HeLa_MetaMorpheus/Task1-SearchTask/HQ_HeLa_MetaMorpheus_interact.pep.xml" MINPROB=0.0 PPM ACCMASS NONPARAM DECOY=DECOY"
using Accurate Mass Bins
using PPM mass difference
Using Decoy Label "DECOY".
Using non-parametric distributions
 (MetaMorpheus) (minprob 0)
error: engine MetaMorpheus not recognized

command "C:/TPP/bin/PeptideProphetParser "/tmp/a28048/Miguel/HQ_HeLa_MetaMorpheus/Task1-SearchTask/HQ_HeLa_MetaMorpheus_interact.pep.xml" MINPROB=0.0 PPM ACCMASS NONPARAM DECOY=DECOY" failed: Operation not permitted

command "C:/TPP/bin/PeptideProphetParser "/tmp/a28048/Miguel/HQ_HeLa_MetaMorpheus/Task1-SearchTask/HQ_HeLa_MetaMorpheus_interact.pep.xml" MINPROB=0.0 PPM ACCMASS NONPARAM DECOY=DECOY" exited with non-zero exit code: 1
QUIT - the job is incomplete
```

### peptideProphet log after running it on the newly created pep.xml and modify it by changing 'MetaMorpheus' to 'Comet' as a search engine. 

```
C:/TPP/bin/xinteract (TPP v5.2.0 Flammagenitus, Build 201903130949-7900 (Windows_NT-x86_64))
 PPM mode in Accurate Mass Model ...

running: "C:/TPP/bin/InteractParser "/tmp/a27168/Miguel/HQ_HeLa_MetaMorpheus/Task1-SearchTask/interact_2_cometMOCK.pep.xml" "HELA_200824151226.pep.xml" -L"7""
 file 1: HELA_200824151226.pep.xml
 processed altogether 79784 results
INFO: Results written to file: /tmp/a27168/Miguel/HQ_HeLa_MetaMorpheus/Task1-SearchTask/interact_2_cometMOCK.pep.xml
command completed in 9 sec 

running: "C:/TPP/bin/DatabaseParser "/tmp/a27168/Miguel/HQ_HeLa_MetaMorpheus/Task1-SearchTask/interact_2_cometMOCK.pep.xml""
command completed in 0 sec 

running: "C:/TPP/bin/RefreshParser "/tmp/a27168/Miguel/HQ_HeLa_MetaMorpheus/Task1-SearchTask/interact_2_cometMOCK.pep.xml" "D:\data\Miguel\Databases\EBI_Human_reference_1protein_1gene_RELEASE_2020_02_w_iRTs_plus_wSCRAMBLED_named2.fasta""

  - Searching the tree...
  - Linking duplicate entries...
  - Printing results...
    Warning: could not map 16815 entries

  - Building Commentz-Walter keyword tree...command completed in 6 sec 

running: "C:/TPP/bin/PeptideProphetParser "/tmp/a27168/Miguel/HQ_HeLa_MetaMorpheus/Task1-SearchTask/interact_2_cometMOCK.pep.xml" MINPROB=0.0 PPM ACCMASS NONPARAM DECOY=DECOY"
using Accurate Mass Bins
using PPM mass difference
Using Decoy Label "DECOY".
Using non-parametric distributions
 (Comet,) (minprob 0)
NULL distri, search engine=Comet,

command "C:/TPP/bin/PeptideProphetParser "/tmp/a27168/Miguel/HQ_HeLa_MetaMorpheus/Task1-SearchTask/interact_2_cometMOCK.pep.xml" MINPROB=0.0 PPM ACCMASS NONPARAM DECOY=DECOY" failed: Operation not permitted

command "C:/TPP/bin/PeptideProphetParser "/tmp/a27168/Miguel/HQ_HeLa_MetaMorpheus/Task1-SearchTask/interact_2_cometMOCK.pep.xml" MINPROB=0.0 PPM ACCMASS NONPARAM DECOY=DECOY" exited with non-zero exit code: 1
QUIT - the job is incomplete
```

I am not sure how useful this is for you but I will also report this to the TPP developers and definitively test your newly implemented pepXML output and its compatibility with TPP.

Best,
Miguel

**Comment by MiguelCos** [comment]
Hello @lonelu, I just tried the pep.XML output you sent on peptideProphet-TPP. I had to change your local paths for both the fasta and mzML file sin the pep.XML for it to run, but the analysis still ends up in error.

This is what I get (sorry for the huge log):
```
C:/TPP/bin/xinteract (TPP v5.2.0 Flammagenitus, Build 201903130949-7900 (Windows_NT-x86_64))
 PPM mode in Accurate Mass Model ...

running: "C:/TPP/bin/InteractParser "/tmp/a09100/MetaMorpheus_pepxml_output_implementation/2020-11-17-16-14-50/Task1-SearchTask/interact.pep.xml" "20190718_yeast_Bt.pep.XML" -L"7""
 file 1: 20190718_yeast_Bt.pep.XML
 processed altogether 24501 results
INFO: Results written to file: /tmp/a09100/MetaMorpheus_pepxml_output_implementation/2020-11-17-16-14-50/Task1-SearchTask/interact.pep.xml
command completed in 3 sec 

running: "C:/TPP/bin/DatabaseParser "/tmp/a09100/MetaMorpheus_pepxml_output_implementation/2020-11-17-16-14-50/Task1-SearchTask/interact.pep.xml""
command completed in 0 sec 

running: "C:/TPP/bin/RefreshParser "/tmp/a09100/MetaMorpheus_pepxml_output_implementation/2020-11-17-16-14-50/Task1-SearchTask/interact.pep.xml" "C:\TPP\data\MetaMorpheus_pepxml_output_implementation\yeast.fasta""

  - Searching the tree...
  - Linking duplicate entries...
  - Printing results...
    Warning: could not map 2418 entries

  - Building Commentz-Walter keyword tree...command completed in 3 sec 

running: "C:/TPP/bin/PeptideProphetParser "/tmp/a09100/MetaMorpheus_pepxml_output_implementation/2020-11-17-16-14-50/Task1-SearchTask/interact.pep.xml" MINPROB=0.0 MINPROB=0 PPM ACCMASS NONPARAM DECOY=DECOY_"
using Accurate Mass Bins
using PPM mass difference
Using Decoy Label "DECOY_".
Using non-parametric distributions
 (SEQUEST) (minprob 0)
adding ACCMASS mixture distribution
init with SEQUEST trypsin 
ERROR: Discriminant value computed as nan, for spectrum 20190718_yeast_Bt.32076.32076.2. This spectrum will be excluded from the model.
ERROR: Discriminant value computed as nan, for spectrum 20190718_yeast_Bt.24806.24806.3. This spectrum will be excluded from the model.
ERROR: Discriminant value computed as nan, for spectrum 20190718_yeast_Bt.33868.33868.3. This spectrum will be excluded from the model.
ERROR: Discriminant value computed as nan, for spectrum 20190718_yeast_Bt.42271.42271.2. This spectrum will be excluded from the model.
ERROR: ....

INFO: Processing standard MixtureModel ... 
 PeptideProphet  (TPP v5.2.0 Flammagenitus, Build 201903130949-7900 (Windows_NT-x86_64)) AKeller@ISB
 read in 50 1+, 10657 2+, 4880 3+, 744 4+, 89 5+, 2 6+, and 0 7+ spectra.
Initialising statistical models ...
Found 1785 Decoys, and 14637 Non-Decoys
Iterations: .
command "C:/TPP/bin/PeptideProphetParser "/tmp/a09100/MetaMorpheus_pepxml_output_implementation/2020-11-17-16-14-50/Task1-SearchTask/interact.pep.xml" MINPROB=0.0 MINPROB=0 PPM ACCMASS NONPARAM DECOY=DECOY_" failed: Unknown error

command "C:/TPP/bin/PeptideProphetParser "/tmp/a09100/MetaMorpheus_pepxml_output_implementation/2020-11-17-16-14-50/Task1-SearchTask/interact.pep.xml" MINPROB=0.0 MINPROB=0 PPM ACCMASS NONPARAM DECOY=DECOY_" exited with non-zero exit code: 255
QUIT - the job is incomplete
``` 

Any idea what might be causing this?

Many thanks for your efforts!

Best,
Miguel

**Comment by trishorts** [comment]
Might be that we don't use that decoy label for decoys.

**Comment by lonelu** [comment]
Thanks for the info. @MiguelCos . 
I may need to try TPP to figure out the bug, it seems like a complicated program. 
Do you mind share a 'correct' pepXML file with TPP with this data I used? which may help me a lot to figure out the program.
Thanks,
Lei

**Comment by lonelu** [comment]
I noticed a *.pep.xml.index file generated from TPP Tandam, which could be a missing thing.

**Comment by MiguelCos** [comment]
Hello @lonelu ,

I ran an X!Tandem search with the yeast mzML file+fasta you provided inside TPP and generated the files in the link. Notice that the fasta + decoys was created also with one of the TPP modules. `20190718_yeast_Bt.tandem.pep.xml` is the direct output from the search engine. `yeast_interact.pep.xml` is the output after probability calculation with peptideProphet ("Analyze peptides" module). `yeast_interact.ipro.pep.xml` is the output after using iProphet model on the first *interact* file. 

It would be nice to be possible to use 
I don't believe that the .index file would be the problem. peptideProphet and iProphet accept a pep.xml input as it might be generated directly from a search engine such as X!tandem, Comet or MSFragger without the need of any other input. I think the .index file is just generated as part of the GUI, to visualize and explore the pepXML result.

Many thanks for taking a look into this. Let me know if you need specific help or have any questions about TPP.

https://1drv.ms/u/s!ArJgSkDejwROmNY7Sa-R2Fn3-LQgUw?e=u5vLhz

**Comment by acesnik** [comment]
https://github.com/smith-chem-wisc/MetaMorpheus/pull/1984
