### ISSUE TITLE
MM_V0.0.312 Crashes when trying to visualize annotated MS2 spectra

### ISSUE THREAD

**Issue by kyleabrown20** [smith-chem-wisc/MetaMorpheus#1974]
When I try to visualize the annotated MS2 results from a search, the program crashes when I click on a peptide spectra.

**Comment by trishorts** [comment]
thanks kyle. i'll check this quick and see if i can reproduce the error.

**Comment by trishorts** [comment]
i'm not getting an error.  Can you tell us a little more about your search? Maybe we could run a search with one of your files?

![image](https://user-images.githubusercontent.com/16841846/98590166-09367480-2294-11eb-8e80-4a13693338c2.png)

**Comment by kyleabrown20** [comment]
Thanks for the help! Here is a screen shot of the error in case it helps.

[cid:6591fc0d-3ed2-4ab6-acab-1d8da7806a60]


-------------------------------------

Kyle A. Brown, PhD

Department of Surgery

University of Wisconsin-Madison


________________________________

**Comment by trishorts** [comment]
somehow your screenshot didn't come through

**Comment by rmillikin** [comment]
Just a note that this is resolved. It occurred because there was a period in the spectra file name. Fixed in #1976 .
