### ISSUE TITLE
Questions about dissociation type

### ISSUE THREAD

**Issue by grimace9527** [smith-chem-wisc/MetaMorpheus#1977]
Hi & Thanks for your reply:
    I am trying to analyze the data of [MSV000083070](https://massive.ucsd.edu/ProteoSAFe/dataset.jsp?task=87b447fbf68845c89ee8e558aa3f1acd) which was used in the article 'O-Pair Search with MetaMorpheus for
O-glycopeptide characterization'. Since not familiar with the type of EThcD,  I wonder which dissociation type to choose in the 'Dissociation Type' and 'Child Scan Dissociation' column, which locates in the GlycoSearchTaskWindow. Is the 'Child Scan Dissociation' means the dissociation of MS2 spectrums?
   Thanks again!

**Comment by lonelu** [comment]
Hi, Thanks for using MetaMorpheus.
The data is HCD trigger EThcD, which means the same precursor will be selected for HCD first and EThcD followed. Please use Dissociation Type: HCD, ChildScanDissociationType: EThcD.
We will make sure you can successfully run the program, please let me know if you have any other questions.
Lei

**Comment by grimace9527** [comment]
Thanks for the solution and the explanation! It works well. : )
