### ISSUE TITLE
Protein Inference Bug

### ISSUE THREAD

**Issue by rmmiller22** [smith-chem-wisc/MetaMorpheus#1979]
Identified that a single protein group is being identified 3 times in a single AllProteinGroups.tsv file. 
(Q4G0X9|Q4G0X9_2|G4G0X9_3 - single shared peptide VESKIEQEK - right above 1 % FDR cutoff). This occurred in recent and previous searches (months old)- and across multiple databases (GENCODE and UniProt produce the same error)

@rmillikin, @trishorts - I will look into this, but if you have any thoughts as to what could be going on let me know

**Comment by rmillikin** [comment]
can you post the file? I don't quite follow. It's 3 different protein groups all with the same set of accessions?

**Comment by rmmiller22** [comment]
![image](https://user-images.githubusercontent.com/30324061/99153886-3bb7e700-2671-11eb-8e97-d8a092d9d482.png)
Yes, three separate protein groups that are actually identical in terms of accessions, peptides, fdr etc

**Comment by rmmiller22** [comment]
I can post the protein group file, where would you want it

**Comment by rmillikin** [comment]
I'm guessing this is in https://github.com/smith-chem-wisc/MetaMorpheus/blob/master/EngineLayer/ProteinScoringAndFdr/ProteinScoringAndFdrEngine.cs ScoreProteinGroups method, it's supposed to merge indistinguishable protein groups which doesn't seem to be happening correctly here
