### ISSUE TITLE
Unable to read RAW file in Mac Terminal

### ISSUE THREAD

**Issue by stsour** [smith-chem-wisc/MetaMorpheus#1982]
I see in earlier posts  (#1967)  that raw file reading capability has been added to Linux. I will be trying this out, but in the meantime I am trying to run the command line package on my mac through terminal, and it crashes giving this error message:

> Welcome to MetaMorpheus
> 0.0.312
> Starting task: Task1SearchTask
> 	Finished writing file: /Users/shiri/Google Drive File Stream/My Drive/Mistranslation Project/Papers/Clark_ccRCC/Proteomics Data/S1/2020-11-15-21-31-06/Task Settings/Task1SearchTaskconfig.toml
> Run failed, Exception: Unable to access RAW file!
>

Any plans to have raw file reading work on a Mac?

**Comment by rmillikin** [comment]
thanks for the crash report - I will check w/ someone on our team that has a mac computer and get back to you. In theory this should work as-is but it's difficult to regularly test it since our testing takes place in Windows and Linux environments.

**Comment by stsour** [comment]
No problem. I'm all set for now, working in a Linux environment.

**Comment by rmillikin** [comment]
@kyp4 was able to reproduce this error w/ her Mac. We use Thermo's RawFileReader to read .raw files, and unfortunately it looks like this package only supports Windows and Linux ( https://planetorbitrap.com/rawfilereader ). I mistakenly thought it also supported MacOS. So, it looks like until Thermo supports Mac users, .raw files are only readable on Windows and Linux.
