### ISSUE TITLE
Diagnostic ions for glycopeptides

### ISSUE THREAD

**Issue by rmillikin** [smith-chem-wisc/MetaMorpheus#199]
Oxonium  ions  such  as  [HexNAc+H]+(204.1 Da),  [NeuAc+H]+ (292.1 Da), [LacNAc+H+] (366.1 Da) 
and [NeuAc-LacNAc+H+] (657.2 Da) usually can be used as reliable indicators of the presence of glycopeptides 

Nature Protocols  doi:10.1038

**Comment by stefanks** [comment]
Rob, have you seen these in practice?

**Comment by rmillikin** [comment]
Yes, if the fragmentation method is HCD; CID not really

**Comment by trishorts** [comment]
![image](https://cloud.githubusercontent.com/assets/16841846/24507543/53273946-1526-11e7-93b1-74a291157dde.png)

from: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4125726/

**Comment by trishorts** [comment]
![image](https://cloud.githubusercontent.com/assets/16841846/24507953/949ba23a-1527-11e7-9047-a8a214738830.png)

from: 
![image](https://cloud.githubusercontent.com/assets/16841846/24507975/ab669cc2-1527-11e7-8ca2-ff14900f4e71.png)

**Comment by trishorts** [comment]
We might want to link certain diagnostic ions with certain types of fragmentation to prevent false application (e.g. using one found in HCD for ETD validation of PTM).

**Comment by trishorts** [comment]
would be nice, when we see diagnostic ions and we use those to call a modification, that we list them in a column in the MM output. Don Hunt uses several diagnostic ions to call o-glcnac. We looked and we also see several. So, let's use all that we can. 204 186 168 144 138 126

**Comment by rmillikin** [comment]
see #1259
