### ISSUE TITLE
Bug with annotation in MetaDraw

### ISSUE THREAD

**Issue by Dmorgen** [smith-chem-wisc/MetaMorpheus#2006]
Hi Guys,

got weird annotation in Metadraw whereby the b and y ions are all marked on the same exact position, even when it shouldn't.
[48474_FMEDMMPK.pdf](https://github.com/smith-chem-wisc/MetaMorpheus/files/5816531/48474_FMEDMMPK.pdf)

Cheers,
David.

**Comment by trishorts** [comment]
David, 

Can you share the raw file and organism? I'd like to debug this and see what is going on.

**Comment by Dmorgen** [comment]
please see your email.

**Comment by trishorts** [comment]
I reproduced this bug. I'll try to figure out where the bug lies. 
![image](https://user-images.githubusercontent.com/16841846/105213452-58aae380-5b14-11eb-82a4-daf9242698bf.png)

**Comment by rmmiller22** [comment]
This issue has been fixed, and this fix has been incorporated into the latest release made today (0.0.313)
