### ISSUE TITLE
version 313 doesn't start up

### ISSUE THREAD

**Issue by Dmorgen** [smith-chem-wisc/MetaMorpheus#2012]
Hi,

I've updated the version and it doesn't start up. I've uninstalled, and reinstalled from the MSI - still no luck. what should I look for?

Cheers,
David.

**Comment by trishorts** [comment]
sorry. i have same problem. we'll get on it. please go back to 312 for the moment.

https://github.com/smith-chem-wisc/MetaMorpheus/releases/tag/0.0.312

**Comment by rmillikin** [comment]
quick update. the MM installer works on our automated testing suite but not on local machines, for some reason. I think we'll be able to make a working release later today, but we need to figure out what's going on. Stay tuned, apologies for the delay.

**Comment by Dmorgen** [comment]
:)

**Comment by rmmiller22** [comment]
This issue has been fixed and the new 0.0.313 can be successfully installed, opened and operated. Thank you for bringing this forward.
