### ISSUE TITLE
Internal fragment scoring

### ISSUE THREAD

**Issue by stefanks** [smith-chem-wisc/MetaMorpheus#202]
Peptides missing from both ends, unknown termini at both ends.

**Comment by stefanks** [comment]
Not even sure how to approach this

**Comment by stefanks** [comment]
In ms1 spectra, proteins are still intact, but in ms2, PEPTIDE  might break into P, PE, T, PT, EPT,  T, TI TID , DE, IDE...

**Comment by acesnik** [comment]
I misunderstood this issue. It sounds like we might be able to do this already; we just need to look to see if we identify them. Does it require a new approach?

**Comment by trishorts** [comment]
I was thinking that we could create a lookup at the start like we do anyway for b/y ions.

**Comment by lschaffer2** [comment]
Yeah, maybe just requires some looking into of how many theoretical internal fragments to add, I don't know if too many combinations/possibilities would create issues

**Comment by rmillikin** [comment]
reopen if you want. not interested in verifying this.
