### ISSUE TITLE
no quantification data for one sample

### ISSUE THREAD

**Issue by Dmorgen** [smith-chem-wisc/MetaMorpheus#2023]
Hi,

I've ran quantification of two samples (with the correct experimental setup), but I'm getting intensity data for only one sample. is there something I'm missing here?

D.

**Comment by trishorts** [comment]
we just pushed the fix for that yesterday. i hope we can get a new release very soon.

if it's not released today, i can get you an early version to install and correct the problem.

sorry for the inconvenience.

**Comment by Dmorgen** [comment]
That's awesome - a pre-solved problem :)
