### ISSUE TITLE
Determine if MM is identifying and scoring peptide fragments in multiple charge states

### ISSUE THREAD

**Issue by trishorts** [smith-chem-wisc/MetaMorpheus#2029]

**Comment by rmillikin** [comment]
https://github.com/smith-chem-wisc/MetaMorpheus/blob/c4b487bb6bfd5c243fe09541a8a26e49050b3339/EngineLayer/MetaMorpheusEngine.cs#L134

right now MM stops after finding one acceptable fragment, it doesn't look for alternative charge states of that fragment in the MS2
