### ISSUE TITLE
Make sure all tasks work on low RAM machines

### ISSUE THREAD

**Issue by stefanks** [smith-chem-wisc/MetaMorpheus#203]
MetaMorpheus should run on modern computers, without requiring an exorbitant amount of RAM. On the other hand, for computers with large amounts of RAM, MetaMorpheus should use that to its advantage.

Let's validate that the following tasks work on low RAM machines:

- [ ] Search
- [ ] Gptmd
- [ ] Calibration

**Comment by stefanks** [comment]
Any opinions on the minimum amount of RAM that MetaMorpheus should be able to run on? How many files should it be able to handle at once on these low RAM machines?

**Comment by stefanks** [comment]
Someone needs to test MetaMorpheus performance on our cluster

**Comment by trishorts** [comment]
we're (well, Lei really) on it.

**Comment by stefanks** [comment]
Mono should be installed on Phoenix. 
More info:
"Code is not meant to be run on the headnode. You should start an interactive job using the qsub -I` command if you want to run software from the command line, like mono. You should check out https://hpc.chem.wisc.edu for more info on using the cluster "

**Comment by rmillikin** [comment]
reopen if you want. not interested in verifying this.
