### ISSUE TITLE
`dotnet CMD.dll --help` should return exit code 0, rather than exit code of 1 (error)

### ISSUE THREAD

**Issue by acesnik** [smith-chem-wisc/MetaMorpheus#2046]
Tested in a linux environment:
```
dotnet CMD.dll --help
echo $? # return the exit code
```
This gives 1, indicating an error, rather than 0, indicating successful run, which is more typical for a help menu.

The help menu also gives the debugging-like version number:
![image](https://user-images.githubusercontent.com/16342951/111823372-2be13580-88e5-11eb-856b-be702568e654.png)

The minimal example of making TOMLs is working well, though! Giving an exit code of 0 and the proper version number.
![image](https://user-images.githubusercontent.com/16342951/111823447-43202300-88e5-11eb-8567-bdec7feed9d4.png)

**Comment by trishorts** [comment]
how do you know/test this? i'm trying to figure out how to test command line arguments.

**Comment by trishorts** [comment]
Ok. So I went old skool and added some print statements to console. I tested the old --help and the version with the proposed change. Old version returned error code 1 and new version returns 0. I'm don't really understand ErrorType.HelpRequestedError but the code seems to have the desired effect.

![image](https://user-images.githubusercontent.com/16841846/113863703-990f1a80-976f-11eb-9aac-c3c8514f7813.png)

**Comment by acesnik** [comment]
Thanks for taking a look. This is more typical behavior of a commandline program, and the help menu is often used to verify whether the program is functioning. Here's an example of `stringtie` having an exit code of 0 after getting the help menu:
![image](https://user-images.githubusercontent.com/16342951/113871785-8ae2ed80-97b3-11eb-96b5-e5fa9322e887.png)

**Comment by acesnik** [comment]
https://github.com/smith-chem-wisc/MetaMorpheus/pull/2048
