### ISSUE TITLE
Autoinstaller: disallow users from downloading next version if new .NET Core version not installed

### ISSUE THREAD

**Issue by acesnik** [smith-chem-wisc/MetaMorpheus#2051]
* Autoinstaller should predict whether there will be a change in the .NET Core version and prompt user to download the version
* The "Install Now" button should be disabled until the new .NET Core version is installed

**Comment by acesnik** [comment]
Should probably integrate this before https://github.com/smith-chem-wisc/MetaMorpheus/pull/2047 😅

**Comment by rmillikin** [comment]
Last time we had a .NET core upgrade I put it in the release notes, so we can do this without extra code

**Comment by rmillikin** [comment]
https://github.com/smith-chem-wisc/MetaMorpheus/releases/tag/0.0.305

**Comment by acesnik** [comment]
Okay, that's awesome. I did some rough work on this earlier (https://github.com/smith-chem-wisc/MetaMorpheus/pull/2052), but will abandon it.
