### ISSUE TITLE
MetaMorpheus toml definitions

### ISSUE THREAD

**Issue by bernt-matthias** [smith-chem-wisc/MetaMorpheus#2054]
Dear MetaMorpheus community, I'm currently evaluating this tool wrt. integration in Galaxy. The main question for me seems to be if there is a "formal" definition of the entries in the toml files. Ideally with some help text for each entry.

Maybe its possible to (semi)autogenerate a Galaxy tool from this...

**Comment by acesnik** [comment]
I think I mentioned this in the galaxy pull request, but the TOMLs can be generated with `metamorpheus -g`. I don't think there are formal definitions for these TOML files, and they can change by the version, so it might be worth testing to make sure the default parameters and parameter names haven't changed.

I think there's a possibility that MetaMorpheus could output comments for the generated TOMLs based on the tooltip information that's in the graphical user interface. Would that be helpful?

**Comment by acesnik** [comment]
After a quick glance, I'm not sure how MetaMorpheus would output comments programmatically, but it might be a good undergraduate project if @trishorts has anybody who might be looking to try their hands on a programming problem.

**Comment by bernt-matthias** [comment]
@acesnik thanks for the reply. Btw, the Galaxy proteomics community made some good progress with integrating metamorpheus: https://github.com/galaxyproteomics/tools-galaxyp/pull/587

**Comment by trishorts** [comment]
was thinking about adding definitions to the tomls themselves in the form of comments but that does not seem allowed:
https://github.com/toml-lang/toml/issues/218

**Comment by trishorts** [comment]
where could i locate a set of toml definitions that would satisfy "the public". Happy to locate it in some specific location on user request. Certainly can be in the wiki

**Comment by trishorts** [comment]
not definitions but examples:
https://github.com/smith-chem-wisc/MetaMorpheus/wiki/Example-TOML-Files-for-each-Task

**Comment by rmmiller22** [comment]
Definitions for each task parameter has been added to the Wiki and can be found here
https://github.com/smith-chem-wisc/MetaMorpheus/wiki/MetaMorpheus-Task-Parameters-Defined
