### ISSUE TITLE
Should we use separate scoring for each peptide length?

### ISSUE THREAD

**Issue by stefanks** [smith-chem-wisc/MetaMorpheus#207]

**Comment by zrolfs** [comment]
![screenshot 101](https://cloud.githubusercontent.com/assets/16883585/26326397/92e5c1fc-3f00-11e7-8c96-3418b9a295d5.png)

**Comment by acesnik** [comment]
Nice plots. There definitely are some trends. The 40-mers identified on average get ~25% coverage, and yet get the same score as a 10-mer with 100% coverage.

**Comment by trishorts** [comment]
Those are nice plots but they don't address the central premise, which is should we use separate scoring for each peptide length and not use uniform scoring of all observed peptides. If we were to use separate scoring, how would that work for modified psms that had a score bonus?

**Comment by zrolfs** [comment]
One way we could look at this is to look at peptides above a 1% FDR and "validate" them orthogonal from the score using the mass error and expected retention time. If we see more small peptides that have expected retention times and low precursor mass errors than large peptides, that would support that a modified scoring is necessary based on length. It's important to consider that smaller sequences are more likely to have homologous sequences present in the database, which might prevent us from rescoring small peptides. For example, theoretical K.PEPTIDE.S (7-mer) and K.SPETPIDE.S could have similar scores, but an internal cleavage happened to give the experimental PEPTIDE a better match to PETPIDE. The mass error and retention data between the two are identical, and the scan was assigned to an incorrect sequence. This is much less likely to occur for longer sequences (K.PEPTIDE.SEQUENCE vs K.PETPIDE.SCDEGA).

**Comment by rmillikin** [comment]
this issue seems not very relevant in the new PEP world
