### ISSUE TITLE
Bug on protein output

### ISSUE THREAD

**Issue by Dmorgen** [smith-chem-wisc/MetaMorpheus#2070]
Hi,

When opening the TSV files in excel, sometimes we get shifts in the tabs leading to deformation of the file structure: 
![image](https://user-images.githubusercontent.com/35773089/122029680-bf87ac80-cdd5-11eb-8ad5-8b75565cd946.png)

Thanks!
David.

**Comment by zrolfs** [comment]
Hi David,
Excel has a character limit for its cells. If we exceed that limit (say with a large protein or highly ambiguous identification), then Excel splits the cell with a new line and your screenshot is the result.
We recognize that many users view their results in Excel, so we made an option for MetaMorpheus to remove cells that are too big for excel and replace the cell with "Output too long for Excel". This option used to be in the task settings (i.e. you could select it in the GUI), but it looks like somebody decided to make it a global setting. It's kind of a pain, but you can make the result files compatible with Excel by changing this parameter in the global settings. I've attached the below figure to help you figure out how to do that.
![image](https://user-images.githubusercontent.com/16883585/122094362-18594400-cdda-11eb-88d3-f5cf71624128.png)

Hope that helps!
Zach

**Comment by Dmorgen** [comment]
Awesome, Thanks!

David.
