### ISSUE TITLE
MM 0.0.317 closes when selecting "download proteome"

### ISSUE THREAD

**Issue by MJanech** [smith-chem-wisc/MetaMorpheus#2071]
Hi. Just downloaded the recent update and wanted to try the  download from Uniprot option. I select "download proteome" and MM closes. Nothing further. No prompt. Mysterious. All other buttons function as they did in previous versions.

**Comment by rmillikin** [comment]
Thanks for your bug report @MJanech . I can reproduce this in the current release. I'll post again when we've got a fix in the works.

**Comment by rmillikin** [comment]
This appears to be a bug with the installed version of MetaMorpheus. The "Proteomes" folder and its contents are not properly installed to the MetaMorpheus data folder. This was fixed as part of #2047 and will be in the next release. I'll leave this issue open for now, until a new release is made.

**Comment by MJanech** [comment]
Thanks Robert. I noticed that MM prompted me to point to a "proteomes" folder. This is not an action I recalled in previous installs.  All sounds good.

Best,
Mike

**Comment by acesnik** [comment]
Working in 0.0.318
<img width="1133" alt="image" src="https://user-images.githubusercontent.com/16342951/127108398-ba6b1440-c9b1-46e1-8f93-8ae524aa4221.png">
