### ISSUE TITLE
make sure that "PSM Count (unambiguous, <0.01 q-value)" is updated after PEP disambiguation

### ISSUE THREAD

**Issue by rmillikin** [smith-chem-wisc/MetaMorpheus#2075]
I haven't pinpointed what the problem is yet but @kbhenke reports that there are some PrSMs that have a 0 for PSM count, are targets, are unambiguous, and have q-values <0.01 and notch qvalues <0.01. this is just a guess but they may have been ambiguous originally, and then shortreed's PEP algorithm removed some ambiguity and the PSM count wasn't updated accordingly. need to check. maybe same as #2055

**Comment by trishorts** [comment]
i don't recall but I think another problem is that the accessions assigned to psms/peptides is not changed after protein inference. is that true?

**Comment by kbhenke** [comment]
While this topic is being discussed, another (possibly related?) issue I’d like to report is that when I search multiple files together and then want to see how many PrSMs there were for a given prfm in a particular raw file, my instinct is to open the individual search results for that file and look at the number of PrSMs reported.  However, I'm pretty sure that when you search multiple files together, the same number of PrSMs is reported for all the raw files (I think this number is the TOTAL PrSMs observed in ALL raw files searched).  I don't find this number particularly helpful.  I've run into this issue a couple of times (both in BU and TD) and I think we/you all decided it was a bug, but I'm not sure that it was ever fixed.

**Comment by rmillikin** [comment]
this was actually a parsimony issue, sort of. parsimony removes some ambiguity, and the "PSM Count (unambiguous, <0.01 q-value)" field had to be updated post-parsimony.

@trishorts protein inference does/should change the accessions assigned to the PSMs/peptides. 

https://github.com/smith-chem-wisc/MetaMorpheus/blob/4944681aeab7c8ac100b474a2b080c5c9e228b20/EngineLayer/ProteinParsimony/ProteinParsimonyEngine.cs#L422

@kbhenke yeah this is an issue. I might be able to fix these both in one go. i'll check it out
