### ISSUE TITLE
User selected minimum peptide length

### ISSUE THREAD

**Issue by stefanks** [smith-chem-wisc/MetaMorpheus#208]

**Comment by trishorts** [comment]
someone who can should combine these issues

**Comment by acesnik** [comment]
Noted by @trishorts in https://github.com/smith-chem-wisc/MetaMorpheus/issues/307:
"Possibly allow short peptides will full coverage of b and y ions"

**Comment by lonelu** [comment]
I add new parameters 'int? minPeptideLength' and maxPeptideLength in the 'ProteinExtensions' - 'Digest' methods, and made the function work with Unit test. 
The method 'Digest' are used by Indexing Engine.cs and ClassicSearchEngine.cs, the engines are used  by SearchTask.cs and other 2 tasks. So I change all of those. (*Only I didn't change the calibrationEngine.cs. Not sure if needed)
I change so many things that made me scared. Is there a way like Unit test to test if the GUI works or not?Although all the Unit Test can pass.

**Comment by stefanks** [comment]
lonelu, currently we check if the GUI works by just compiling the GUI, running a few tasks, and seeing if the outputs correspond to the changes you made!

**Comment by stefanks** [comment]
Done in https://github.com/smith-chem-wisc/MetaMorpheus/pull/335

The note about "Possibly allow short peptides will full coverage of b and y ions" is moved to a new issue
