### ISSUE TITLE
Search crashes in GPTMD step

### ISSUE THREAD

**Issue by Dmorgen** [smith-chem-wisc/MetaMorpheus#2080]
Hi,

please see the attached output.

Thanks!
David.

[results.txt](https://github.com/smith-chem-wisc/MetaMorpheus/files/6768737/results.txt)

**Comment by trishorts** [comment]
can you share the files/database/toml? I'll try to reproduce the crash and fix it.

**Comment by Dmorgen** [comment]
Hi,

Please see the link for the data and the search files:
https://owncloud.incpm.weizmann.ac.il/index.php/s/1dVy7Frmo4JXDCQ

the database is Uniprot human XML.

D.
