### ISSUE TITLE
Question about the ion type used in EThcD dissociation type

### ISSUE THREAD

**Issue by grimace9527** [smith-chem-wisc/MetaMorpheus#2085]
Hello!
For the O-Pair mode, I was wondering which kinds of ion types were used generate the theoretical spectrum of EThcD dissociation type...For example the types of b, y, c, and z-ion? Thanks for your reply!

**Comment by trishorts** [comment]
don't totally understand your question. yes. we do use all four ion types you mention (z is zdot).

**Comment by trishorts** [comment]
I've asked the creator of this code to respond.

**Comment by lonelu** [comment]
Yes, we use all four ion types. Feel free to ask any questions.

**Comment by grimace9527** [comment]
> I've asked the creator of this code to respond.

Thanks! It helped a lot

**Comment by grimace9527** [comment]
> Yes, we use all four ion types. Feel free to ask any questions.

Thanks! got it
