### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by fazeliniah** [smith-chem-wisc/MetaMorpheus#2086]
Dear MM developer team, 
I am trying to use the Glycosearch for o-lined enriched sample obtained in our QE-HF. I keep getting the runtime error. Please see attached. The results file is also attached. 
Thanks again for all your effort to develop this useful tool.
![MM_error](https://user-images.githubusercontent.com/19155957/127515946-2b131113-b552-49bd-94bb-2a16b790e26b.PNG)
[results.txt](https://github.com/smith-chem-wisc/MetaMorpheus/files/6901502/results.txt)

**Comment by trishorts** [comment]
can you provide us with the raw files, databases and tomls that you used? I will trouble shoot the problem.

**Comment by lonelu** [comment]
Thanks for reporting this error. It seems like the program finished the searching but failed on write localization information. It will help us to use your raw file to target the error. @fazeliniah

**Comment by fazeliniah** [comment]
Please find the requested files here:
https://www.dropbox.com/sh/ke00gq6w7f74ztk/AACECDpJDIX_d5EUjVBKmr-ja?dl=0
Thanks

**Comment by lonelu** [comment]
No Crash in the new branch I am working.
