### ISSUE TITLE
Support for TMTpro/TMTpro-18plex

### ISSUE THREAD

**Issue by MKoesters** [smith-chem-wisc/MetaMorpheus#2089]
Hi all,

I'm planning to use MetaMorpheus to search a TMTpro 18 dataset.
For this, I was planning to add the modifications to the tmt.txt file.

While inspecting the file, I saw that e.g. TMT11 lists 12 diagnostic ions.
Is the 12th DI the full label?

Before I lookup all the DI, is it already possible to search TMTpro/TMTpro 18 with MetaMorpheus?

Best,
Manuel

**Comment by trishorts** [comment]
Hello Manuel,

It's been a while since I coded this. I don't recall if there are or were different versions available. I see we have three reporters for 117. Here are them all below from unit tests.

![image](https://user-images.githubusercontent.com/16841846/129956160-938eddb4-03dc-4bca-a597-51efa81318a6.png)

**Comment by trishorts** [comment]
If you come up w/ the formulas and so forth, maybe you could post them here. Then we can update MM so they are native in the next release.

**Comment by MKoesters** [comment]
I'll definitely post them here, once I got them and verified they are correct!
Regarding the masses above, afaik the TMT reporter masses range from 126 to 135, so I'm a bit confused what these masses actually are (see here http://www.unimod.org/modifications_view.php?editid1=2016)

**Comment by MKoesters** [comment]
These should be the right reporter ions masses and formulas for TMTpro and TMTpro 18

```
Label,Mass,Formula
126,126.12773,C(8)H(15)N(1)
127N,127.12476,C(8)H(15)15N(1)
127C,127.13108,13C(1)C(7)H(15)N(1)
128N,128.12812,13C(1)C(7)H(15)15N(1)
128C,128.13444,13C(2)C(6)H(15)N(1)
129N,129.13147,13C(2)C(6)H(15)15N(1)
129C,129.13779,13C(3)C(5)H(15)N(1)
130N,130.13483,13C(3)C(5)H(15)15N(1)
130C,130.14115,13C(4)C(4)H(15)N(1)
131N,131.13818,13C(4)C(4)H(15)15N(1)
131C,131.14450,13C(5)C(3)H(15)N(1)
132N,132.14154,13C(5)C(3)H(15)15N(1)
132C,132.14786,13C(6)C(2)H(15)N(1)
133N,133.14489,13C(6)C(2)H(15)15N(1)
133C,133.15121,13C(7)C(1)H(15)N(1)
134N,134.14825,13C(7)C(1)H(15)15N(1)
134C,134.15457,13C(8)H(15)N(1)
135N,135.15160,13C(8)H(15)15N(1)
```

I verified formulas have the right masses using this python script:

```
In [1]: import numpy as np

In [2]: from chemical_composition.chemical_composition_kb import PROTON

In [3]: from chemical_composition import ChemicalComposition

In [4]: with open("TMTpro_formulas.csv") as fin:
   ...:     next(fin) # skip header
   ...:     cc = ChemicalComposition()
   ...:     for line in fin:
   ...:         formula = line.split(',')[2]
   ...:         mass = float(line.split(',')[1])
   ...:         cc.use(formula=formula)
   ...:         theo_mass = cc.mass() + PROTON
   ...:         print(bool(np.isclose(mass, theo_mass)) is True)
   ...:
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
```
