### ISSUE TITLE
Gene name column missing in output when using CHO xml database 

### ISSUE THREAD

**Issue by bhampton-som** [smith-chem-wisc/MetaMorpheus#2090]
I use the feature in MM to download proteomes.  When looking at the "AllQuantifiedProteinGroups.tsv" file from a search that used a human XML database there is a "Gene" column which contains gene names for each row.  However, the search results when a CHO XML database is used does not contain a Gene column in its  .tsv file.  Both the Human and CHO XML sequence file contains code for the gene name e.g. 
<gene>
<name type="primary">GENE-NAME-HERE</name>
</gene>

I have not yet tried using a FASTA file in place of the XML file to compare the results.

In my use case, it is important to have the Gene column in the CHO output file for the purpose of ortholog mapping of these hamster genes to either mouse or human species.  Using the only currently useful data column "Protein Accession" produces much lower species to species mapping success compared to using the "Gene" name.  

Can MM be altered to output Gene names for any species being searched?

Thank you for your assistance.

**Comment by bhampton-som** [comment]
The XML code I typed originally is below:
`<gene>
<name type="primary">GENE-NAME-HERE</name>
</gene>`

**Comment by acesnik** [comment]
What does CHO mean?

Is this information in the `Gene Name` column? It should be two columns to the right of `Protein Accession`.

For example, for `Q92747` in human, the gene name column would is `primary:ARPC1A, synonym:SOP2L`. The column to the right of that is organism, too, so that might be useful if searching multiple species databases.

**Comment by bhampton-som** [comment]
Sorry, I should have been more specific about the species.  CHO is short for Chinese hamster ovary, which is a commonly used cell line.  The proteome ID is UP000001075.  And as I stated originally, there is not a Gene column in the ProteinGroups file when this hamster proteome XML database is used.  There is a Gene column when the human proteome XML database is used.  I'm using the same MM defaults for the searches, just changing the proteome database.

Please note that I'm not searching multiple species at once.  I'm only mentioning the search where I used a human database here as a troubleshooting method to demonstrate that MM does output the Gene column correctly when searching human data against the human XML database (as well as mouse vs mouse database).  However, MM does not output the Gene column when searching hamster data against the hamster XML database.

**Comment by bhampton-som** [comment]
I am very sorry.  I am incorrect.  The Gene column is present in the hamster search.  Please disregard previous comments.

**Comment by acesnik** [comment]
Oh, okay! I'm glad you were able to find the information you need.

Cheers,

AC
