### ISSUE TITLE
XL search "Max threads" cannot be set from GUI

### ISSUE THREAD

**Issue by khal3dj** [smith-chem-wisc/MetaMorpheus#2099]
Hi,

When choosing a non-default number of max threads for XL search tasks, then saving task settings, the number is always reset to the default (max - 1). If I adjust the number in the .toml file, it is read correctly. However, it is reset to default again whenever task settings are saved again.

**Comment by lonelu** [comment]
Hi kh,
Thank you for pointing this GUI bug. It will be fixed in the next release. 
Lei

**Comment by lonelu** [comment]
'''
Remeber to add the following in XLSearchTaskWindow.xaml.cs':
line 321 
var _maxThreadsToUsePerFile = int.Parse(maxThreadsTextBox.Text, CultureInfo.InvariantCulture); 
line 336
maxThreadsToUsePerFile: _maxThreadsToUsePerFile,
'''
