### ISSUE TITLE
Question: How to filter the results by peptide FDR?

### ISSUE THREAD

**Issue by grimace9527** [smith-chem-wisc/MetaMorpheus#2101]
Hi and thanks ahead for reply:
    I wonder if I can filter the results by peptide-level FDR, since there is only a 'Qvalue' column in the result 'oglyco.psmtsv' and 'single.psmtsv'. And I can't find the relative explanations (for peptide FDR) in the wiki... Thanks again for response!

**Comment by trishorts** [comment]
Not sure what you want. FDR is a group parameter (not for individual assignments). i think you may want the q-value, which is simply the FDR of all peptides beginning with the highest scoring peptide to the peptide in question. Every peptide with q-value < 0.01 has 1% chance of being incorrect (1% FDR). Let us know if you have more questions.

**Comment by grimace9527** [comment]
Thanks for your explanation!
What I want to express is the individual peptide q-values. So is there any information about the q-values of peptide identifications given in the result? Or how should I do to keep the peptide-level FDR of the result lower than 1%?

**Comment by grimace9527** [comment]
It looks like the 'Qvalue' column in the 'oglyco.psmtsv' represents the q-values of PSMs, so I wonder if there are any information about the q-values of peptide identifications?

**Comment by lonelu** [comment]
Hi,  the FDR is only controlled in PSM level in the current release version. The way the peptide FDR is calculated under development is to obtain the best score PSM for each peptide and order all peptides from high to low to obtain peptide FDR. 
 
Thanks for asking and this is an important feature to include. Please let us know if you have any suggestions.

**Comment by grimace9527** [comment]
Thanks for all these answers. Looking forward to seeing the new features and thanks again!

**Comment by trishorts** [comment]
check boxes added in next release
