### ISSUE TITLE
Confusing help box for setting precursor mass tolerance 

### ISSUE THREAD

**Issue by acesnik** [smith-chem-wisc/MetaMorpheus#211]
Right now the suggestion for entering a precursor mass tolerance is:
> Examples:
> name dot 5 ppm 0,1.003,2.006
> name interval [-4;-3],[-0.5;0.5],[101;102]

This is a bit confusing on first attempt; I had to ask for help.

Here are a few suggestions --

1. Change "dot" to "tolerance"
2. Make a "Format:" section above or below the examples that specifies that each field should have a space between them, and what each of the fields for the two types of commands represent. Maybe briefly mention how the comma-separated lists are handled.

**Comment by stefanks** [comment]
Some additional problems: commas between numbers are bad, because sometimes they are used within numbers, e.g. 1,000 for a thousand. Need a better system that is as flexible as the current one, simply documenting it is not sufficient.

**Comment by stefanks** [comment]
Is this current tooltip clear? 


A custom mass difference acceptor may be specified in multiple ways:
* To accept a custom (other than the interval corresponding to the precursor tolerance) interval around zero daltons, specify a custom name, followed by "ppmAroundZero" or "daltonsAroundZero", followed by the numeric value corresponding to the interval width. Examples:
   * CustomPpmInterval ppmAroundZero 5
   * CustomDaltonInterval daltonsAroundZero 2.1 

* To accept a variety of pre-specified mass differences, use a custom name, followed by "dot", followed by a custom bin width, followed by comma separated acceptable mass differences. Examples:
   * CustomMissedIsotopePeaks dot 5 ppm 0,1.0029,2.0052
   * CustomOxidationAllowed dot 0.1 da 0,16

* To accept mass differences in pre-specified dalton intervals, use a custom name, followed by &quot;interval&quot;, followed by comma separated mass intervals in brackets. Example:
   * CustomPositiveIntervalAcceptror interval [0,200]
