### ISSUE TITLE
Problem viewing "parent" and "child" spectra from O-Glyco search

### ISSUE THREAD

**Issue by comtewal** [smith-chem-wisc/MetaMorpheus#2110]
**Describing the issue**

Both parent (HCD) and child (ETD) spectra show side by side rather than top and bottom as in your wiki.  For long peptides the sequences are superimposed on the screen.

**Reproducing the error**

> - Which protein database did you use? 

SwissProt reviewed human downloaded on 11/30/2021

> - What type of mass spectrometry data files did you use? 

Thermo .raw files from Fusion Lumos (alternating HCD-ETD acquisition- not triggered from m/z=204)

> - Did you use any special settings, or just the defaults? Please provide the `.toml` methods file(s) generated by the GUI or used to run the commandline version.

[AutoGeneratedManuscriptProse.txt](https://github.com/smith-chem-wisc/MetaMorpheus/files/7728696/AutoGeneratedManuscriptProse.txt)

*** when dragging the .toml files I get a message saying the format is not supported (???)

> - If possible, please provide examples of the datafiles that reproduce the error. We can provide a folder that you can use to upload the data. Please let us know if the data needs to remain private.

**Desktop information**

> Please provide the autogenerated `prose.txt` file (can drag-and-drop it into this window) 

[121621_OPair_Superimposing_Spectra.pptx](https://github.com/smith-chem-wisc/MetaMorpheus/files/7728644/121621_OPair_Superimposing_Spectra.pptx)

**Comment by acesnik** [comment]
Thanks for the note about the issue. Tagging @lonelu  here to check on the issue: 

> Both parent (HCD) and child (ETD) spectra show side by side rather than top and bottom as in your wiki. For long peptides the sequences are superimposed on the screen.

Also, thanks for the note about the `.toml` file drag-and-drop. Will look into that.

**Comment by acesnik** [comment]
Have you tried changing the `.toml` file ending to `.toml.txt`? I wonder if it's just the file ending it doesn't like, since it's just a flat file.

**Comment by lonelu** [comment]
I think the viewing is related with some change of code in the visualization function. I will need to check that. 
About the toml file, it may related with the update. You probably generated it from an old version MetaMorpheus, please try to generate it using the new version to see if it still happens.

**Comment by lonelu** [comment]
Figure out the view of the paired scans, but the program might be changed due to some other reason. 
At Line 175 of MetalDraw.xaml, the current code is: "{Binding Path=MyColumnCount}"
If change it to Columns = '1', the paired scans will be vertically aligned. I don't know the reason behind the change.   @rmillikin may know, do we want to change it back to "1"?

**Comment by trishorts** [comment]
that line of code has been that way for a while. rob updated metadraw 13 months ago but didn't change that particular line. that must have been done in a previous metadraw update.

**Comment by trishorts** [comment]
that code was added in release 298 
https://github.com/smith-chem-wisc/MetaMorpheus/tree/0.0.298
I don't see it ever being columns = 1. can you point that out.

**Comment by lonelu** [comment]
Oh, you are right!  ​I just tried v0.0.307, I can still get the vertically aligned psm annotations. 
It must be something else then (could be related to the update of library Oxyplot we used).
So I guess the easiest way is to change line 175 to Columns = '1'.

**Comment by trishorts** [comment]
go ahead and make that little PR. I'm sure that AC and I will approve immediately and we can toss it to rachel.

**Comment by trishorts** [comment]
I just made the change and created a PR. I don't have the files to check if this solution worked. @lonelu can you see if this fixes the problem?
https://github.com/smith-chem-wisc/MetaMorpheus/pull/2112

**Comment by lonelu** [comment]
> I just made the change and created a PR. I don't have the files to check if this solution worked. @lonelu can you see if this fixes the problem? #2112

It fixed the problem.

**Comment by trishorts** [comment]
Thanks for checking. Merry Christmas

**Comment by rmmiller22** [comment]
Code addressing this issue has been merged into the Master, and will be in the next release of MM
