### ISSUE TITLE
Problem using viewer for N-glyco searches

### ISSUE THREAD

**Issue by ValentinaRangelAngarita** [smith-chem-wisc/MetaMorpheus#2118]
Upon selecting the spectra and PSM files (nglyco.psmtsv), nothing loads in the viewer. When selecting that exact sample spectra and using the PSM file for my o-glyco search, it works perfectly fine. Any hint of what I might be doing wrong? 
Thanks!

**Comment by lonelu** [comment]
Hi V,
Thank you for reporting the issue. This seems like a bug happened when loading the nglyco.psmtsv.
Let me check this with my own data first before I get back to you.
Lei

**Comment by nbollis** [comment]
This issue has been resolved with the most recent release of MetaMorpheus 1.0.0
