### ISSUE TITLE
O-Pair crashes specifically on one file

### ISSUE THREAD

**Issue by Dmorgen** [smith-chem-wisc/MetaMorpheus#2126]
**Describing the issue**
Getting an exception specifically on one data file. the rest are OK. the file is not corrupt and opens well in Xcalibur.

**Reproducing the error**
the raw file can be downloaded here:
https://owncloud.incpm.weizmann.ac.il/index.php/s/hqnXmFoeUQMll7Z

Used Human XML, with glyco search.
please see attached log

[results.txt](https://github.com/smith-chem-wisc/MetaMorpheus/files/8191015/results.txt)

thanks!
David.

**Comment by lonelu** [comment]
Thanks for reporting the issue! 
The issue is werid and fixing it may take some time. We will check this and get back to you.
