### ISSUE TITLE
Link invalid in the Test Installation 

### ISSUE THREAD

**Issue by yzhou08** [smith-chem-wisc/MetaMorpheus#2131]
**Describing the issue**
 
The link [https://uwmadison.box.com/v/MetaMorpheusPublic](https://uwmadison.box.com/s/2u42qp0b8jllywqzeungmjj04gplw5in) in the tutorial of Test Installation can not be opened.

**Reproducing the error**

- Protein database

- Mass spectrometry file types

- Settings

- Example datafiles

**Expected behavior for GUI**

**Screenshots**

![screen1](https://user-images.githubusercontent.com/65656680/159734478-84f94bc9-1e4c-4307-b687-2b36bcbf88c4.png)

**Desktop information**

[prose.txt](https://github.com/smith-chem-wisc/MetaMorpheus/files/8334308/prose.txt)

**Additional context**

I am installing MetaMorpheus in my virtual Machine. Because of the invalid link I used my own test data and database, but the input of parameter _-t_ can not be found. 

![screen2](https://user-images.githubusercontent.com/65656680/159734448-67c24b9b-e319-423b-8306-ac21a42981dd.png)

**Comment by acesnik** [comment]
Thanks for reporting this. I don't have a copy of these files. @trishorts @rmillikin @rmmiller22, do you have a copy of it to restore/change this link?

**Comment by trishorts** [comment]
try this: https://uwmadison.box.com/s/woh246eq30vtckxsfbae5pw0ltoznlca

**Comment by acesnik** [comment]
That link works for me. Thanks @trishorts!

**Comment by acesnik** [comment]
> I am installing MetaMorpheus in my virtual Machine. Because of the invalid link I used my own test data and database, but the input of parameter -t can not be found.

@yzhou08 Regarding this issue, it looks like your syntax is valid, but the toml file isn't in your current directory, since the error notes the file doesn't exist. Is it located in a subdirectory? Please check that the path pointing to each toml file is valid.

**Comment by acesnik** [comment]
Closing this issue for now; please use the link Michael shared above and double check the location of the file.

Let us know if there is anything more we can help with!

**Comment by yzhou08** [comment]
Thanks for the response :) The link works for me as well and I have found an example .toml files in another issue and some more in the new link. So I can change them regarding to my situation.
