### ISSUE TITLE
Software not working due to memory overflow in O-glyco search task

### ISSUE THREAD

**Issue by grimace9527** [smith-chem-wisc/MetaMorpheus#2158]
Thanks for your reply!

**Describing the issue**
Hi! When I try to run a O-glyco search task using MetaMorpheus, the software fails to run because there is insufficient computer memory. Since our computer has 32GB of memory, I don't know if there is a problem with the settings. All parameters are the same as default except some new modifications have been added.

**Reproducing the error**

The window of software shows "No Responding".

- Protein database

Human database download from Uniprot.

- Mass spectrometry file types

HCD data in RAW format.

- Settings

TaskType = "GlycoSearch"

[_glycoSearchParameters]
OGlycanDatabasefile = "OGlycan.gdb"
NGlycanDatabasefile = "NGlycan182.gdb"
GlycoSearchType = "OGlycanSearch"
OxoniumIonFilt = true
DecoyType = "Reverse"
GlycoSearchTopNum = 50
MaximumOGlycanAllowed = 2

[CommonParameters]
TaskDescriptor = "GlycoSearchTask"
MaxThreadsToUsePerFile = 32
ListOfModsFixed = "Common Fixed\tCarbamidomethyl on C"
ListOfModsVariable = "Common Variable\tOxidation on M\t\tCommon Artifact\tDeamidation on N\t\tCommon Artifact\tDeamidation on Q"
DoPrecursorDeconvolution = true
UseProvidedPrecursorInfo = true
DeconvolutionIntensityRatio = 3.0
DeconvolutionMaxAssumedChargeState = 12
DeconvolutionMassTolerance = "±4.0000 PPM"
TotalPartitions = 1
ProductMassTolerance = "±20.0000 PPM"
PrecursorMassTolerance = "±10.0000 PPM"
AddCompIons = false
ScoreCutoff = 3.0
ReportAllAmbiguity = true
NumberOfPeaksToKeepPerWindow = 1000
MinimumAllowedIntensityRatioToBasePeak = 0.01
NormalizePeaksAccrossAllWindows = false
TrimMs1Peaks = false
TrimMsMsPeaks = false
UseDeltaScore = false
QValueOutputFilter = 1.0
CustomIons = []
AssumeOrphanPeaksAreZ1Fragments = true
MaxHeterozygousVariants = 4
MinVariantDepth = 1
DissociationType = "HCD"
SeparationType = "HPLC"
MS2ChildScanDissociationType = "HCD"
MS3ChildScanDissociationType = "Unknown"

[CommonParameters.DigestionParams]
MaxMissedCleavages = 2
InitiatorMethionineBehavior = "Cleave"
MinPeptideLength = 6
MaxPeptideLength = 46
MaxModificationIsoforms = 1024
MaxModsForPeptide = 3
Protease = "trypsin"
SearchModeType = "Full"
FragmentationTerminus = "Both"
SpecificProtease = "trypsin"
GeneratehUnlabeledProteinsForSilac = true
KeepNGlycopeptide = false
KeepOGlycopeptide = false

[[FileSpecificParameters]]

- Example datafiles

**Expected behavior for GUI**

**Screenshots**

**Desktop information**

 - OS: Windows 10
 - MetaMorpheus Version: 0.0.320
 - Available RAM: 32 GB

**Additional context**

**Comment by trishorts** [comment]
thanks for reporting this error. Typically when there is a crash, a crash report is created. Can you look for a file called "Results.txt" in the output directory of the search and post the contents here?

**Comment by grimace9527** [comment]
Thanks for your reply. I tried it again and the software still shows "Not responding" like this:
![image](https://user-images.githubusercontent.com/56531544/177657039-25ab6b08-9b80-419f-92d7-6588aae45797.png)

The window stays like this for hours. .mzML data files are converted using MSConvert. There are about 30,000 spectra in the file.

And in the output directory of the search, there are only two folders named "Task Settings" and "Task1-GlycoSearchTask". The "Task Settings" contains a .toml file when the other folder is empty...Sorry I don't find the "Results.txt" file there.

**Comment by trishorts** [comment]
ok. thanks for looking. i don't think its the raw files. I think its the database. please increase the number of database partitions.

if you are using the default, try 4. 

how many raw files? have you tried only 1 as a test?

![image](https://user-images.githubusercontent.com/16841846/177661344-c0c94929-f2e2-4d3b-8453-a04e552a8c09.png)

**Comment by grimace9527** [comment]
Thanks!I've changed the number of database partitions to 4 and it's working fine (so far). I will keep watching the task and if there are new error messages I will sent you in time. Thanks again for your response.
By the way, does this option mean that the software will split the database into 4 parts and search them one by one?
For the number of RAW files, yes I have tried only 1 file as a test.

**Comment by trishorts** [comment]
please let me know if your search finished successfully

**Comment by grimace9527** [comment]
Thanks. It finished successfully after the number of database partitions was changed. : )
