### ISSUE TITLE
Problem visualizing nglyco

### ISSUE THREAD

**Issue by ht-lau** [smith-chem-wisc/MetaMorpheus#2198]
Hi MetaMorpheus team,

I ran into the same issue with thread #2118 that MetaDraw is not loading the nglyco.psmtsv. 

I am using version 0.0.320.

I have also try renaming the column “Scan Retention Time”, removing the columns from “Location Score” to the last column. This will allow Metadraw to read the file, but MetaMorpheus will crash when I click the peptide spectrum match.

MetaDraw will not read the file if I only change “Scan Retention Time” to “Retention Time”. Is there a way to visualize nglyco?

Thanks
HT

**Comment by trishorts** [comment]
thanks for the notification. we have a new release out in the next couple weeks. ihope that this will be addressed. can you provide a raw file, toml and database so that we can reproduce the error?

**Comment by ht-lau** [comment]
I can. Where can I upload to?

**Comment by nbollis** [comment]
Any cloud based data storage such as a google drive, dropbox, or onedrive. So long as we are able to access the data, anything will work

**Comment by nbollis** [comment]
This issue has been resolved with the most recent release of MetaMorpheus 1.0.0
