### ISSUE TITLE
Link does not work for Vignette: Bottom up mouse

### ISSUE THREAD

**Issue by naviyas** [smith-chem-wisc/MetaMorpheus#2211]
I'm trying to download the data required to do the Vignette: Bottom up mouse, however the link to download the vignette files leads me to a box page and no files. Can you please fix the link? Thank you!

**Comment by trishorts** [comment]
sorry for the slow response. just back from the holidays.

please try the following link: 
https://uwmadison.box.com/s/woh246eq30vtckxsfbae5pw0ltoznlca

**Comment by trishorts** [comment]
fixed
