### ISSUE TITLE
Write Spectral Library not working

### ISSUE THREAD

**Issue by ChrisMcGann** [smith-chem-wisc/MetaMorpheus#2215]
**Describing the issue**

Selecting "Write SpectralLibrary" in the search task doesn't output a spectral library. Search works perfectly fine with the exception of that.

- Protein database

Uniprot human fasta  + MetaMorpheus contaminants.  Fixed carbamidomethyl on C, variable M(ox).

- Mass spectrometry file types

Thermo Orbitrap Eclipse .raw ,  ITMS2 + FAIMS.

- Settings

.toml attached

[Task1-SearchTaskconfig.toml.txt](https://github.com/smith-chem-wisc/MetaMorpheus/files/10421540/Task1-SearchTaskconfig.toml.txt)

**Comment by trishorts** [comment]
fixed in the next release
