### ISSUE TITLE
Server installment only works when running as administrator

### ISSUE THREAD

**Issue by ahi-ed** [smith-chem-wisc/MetaMorpheus#2227]
**Describing the issue**
 The program does not start up or produce an error message opening prompt. 

**Reproducing the error**
 Possibly the program wants to excess files that need administrator credentials for file writing. 

- Protein database
 not relevant

- Mass spectrometry file types
not relevant

- Settings

- Example datafiles
not relevant

**Expected behavior for GUI**
 I expected the GUI to open for general use.

**Screenshots**

**Desktop information**
 
![image](https://user-images.githubusercontent.com/99261669/214880238-35e68ae7-af55-480f-bd26-240c3c3028a6.png)

**Additional context**

**Comment by trishorts** [comment]
is this windows 10? did you install the program using the .msi?  https://github.com/smith-chem-wisc/MetaMorpheus/releases/download/0.0.320/MetaMorpheusInstaller.msi

please check that you have the two following softwares installed:
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-5.0.4-windows-x64-installer
https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-desktop-6.0.4-windows-x64-installer

**Comment by ahi-ed** [comment]
Installment was completed on a Windows Server 2012 R2 Server. The correct software versions of dotnet were installed.

We have a multi user system and after installation, it works for the person that installed it. I was mistaken it had something to do with administrator rights. The cause of the problem is that Metamorpheus expects the folder AppData\Local\MetaMorpheus (plus contents) to be present in the user's home directory, and doesn't run if it's missing. At install time, this folder is created for the user that installs the software. We could fix the problem by manually copying the folder to the users home directory on the server. Would it be possible to allow for multi use installment and redirect AppData\Local\MetaMorpheus?
