### ISSUE TITLE
Allow specifying number of ions to look for in a search

### ISSUE THREAD

**Issue by stefanks** [smith-chem-wisc/MetaMorpheus#23]

**Comment by trishorts** [comment]
I don't know what this means. If this means specifying peptide length, then it can be closed

**Comment by stefanks** [comment]
No, this is something that I believe Zach needed at some point. For example, limit the search to at most 5 y ions, etc. 
Zach, do you still need this?

**Comment by zrolfs** [comment]
Nah, I wrote a chunk of code that I just add to every MM version to achieve this. When optimized it increases fusion peptide identifications by a couple percent. It doesn't have any application to traditional searches and can be closed.
