### ISSUE TITLE
GPTMD-generated contaminant database should be automatically have "contaminant" checkbox checked

### ISSUE THREAD

**Issue by rmillikin** [smith-chem-wisc/MetaMorpheus#239]

**Comment by acesnik** [comment]
Also, consider automatically checking the contaminant box for databases with "cRAP" or "contaminant" in the filename.

**Comment by stefanks** [comment]
Done in https://github.com/smith-chem-wisc/MetaMorpheus/commit/b8a394da94312ab54f5bd3afd8e7d8a17319b686
