### ISSUE TITLE
GPTMD task panel: List of database reference types to read in and write out

### ISSUE THREAD

**Issue by acesnik** [smith-chem-wisc/MetaMorpheus#241]
Example: "GO","Ensembl" in a text box would read in as a string array to the ProteinDbReader in the most recent mzLib (v117), so proteins would be read and written with GO and Ensembl dbRef elements.

**Comment by stefanks** [comment]
Resolved in https://github.com/smith-chem-wisc/MetaMorpheus/commit/a25e89f7d8419c2e32e4c66e433c5ffcd824d994
