### ISSUE TITLE
What does amino acid and amino acid2 mean in the custom crosslinker box?

### ISSUE THREAD

**Issue by bluemooninvestor** [smith-chem-wisc/MetaMorpheus#2411]
I am trying to set up a new thiol binding crosslinker? I have added the final mass (ie after it binds to the thiols).

What does amino acid and amino acid2 mean in the custom crosslinker box? I have added "C,U" in both boxes, since it should bind to cysteine and selenocysteine. Is that correct way to do it?

Further, if I have a crosslinker of mass 50, which binds to two thiols and itself loses two hydrogen, should the final mass be 48, or should it be 46 considering that the two target Cys-SH also lose two H.

Kindly let me know.

Thanks

**Comment by nbollis** [comment]
46 would be the correct mass here as it is the final mass of the crosslinker. C in aa1 and U in aa2. If there’s any other combos to worry about like CC or UU, you would have to enter those separately and run a second crosslink search with that as the crosslinker

**Comment by bluemooninvestor** [comment]
Thanks @nbollis ! However the software is still not running for me. I have opened as seperate thread for the issue.
