### ISSUE TITLE
What does a PEP and PEP Q-value of NaN indicate?

### ISSUE THREAD

**Issue by bluemooninvestor** [smith-chem-wisc/MetaMorpheus#2415]
I am trying to analyze XL-MS data analysis. I have got some interlinks and intralinks at FDR 1%. However, the last 2 columns,  PEP and PEP Q-value, read NaN. What does this mean? The Q-value is 0. Sorry, I couldn't find any explainations in the paper.

**Comment by nbollis** [comment]
A PEP value of NAN indicates that there were not enough peptides to perform Posterior Error Probability. You are currently required to have at least 100 peptides at Q-value<= 0.01
