### ISSUE TITLE
MetaDraw crashed while attempting to open the Chimeric Scan View.

### ISSUE THREAD

**Issue by mzhastings** [smith-chem-wisc/MetaMorpheus#2418]
**Describing the issue**

MetaDraw crashed while attempting to open the Chimeric Scan View. 

**Reproducing the error**

The scan being viewed was an ambiguous ID

- Protein database

n/a

- Mass spectrometry file types

.MZML

- Settings

defaults

- Example datafiles

Full sequence of peptide:
HGLDNY[Custom:NPA_Desthiobiotin   on Y]RGYSLGNWVC[Common Fixed:Carbamidomethyl on  C]AAKFESNFNTQATNR\|HGLDNYRGY[Custom:NPA_Desthiobiotin on Y]SLGNWVC[Common   Fixed:Carbamidomethyl on C]AAKFESNFNTQATNR

Path to folder with psm file and mzML file containing peptide:
"Z:\Users\Madeleine\CrashDataFiles"

**Expected behavior for GUI**

Expected to see the chimeric scan view

**Screenshots**

n/a

**Desktop information**

**Additional context**

**Comment by mzhastings** [comment]
also fragment ion brackets aren't shown when looking at the ambiguous IDs child scan view (except for the first option)
![image](https://github.com/user-attachments/assets/4389e517-7313-490a-bb3d-fca164bbffb2)
![image](https://github.com/user-attachments/assets/de26b446-1361-4cf0-8b93-57f943697e80)

**Comment by nbollis** [comment]
Thanks for this report! The crash is an issue that I will look into. 

The lack of fragment ions annotations is intended. When we write the psm/peptide file only the matched fragment ions from the first ambiguous option is outputted. This means MetaDraw does not have enough information to accurately annotate any other ambiguous search result.
