### ISSUE TITLE
Search crashed at the protein loading stage

### ISSUE THREAD

**Issue by Dmorgen** [smith-chem-wisc/MetaMorpheus#2436]
Hi,
I've ran a calibration step using XML file containing all isoforms,  it crashed due to instrument definition?
[results.txt](https://github.com/user-attachments/files/17653966/results.txt)

Cheers,
David.

**Comment by nbollis** [comment]
Hey David,

Thanks for the report. It appears that the error was thrown from inside the ThermoFisher RawFileReader package. In our code-base, every single call to the problematic method is hard coded to send the same parameters, leading me to believe there is an issue with our RawFileReader dll (updated last in 2019) and/or the specific instrument your data was collected on. 

Can you provide a few details about the instrument you used and how this file may differ from those that have worked in the past?

**Comment by Dmorgen** [comment]
Hi,

please see the link, it provides one file:
https://drive.google.com/file/d/14yvGXxdFskZLaIjIObNsOkTNrdHKLzuw/view?usp=sharing

Assuming a file is corrupt for some reason - would that make the error?

**Comment by trishorts** [comment]
check that when you moved files around that the transfer was complete. we have seen instances when download doesn't completely finish causing problems. I'll try to download and open a file.

**Comment by Dmorgen** [comment]
Will do, Thanks!

D.

**Comment by Dmorgen** [comment]
OK - it was a corrupt file in the set. Thanks!

**Comment by trishorts** [comment]
bad file was the cause

**Comment by Dmorgen** [comment]
Thanks!
