### ISSUE TITLE
Crash mid run of a small DB

### ISSUE THREAD

**Issue by Dmorgen** [smith-chem-wisc/MetaMorpheus#2450]
Hi,

please see the attached crash log. the data is from a sample from teeth, searched against a small protein dataset, with GPTMD followed by the search. the search stage crashed.

Thanks!
David.

[results.txt](https://github.com/user-attachments/files/18116344/results.txt)

**Comment by trishorts** [comment]
are you willing to let us have a go?

**Comment by Dmorgen** [comment]
sure. I will prepare a folder in the box

**Comment by trishorts** [comment]
maybe the raw file is still loading?
i see fasta only

**Comment by trishorts** [comment]
working on fix here: https://github.com/smith-chem-wisc/MetaMorpheus/pull/2453
Bug created by attempted addition of modification to a peptidewithsetmods that already had a modification at the same position

**Comment by Dmorgen** [comment]
Thanks!
