### ISSUE TITLE
fattyacidtypemodifications.txt

### ISSUE THREAD

**Issue by trishorts** [smith-chem-wisc/MetaMorpheus#248]
Custom Modifications
ID   CHDH
FT   MOD_RES
TG   D
PP   Anywhere.
MM   294.183109
CF   H26 C17 O4
//
ID   CHDHminus2methylenes
FT   MOD_RES
TG   D
PP   Anywhere.
MM   266.151809
CF   H22 C15 O4
//

**Comment by stefanks** [comment]
Done https://github.com/smith-chem-wisc/MetaMorpheus/commit/16053dfddb8c67928748e2e8fb1a4e7d925c977f
