### ISSUE TITLE
Calibrated mzML files don't have an index list offset

### ISSUE THREAD

**Issue by zrolfs** [smith-chem-wisc/MetaMorpheus#254]
This isn't a problem for MetaMorpheus, but if users want to use the calibrated mzML files further downstream in other capacities, then it might be nice to include it.

**Comment by zrolfs** [comment]
This might be an issue with the downstream software I'm trying; I'll keep troubleshooting.

**Comment by stefanks** [comment]
Yes, this is an issue with mzLib. Follow the issue here: https://github.com/smith-chem-wisc/mzLib/issues/33
