### ISSUE TITLE
Open Mass Search-Different Number of PSMs per database

### ISSUE THREAD

**Issue by zrolfs** [smith-chem-wisc/MetaMorpheus#273]
Observing marginal (1-10) differences in the number of PSMs observed for open mass searches when using different databases and/or looking at only B or only Y ions. If the mass search is truly open, then every MS2 scan should be assigned an identity.

**Comment by stefanks** [comment]
MetaMorpheus requires at least one peak to have a PSM. So it's behaving as it should. Closing issue, please reopen if you think that this is not what's happening.
