### ISSUE TITLE
Label modification types in m.txt & Master list of modification types

### ISSUE THREAD

**Issue by acesnik** [smith-chem-wisc/MetaMorpheus#286]
"GG of K" should be labeled with a type that we can exclude for intact mass work.

We should also make a reference list of all modification types and maybe some descriptions.

**Comment by stefanks** [comment]
How would you classify that modification? What type?

**Comment by acesnik** [comment]
Tryptic product of ubiquitin, or maybe just tryptic product.

**Comment by stefanks** [comment]
See https://github.com/smith-chem-wisc/MetaMorpheus/issues/296
