### ISSUE TITLE
Hierarchical Analysis: Bioreps/techreps/fractions/experiment

### ISSUE THREAD

**Issue by stefanks** [smith-chem-wisc/MetaMorpheus#291]
Run combined analyses hierarchically: Bioreps/techreps/fractions/experiment will be defined by the user in the GUI (similar to MaxQuant), not in the file hierarchy. Analysis should then be run for each aggregate level, instead of the current case where it is only run for all files individually, and one analysis for all files together.

**Comment by stefanks** [comment]
How would this work in the command line version?

**Comment by trishorts** [comment]
never used the command line version. If a .toml file is used, the input file entry could be tab delimited with as follows:
file--->biorep--->fraction--->technicalRep
file.raw--->1--->7--->2

there could be command line arguments (-b 3 -f 7 -t3) for each file or simply to indicate that the .toml holds info for biorep -b, fraction -f and techrep -t

**Comment by rmillikin** [comment]
This has been sort of implemented with the addition of Experimental Design, but right now this is only used for normalization of peptide intensities. Make a new issue if you want to see this used for some other purpose, e.g. aggregating spectra, scoring based on consistent retention-time, etc.
