### ISSUE TITLE
Automatic second identification in coisolation event

### ISSUE THREAD

**Issue by trishorts** [smith-chem-wisc/MetaMorpheus#297]
Determine if the selected precursor matches optimum precursor during search. If different, trigger a second attempt for peptide spectrum match with the selected precursor having eliminated the already used MS2 peaks from the scan

**Comment by stefanks** [comment]
This significantly changes the code structure, since right now it is assumed throughout that every fragmentation spectrum can have only a single PSM, and not more.

**Comment by acesnik** [comment]
Why not look for additional matches even if the selected precursor matches the identified peptide on the first try?

**Comment by trishorts** [comment]
Yes. One could automatically do it. Depends on the payoff b/c search time doubles. A real/optimal precursor mismatch suggest to me high probability for coisolation event. Best to let the data dictate. Let's try double search and see the yield. Compare to pinged coisolation event.

**Comment by acesnik** [comment]
The modern search might ameliorate the search time issue, since it's no longer a search, _per se_.

**Comment by acesnik** [comment]
What about using the second best, etc., matches? If the two high-scoring matches have none of the same peaks, they could be assumed to be coisolated peptides.

**Comment by stefanks** [comment]
In the classic search that is being run with liberal paramerers, such as +-3.1 daltons, the match to the co-isolated peptides is computed as well already! All that needs to be done is to record it and account for it in the output somehow.

**Comment by acesnik** [comment]
Could you record them in the regular PSMs list? Target-decoy should still hold, as long as there's equal competition for decoy peptides as coisolation events.

**Comment by trishorts** [comment]
A coisolation event with TMT fixed tag means that the reporter ions are contaminated by the presence of at least two sets of reporters. This data should probably not be used for quantification.... Only clean spectra should be used.

**Comment by stefanks** [comment]
Done! https://github.com/smith-chem-wisc/MetaMorpheus/pull/376
