### ISSUE TITLE
Does including ammonia and water loss in psm scoring help?

### ISSUE THREAD

**Issue by stefanks** [smith-chem-wisc/MetaMorpheus#30]

**Comment by trishorts** [comment]
andromeda/maxquant scores as follows:

![image](https://cloud.githubusercontent.com/assets/16841846/24866156/f5a99064-1dce-11e7-8bf6-e9c661b5ccd0.png)

**Comment by stefanks** [comment]
Let's figure out which peak types are most useful!

For a specific experiment, let's conduct a search and then annotate all the confident identifications. Remove co-isolated peptides for simplicity. 

For each peak type, collect information such as: peaks found/total peaks, intensity matching, peak dependence on other peaks, sequence coverage, etc. 

Once we compile it, we should have the peak types ranked by how well they support an identification, and then consider including them in MM searches. This should be done separately for each instrument, fragmentation method, collision energy, etc.

**Comment by zrolfs** [comment]
Although obvious, I think it's worth mentioning that these additional ion types will dramatically increase the search time for all searches. A two pass search where we first score only b-y-ions, save the top N scoring peptides, and then re-score using the additional ions may be useful for resolving this issue.

**Comment by rmillikin** [comment]
I think this was a "no"?

**Comment by zrolfs** [comment]
@trishorts
