### ISSUE TITLE
Does scoring hits in top-down search differently help top-down identifications?

### ISSUE THREAD

**Issue by trishorts** [smith-chem-wisc/MetaMorpheus#306]
For scoring see:
https://www.ncbi.nlm.nih.gov/pubmed/24922115

J Proteome Res. 2014 Jul 3;13(7):3231-40. doi: 10.1021/pr401277r. Epub 2014 Jun 12.
The C-score: a Bayesian framework to sharply improve proteoform scoring in high-throughput top down proteomics.

LeDuc RD1, Fellers RT, Early BP, Greer JB, Thomas PM, Kelleher NL.

**Comment by rmillikin** [comment]
PEP seems to be a good way to do this.
