### ISSUE TITLE
Add calibration performance metrics

### ISSUE THREAD

**Issue by trishorts** [smith-chem-wisc/MetaMorpheus#309]
Create a calibration_results.txt file that had mean, median, standard deviation, and quartiles/95%? for each raw file before and after calibration. This info would be for both MS1 and MS2. That would be great info to see the effect, and to use as MS1/MS2 peak tolerance.

**Comment by stefanks** [comment]
Done for MS1 in https://github.com/smith-chem-wisc/MetaMorpheus/pull/326

**Comment by stefanks** [comment]
Done in https://github.com/smith-chem-wisc/MetaMorpheus/pull/342
