### ISSUE TITLE
One Search Result from Multiple Proteases

### ISSUE THREAD

**Issue by trishorts** [smith-chem-wisc/MetaMorpheus#310]
We're analyzing the same sample with multiple proteases now. Currently, data from each protease must be analyzed separately, producing multiple aggregated results files. There is no good way to combine these. I propose that we allow searching data with different proteases in a single run. The major impact of this will be improved protein parsimony since overlapping peptides will resolve assignment. ZR is getting proteasome data and RM is getting antibody data. Both would benefit greatly from this approach.

**Comment by stefanks** [comment]
So every protease would have a separate raw file? I'm not sure how to do it best from a design point of view!
How about an optional settings file for every raw file that would override the default task parameters?
Say we have rawFileTrypsin.raw and rawFileArgC.raw. I suggest that if alongside those there is a rawFileArgCsettings.toml with a single line "protease Arg-C", then every search that loads the rawFileArgC.raw would replace the selected protease with the one from the custom settings file.

**Comment by stefanks** [comment]
The way it would work in the GUI, is by having a new column in the Datafiles table, something like "custom settings". It would load these individualized settings and should be editable from the GUI. Mulitple selection would be allowed.

**Comment by trishorts** [comment]
I don't think we can use the same MM score cut-offs for different proteases, so we made to to get 1% in sub-groups (e.g. all the trypsin files, all the lysC files, etc.) and do the parsimony. I think 1% on protein parsimony would be fine using different sources of peptides b/c they could all still be assigned to both target and decoy. Having a single aggregated psms and aggregated unique psms might be somewhat problematic.

**Comment by zrolfs** [comment]
Is anybody working on this feature? What's the status look like?

**Comment by zrolfs** [comment]
Piggybacking off of this feature (because it could likely be done when creating custom datafile settings), could there be a feature to group raw files based on sample type (such as MaxQuant's group#)? i.e. search all replicates of one condition together for aggregation and protein parsimony and exclude other conditions. Right now the user has to manually start the next condition after waiting for the previous one to finish.

**Comment by stefanks** [comment]
File-specific searches are working now. 
Hierarchical analysis (grouping) is discussed here: https://github.com/smith-chem-wisc/MetaMorpheus/issues/291
