### ISSUE TITLE
Installation Package with "Check for Updates"

### ISSUE THREAD

**Issue by trishorts** [smith-chem-wisc/MetaMorpheus#311]
Might be nice instead of constantly deleting/downloading/unzipping....

**Comment by stefanks** [comment]
For this we need to figure out:
- What is the standard way of doing this?
- If this is a GUI exclusive feature or the command line version should have it too
- If this can work with the way releases are currently done, i.e. on the GitHub releases page

**Comment by trishorts** [comment]
![image](https://cloud.githubusercontent.com/assets/16841846/24513816/d3c8c3e2-1537-11e7-9f04-e9965ffc6376.png)

**Comment by stefanks** [comment]
free for Professional and Enterprise editions... We are using the Community edition

**Comment by stefanks** [comment]
Some FOSS alternatives to InstallShield http://alternativeto.net/software/installshield/?license=opensource

**Comment by trishorts** [comment]
With Installer, we can have automatic bug report generated which captures error message and system information. That will help us maintain well functioning software

**Comment by trishorts** [comment]
installer would also help us to make sure that software out in the wild could be fixed when we repair by informing them of "Critical Updates Available". Just found Lei using MM from 10 versions back. Clearly missing a few things.

**Comment by trishorts** [comment]
how about "autorevert"? for when those updates introduce bugs....???

**Comment by stefanks** [comment]
Generate and send automatic crash reports moved to new issue: https://github.com/smith-chem-wisc/MetaMorpheus/issues/778
Autorevert functionality is there already: if new version is buggy, we can remove it from the releases page, and the software would "upgrade" to a previous version.
