### ISSUE TITLE
Exception thrown with 0.0.77.0 when pruning database

### ISSUE THREAD

**Issue by lschaffer2** [smith-chem-wisc/MetaMorpheus#315]
System.Collections.Generic.KeyNotFoundException was unhandled
Message: An unhandled exception of type 'System.Collections.Generic.KeyNotFoundException' occurred in TaskLayer.dll
Additional information: The given key was not present in the dictionary.

Settings I used:
![image](https://cloud.githubusercontent.com/assets/16846041/24514065/9db9b9e0-1538-11e7-9c82-5fc0faf57f3d.png)

**Comment by stefanks** [comment]
Please try version 0.0.78

**Comment by stefanks** [comment]
FIxed
