### ISSUE TITLE
MM reads and used amino acid substitutions/insertions/deletions directly from database

### ISSUE THREAD

**Issue by trishorts** [smith-chem-wisc/MetaMorpheus#317]
Settings could be 1. use default sequence; 2. used modifed sequence; or, 3. use both sequences. XML looks like:

<feature type="sequence variant" description="In MODY10; dbSNP:rs121908278." id="VAR_063721" evidence="14">
<original>R</original>
<variation>C</variation>
<location>
<position position="6"/>
</location>
</feature>

**Comment by stefanks** [comment]
What do you mean by XML looks like:R C ?

Currently subsitutions/deletions (not insertions) are treated as modifications, and gptmd can add them.

Do you mean to look at specific uniprot designations of sequence changes?

Or something else?

Please expand!

**Comment by trishorts** [comment]
XML should like like this. User can decide to keep original ("M"), use new ("L") or use both.
![image](https://user-images.githubusercontent.com/16841846/28877511-2d631826-7762-11e7-84c3-825fe51806cd.png)

**Comment by stefanks** [comment]
Is this something that uniprot xmls already have, or this is something that only we have? 

What about the case where two variations are possible on a peptide? In this case there are 4 options! How much freedom do we want to give the user in this case?

**Comment by trishorts** [comment]
Yes. uniprot already has it. I'm not really interested in using any from UniProt. Just the ones we add. In that case I want to allow use of all the options. I think. Might be case by case. But, if we see them in the RNA and believe they are coding variants. Then I want to look for them in the mass spec.

**Comment by rmillikin** [comment]
@acesnik

**Comment by acesnik** [comment]
This is implemented, à la Spritz.
