### ISSUE TITLE
Modification boxes GUI Usability

### ISSUE THREAD

**Issue by stefanks** [smith-chem-wisc/MetaMorpheus#318]
Modification summaries on the search task window, in the form
```
    variable: Oxidation of M
    fixed: Carbamidomethyl of C, TMT tag
    localize: 250 modification types
```

Do we still need the ability to add/edit custom modifications in the GUI? I'm not sure about that anymore.
Also, do we still need drag-drop a custom modification file into the GUI capability?
Do we still need filter modifcation list by any field or property?

**Comment by trishorts** [comment]
I think it'd be nice to have a custom checkbox in the search tab that kept previous custom mods our allowed user to enter new ones. These stored in a text file. Could ensure proper formatting and that minimum required fields are filled.
![image](https://user-images.githubusercontent.com/16841846/28877375-ca28cd1e-7761-11e7-841d-a3452541fd82.png)
