### ISSUE TITLE
Add tooltip descriptions to clarify options in task windows

### ISSUE THREAD

**Issue by acesnik** [smith-chem-wisc/MetaMorpheus#329]
It would be nice to have tooltip descriptors that clarify what certain options in the task windows do. 

One example is Aggregate Proteins. It's concise, but vague by itself. Some tooltip information upon hovering over the label/checkbox would help a bunch.

**Comment by rmillikin** [comment]
I added tooltips to the protein aggregation settings and the quantification settings, they're very easy to edit and suggestions are welcome

**Comment by rmillikin** [comment]
a lot of tooltips added in #1109 

please open a new issue (or just put it on slack) regarding new tooltips. 

for new tooltip requests, please include a suggested tooltip message.
