### ISSUE TITLE
Put an actual note recommending against using uniprot and unimod modifications for gptmd

### ISSUE THREAD

**Issue by acesnik** [smith-chem-wisc/MetaMorpheus#330]
The Mods list has several things that are also represented in the Uniprot modifications, e.g. phophos. It doesn't look like these are hashed to give a unique set of modifications at GPTMDTask.cs @ line ~136. Leah and I are curious how these are being handled, i.e. what happens upon collisions.

**Comment by stefanks** [comment]
Treated as unique. Need to do this for mainly because ptmlist does not include neutral loss info.

**Comment by lschaffer2** [comment]
Which does it assign in the Gptmd database since overlaps would have the same mass? Do you recommend just using the mods one or birth?

**Comment by lschaffer2** [comment]
*both. Sorry for accidentally closing/reopening. On my phone.

**Comment by stefanks** [comment]
Recommend against using uniprot and unimod modifications for gptmd.

**Comment by stefanks** [comment]
If multiple mods selected, all with corresponding masses would be added. It would be a mess

**Comment by lschaffer2** [comment]
Got it. I would put an actual note of this at the top of where you check mods because it wasn't immediately obvious to me.

**Comment by rmillikin** [comment]
uniprot removed from search options in #1723 .
