### ISSUE TITLE
GPTMD databases from old versions cause crashes when searching

### ISSUE THREAD

**Issue by rmillikin** [smith-chem-wisc/MetaMorpheus#336]
No error message is given if a mod in a database does not exist in the mod .txt files. This may be solved by defining mods within the GPTMD database XML file.

This crash is due to names of mods changing version to version.

**Comment by lschaffer2** [comment]
Anthony added mod definitions to the xml. Maybe any there that aren't in the mod .txt files could be added. If same chem formula/mass/location then go with the xml version so they're properly read in?

**Comment by stefanks** [comment]
Yes, mods are defined in the gptmd database file. If this is a cross-version issue, please close!
