### ISSUE TITLE
Pruned GPTMD database is not selected automatically

### ISSUE THREAD

**Issue by rmillikin** [smith-chem-wisc/MetaMorpheus#337]
In the "Protein Databases" window the pruned DB should be displayed and checked, while the unpruned GPTMD database should be unchecked automatically for subsequent tasks

**Comment by stefanks** [comment]
Why do you think this is needed?

**Comment by rmillikin** [comment]
The user is pruning the database for a reason and it will interrupt their workflow if they have to GPTMD -> prune -> stop their search and restart a new search with a new database -> continue searching

Any interruption in the workflow in generally undesirable imo

**Comment by stefanks** [comment]
I think the pruned database is only used outside of metamorpheus. So if gptmd is followed by two searches, I believe the more logical approach is to write two pruned databases based on the gptmd output database, and not sequentially.
Can you come up with a case where a pruned database would be useful within metamorpheus?

**Comment by lschaffer2** [comment]
Any subsequent searches right? I'd only want to run searches with novel PTMs added that met the cutoff.

**Comment by stefanks** [comment]
Okay, let's put this on the list of things to do!

**Comment by rmillikin** [comment]
I think that's a pretty valid point; the only thing I can think of is if you're doing multiple rounds of GPTMD over multiple searches (e.g. different searches for different proteases) maybe you'd want the search space to not get more large than is necessary? That might result in more false positives

**Comment by stefanks** [comment]
Now it is more complicated, since TWO pruned databases are being written. I vote against adding either one to the current database list.

**Comment by lschaffer2** [comment]
I agree now, if want subsequent searches with pruned databases, we can open new instance of MM and load in the pruned one of choice.

**Comment by stefanks** [comment]
Okay, closing
