### ISSUE TITLE
Disambiguate terms

### ISSUE THREAD

**Issue by trishorts** [smith-chem-wisc/MetaMorpheus#341]
I found that the same term was being used in the headers of different file output in slightly different forms. I'd like the same form used for each different header to remove confusion. Here are the examples that I found:

**CountDecoy**
**CountTarget**
**Cumulative Decoy**
**Cumulative Target**
**cumulative_decoy**
**cumulative_target**

**matched ion counts**
**matched ions**

**Protein Full Name**
**Protein FullName**

**Sequence coverage**
**Sequence coverage %**

**Comment by stefanks** [comment]
Executive decision: Human readable, space-separated, individual words capitalized.

**Comment by trishorts** [comment]
Once this is done, we'll have to update the glossary of terminology in the wiki

**Comment by stefanks** [comment]
For psms tsv files, this is done in https://github.com/smith-chem-wisc/MetaMorpheus/pull/376

Still need to finish this for protein files.

**Comment by stefanks** [comment]
Done in https://github.com/smith-chem-wisc/MetaMorpheus/pull/507
