### ISSUE TITLE
Consider least squares fit to quadratic for 1% FDR cut-off

### ISSUE THREAD

**Issue by trishorts** [smith-chem-wisc/MetaMorpheus#343]
currently, the total decoy divided by total target causes and FDR cliff, with then slopes back down until the next decoy shows up. I think that some folks do a quadratic fit to the running FDR so that the cut-off is more robustly set

**Comment by stefanks** [comment]
What is the problem with the way things are done now? Can you give an example of a wrong result?

**Comment by trishorts** [comment]
![image](https://user-images.githubusercontent.com/16841846/28876964-8d518bb6-7760-11e7-8277-ccd2847a8199.png)
T/D around cut-off is clearly non-linear function. Simply saying that a fitted curve might be better

**Comment by rmillikin** [comment]
this issue seems not very relevant in the new PEP world
