### ISSUE TITLE
Bug with pruned databases

### ISSUE THREAD

**Issue by lschaffer2** [smith-chem-wisc/MetaMorpheus#348]
Fewer PTMs than Uniprot database

**Comment by lschaffer2** [comment]
@stefanks, if you just change line 302 in searchtask to "Uniprot" instead of "uniprot" it works. I don't think my pull request is ready yet - too slow for large # PSMs/other fixes we talked about so maybe you could just change this one line/release

**Comment by stefanks** [comment]
Whoops, okay!

**Comment by stefanks** [comment]
Fixed in https://github.com/smith-chem-wisc/MetaMorpheus/pull/353
