### ISSUE TITLE
Include Protein Mass in ProteinGroups.tsv

### ISSUE THREAD

**Issue by zrolfs** [smith-chem-wisc/MetaMorpheus#357]
Simply add another column with the monoisotopic mass of the unmodified identified protein. This would aid in the transition from peptide to protein analysis for groups with high mass range issues (e.g. us) by allowing the user to readily determine how many of the proteins analyzed by bottom-up could be viably detected in a protein mode. It would also make size separated samples easy to validate. This mass output is something that Proteome Discoverer already includes and would be very easy to implement.

**Comment by stefanks** [comment]
Done in https://github.com/smith-chem-wisc/MetaMorpheus/pull/797
