### ISSUE TITLE
Pruning after GPTMD may introduce bias due to quality of false targets in subsequent searches

### ISSUE THREAD

**Issue by acesnik** [smith-chem-wisc/MetaMorpheus#366]
We should include all decoys that meet the 1% FDR cutoff, too. Then, upon making a decoy database in a subsequent search, we should only generate decoys up until the count of target to decoy is the same. See https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3613568/.

This seems somewhat non-trivial to implement because we don't want to combinitorially generate decoys in this case, but rather include only the (potentially) modified decoy peptides that passed the 1% FDR cutoff before pruning.

**Comment by stefanks** [comment]
Yes, this is a serious issue. Another consideration is the creation of gptmd database itself. Should we add decoys there?

Anyways, for both of these questions, if we do need to add decoys, it will be in a form of adding only the decoy **modifications**.

**Comment by acesnik** [comment]
I wonder if this might ameliorate the modified peptide FDR problems we've been discussing in Slack. If we pruned the database of PTM sites not observed in the data (similar to a traditional two-pass reductive search), while maintaining high-scoring decoy modifications, we could maybe improve the FDR for modified peptides and avoid FDR underestimation problems due to pruning high-scoring decoys.

**Comment by stefanks** [comment]
Actually, I believe this issue should be addressed in sone other way. A pruned database should be great highly precise correct and exact. Without contamination by decoy mods.

**Comment by stefanks** [comment]
I vote to close this issue and instead address by making sure the decoy generation and scoring work well whe using pruned databases. And I believe they do. If there is evidence they do not, let's address it separately

**Comment by acesnik** [comment]
I'll try searching with a pruned DB and see if I see the decoy quality bias Everett and company saw (ref from above).

**Comment by acesnik** [comment]
I'm not seeing the same thing Bern and Kil reported regarding the Everett paper. Here's the plot that shows the results of decoy quality bias. The two traces above 1PASS are biased in quality and quantity; Bern and Kil were especially concerned about the EV trace.

![image](https://user-images.githubusercontent.com/16342951/28597586-514c60fc-7164-11e7-84b7-f797911ee0c8.png)

Here's what I'm seeing, where the blue trace is the GPTMD 2nd search, and the grey trace is a 3rd search with a pruned database. The grey trace is slightly below the blue trace, indicating that there isn't the bias discussed in the paper by Bern and Kil. The curves for the modified peptides are slightly different but again do not show significant bias.

![image](https://user-images.githubusercontent.com/16342951/28632845-72f3af06-71f7-11e7-8d68-68e9da7bebfc.png)
