### ISSUE TITLE
Add checkbox to only write seen proteins in pruned database

### ISSUE THREAD

**Issue by stefanks** [smith-chem-wisc/MetaMorpheus#370]

**Comment by trishorts** [comment]
I think this could have some utility depending on how one would use it later. With respect to adding only seen PTMs in pruned, I think we keep the ones that were there before. In that way, a general purpose database of good quality can evolve over time. We don't, however, delete PTMs that were there. We might want to see them in another sample some day. Similarly, you might want to see some proteins that weren't in this sample but might be in another one. Having the option is nice, but dangerous in the hands of the uninitiated. 

This, of course, doesn't at all get into the problems of FDR with reduced databases. I don't think we would use reduced databases for further bottom-up studies.

**Comment by stefanks** [comment]
Got done somewhere along the way. No need for separate check box, now selecting write pruned database writes both kinds: ptm and protein pruned.
