### ISSUE TITLE
Peptides with different mass shifts not treated as unique

### ISSUE THREAD

**Issue by stefanks** [smith-chem-wisc/MetaMorpheus#372]
Need to do that for quantification

**Comment by trishorts** [comment]
not treated as unique currently but should be in the future......
          (PEPTIDE +0Da) not same as (PEPTIDE +42Da)

**Comment by trishorts** [comment]
We could add "mass shift modifications" to the database just like we have in the proteoform nomenclature standard. The full sequence would look something like PEPTI[mass:+14.02]DE. These would then be considered unique and quantified accordingly.

**Comment by stefanks** [comment]
But quantification should not be run on open search results anyway! Also, quantification is not coupled to unique peptides output anyway. I vote to close this issue.

**Comment by trishorts** [comment]
ok
