### ISSUE TITLE
GG of K mod type

### ISSUE THREAD

**Issue by acesnik** [smith-chem-wisc/MetaMorpheus#396]
Might be good to label GG of K a "TrypticProduct" https://github.com/smith-chem-wisc/MetaMorpheus/blob/master/EngineLayer/Mods/Mods.txt#L303

**Comment by stefanks** [comment]
Why? I thought ubiq is a biological modification, and GG of K simply says that it was there at some point. It's not appearing only because of Trypsin digestion, it was there before that.

**Comment by stefanks** [comment]
I'll change it to TrypsinDigestedMod

**Comment by stefanks** [comment]
Done
