### ISSUE TITLE
Score is not always reflective of Matched Ions Count

### ISSUE THREAD

**Issue by zrolfs** [smith-chem-wisc/MetaMorpheus#399]
Issue occurs in classic and modern search in approximately 1% of PSMs. My guess is that improvement possible is changing one of the peaks outside or inside the tolerance, as the score is calculated before the matched ions occur.

This is not a major bug for traditional users, but is a source of additional ambiguity for fusion peptides.

**Comment by stefanks** [comment]
Is this still an issue? If yes, could you give an example?

**Comment by zrolfs** [comment]
It is recognized (and utilized) that the Score can be higher than the Matched Ions Count. I don't remember if the inverse ever occurred. I'll reopen if I find an example of that.
