### ISSUE TITLE
Allow for customizable proteases (like mods)

### ISSUE THREAD

**Issue by rmillikin** [smith-chem-wisc/MetaMorpheus#402]
AspN protease selection currently only generates theoretical peptides cleaved at D, but could also include C and Q:
The endoproteinase AspN cleaves primarily at amino side of aspartate residues and cysteic acid residues that result from the oxidization of cysteine residues, generating a limited number of peptide fragments. Cleavage can also occur at glutamic residues; however, the rate of cleavage at the glutamyl residues is significantly lower than the rate of cleavage at the aspartic acid residues.

I am curious as to how many PSMs we are mis-assigning when using other proteases because we are not including these known observed cleavages in our search space.

**Comment by rmillikin** [comment]
Woops! This is Zach Rolfs on Rob's account, since it was logged in on Artemis. Sorry Rob!

**Comment by stefanks** [comment]
You can edit the proteases file to add a custom protease with any digestion sites. Customizing cleavage taking modifications into account is discussed here: https://github.com/smith-chem-wisc/MetaMorpheus/issues/404
