### ISSUE TITLE
Add MetaMorpheus terms to HUPO

### ISSUE THREAD

**Issue by trishorts** [smith-chem-wisc/MetaMorpheus#405]
1. add MetaMorpheus terms to HUPO github https://github.com/HUPO-PSI/mzIdentML
2. test output against PRIDE
3. test output agains IDConvert

**Comment by trishorts** [comment]
Craig's mzIdentML worked, so if you can emulate that we should be good.  
  ( As one test of the mzIdentML format being correct, idconvert was able to convert it to pep.XML )

You may need to register new Controlled Vocabulary Terms at ( at minimum the application name ): 
https://raw.githubusercontent.com/HUPO-PSI/psi-ms-CV/master/psi-ms.obo  




Craig added these:
[Term]
id: MS:1002661
name: Morpheus
def: "Morpheus search engine." [PMID:23323968]
is_a: MS:1001456 ! analysis software

[Term]
id: MS:1002662
name: Morpheus:Morpheus score
def: "Morpheus score for PSMs." [PSI:PI]
xref: value-type:xsd\:double "The allowed value-type for this CV term."
is_a: MS:1001143 ! PSM-level search engine specific statistic
relationship: has_order MS:1002108 ! higher score better

[Term]
id: MS:1002663
name: Morpheus:summed Morpheus score
def: "Summed Morpheus score for protein groups." [PSI:PI]
xref: value-type:xsd\:double "The allowed value-type for this CV term."
is_a: MS:1002368 ! search engine specific score for protein groups
relationship: has_order MS:1002108 ! higher score better

**Comment by lschaffer2** [comment]
Current mzidentml output works with id convert/has everything craig included in his... Still need to do 1 and 3 though. I used the existing Morpheus terms  for CV terms

**Comment by stefanks** [comment]
More discussion here: https://github.com/smith-chem-wisc/MetaMorpheus/issues/52

**Comment by stefanks** [comment]
What's the status of CV terms? 
Validation discussion here: https://github.com/smith-chem-wisc/MetaMorpheus/issues/52

**Comment by trishorts** [comment]
should be close

**Comment by stefanks** [comment]
Done in https://github.com/smith-chem-wisc/MetaMorpheus/pull/918
