### ISSUE TITLE
allow peptide length limit for no enzyme searches

### ISSUE THREAD

**Issue by trishorts** [smith-chem-wisc/MetaMorpheus#411]
many searches of peptides (like neuropeptides and neoantigens) have short targets. We could let the user set the upper length limit, and thus limit the possibilities to score against and shorten time for comparison

**Comment by trishorts** [comment]
An option is to quickly asses the mass of the largest ion selected for fragmentation and limit the mass of any peptide in the theoretical database to that number (subject to PTM enlargement).

**Comment by stefanks** [comment]
I believe the first issue is already taken care of https://github.com/smith-chem-wisc/MetaMorpheus/issues/208

**Comment by trishorts** [comment]
I'm talking about MAXIMUM length. Not MINIMUM length. But perhaps they're related.

**Comment by stefanks** [comment]
Yup, both are there!

**Comment by trishorts** [comment]
excellent. I wait eagerly for the feature :)

**Comment by zrolfs** [comment]
It's already available in the current release?

**Comment by trishorts** [comment]
i see it.
