### ISSUE TITLE
More flexible result name and folder location

### ISSUE THREAD

**Issue by trishorts** [smith-chem-wisc/MetaMorpheus#431]
automatic naming and results folder placement is can be extremely inconvenient when running multiple instances. would be nice if user could change the default folder and file precursor and also the output folder location. 

This problem surfaced again when only some of many searches crashed midway. And there is no way without opening each folder to see which crashed where and why.....

**Comment by stefanks** [comment]
Please expand on how you see this working. Require user to write the name of the output for each task? What about the overall output folder that currently has the time/date. Where would this go in the GUI? 
I don't see a non-clumsy way of doing this.

**Comment by trishorts** [comment]
add a "File Saving Parameters" tab to the task menus. Could be left with all the defaults that are currently use. But, would have option of changing output folder location and name

**Comment by stefanks** [comment]
Fixed
