### ISSUE TITLE
crash multiple instances accessing same file

### ISSUE THREAD

**Issue by trishorts** [smith-chem-wisc/MetaMorpheus#443]
I guess. Happening for reading .xml.

slack had this to say:

If you want to read from the same file in many instances of the program, with no instance writing to it, then that is also easily doable. Just open the file in shared read-only mode, and there is no problem at all letting lots of programs read the file simultaneously.

using (Stream stream = new FileStream(filePath, FileMode.Open, 
                                      FileAccess.Read, FileShare.Read))

**Comment by stefanks** [comment]
FIxed in upstream https://github.com/smith-chem-wisc/mzLib/commit/e742c343b5c51d1ad6196da27614cc727deecf4f
