### ISSUE TITLE
Trigger linear calibration or expand tolerance automatically on calibration failure

### ISSUE THREAD

**Issue by trishorts** [smith-chem-wisc/MetaMorpheus#453]
Nice options to have in the calibration task

**Comment by stefanks** [comment]
Not sure I want this functionality: a failure with accompanying information serves as a teaching tool to make users aware of the quality of their own data.

**Comment by stefanks** [comment]
I want to be convinced one way or the other

**Comment by trishorts** [comment]
I think when i created the issue, MM would crash upon failure to find calibration points. Currently, MM continues to work on other files, which is good. 

I don't care for "teaching tools". Seems like one of those frustrating video games that prevent you from moving on until you discover the stupid trick. That appeals to some but not universally adored.

If MM could do the paramedic option on the .raw files, then the user would have to enter in any tolerances. This would be my preference. That aside, I would like to know just how users know when their files don't calibrate and why. I still don't know and routinely have files that don't calibrate.

**Comment by lschaffer2** [comment]
It could start at ten ppm and increase to 15 or 20 automatically if there aren't enough points

**Comment by rmillikin** [comment]
I've done this in #1121 

Round1: use task settings. If enough points, break the loop
Round2: 20ppm precursor, 50ppm fragment
Round3: 30ppm precursor, 100ppm fragment
Round4: 40ppm precursor, 150ppm fragment
Round5: Failure, calibration quits

These numbers are hardcoded and can be changed easily, let me know if you think they should be changed
