### ISSUE TITLE
Crash when ThermoFileReader not installed

### ISSUE THREAD

**Issue by trishorts** [smith-chem-wisc/MetaMorpheus#464]
rather than nameless crash

**Comment by acesnik** [comment]
See https://github.com/smith-chem-wisc/mzLib/issues/106

**Comment by stefanks** [comment]
This is a high priority issue! Up for grabs.

**Comment by acesnik** [comment]
Resolved with the mzLib addition, correct?

**Comment by stefanks** [comment]
Handling this gracefully not implemented in MM yet. Looking at it now.

**Comment by stefanks** [comment]
But the main issue (of an uncatchable exception thrown due to missing COM component) is fixed.

**Comment by stefanks** [comment]
Current work: https://github.com/smith-chem-wisc/MetaMorpheus/pull/774

**Comment by stefanks** [comment]
Fixed in https://github.com/smith-chem-wisc/MetaMorpheus/pull/774
