### ISSUE TITLE
Reusing GPTMD databases

### ISSUE THREAD

**Issue by lschaffer2** [smith-chem-wisc/MetaMorpheus#486]
I tried to reuse GPTMD database and got the error due to multiple mods with same id and modification type. A temporary workaround was deleting the mods at the top of the database, but I think if there are mods in the database with same id/mod type, the database mods should be used instead instead of throwing exception

**Comment by stefanks** [comment]
Oh, no!!!! This issue came back. Will address this asap

**Comment by stefanks** [comment]
Please share the files with me, I am not able to reproduce this error.

**Comment by stefanks** [comment]
Error is intended to be thrown, made the error box more descriptive.
