### ISSUE TITLE
Exception thrown because a psm's mostProbableProteinInfo's PeptidesWithSetModifications contains no elements

### ISSUE THREAD

**Issue by lschaffer2** [smith-chem-wisc/MetaMorpheus#487]

**Comment by stefanks** [comment]
Try to turn parsimony off. Do you still get the same error?

**Comment by lschaffer2** [comment]
It only writes mzidentml's with parsimony on

**Comment by stefanks** [comment]
How about different parsimony checkboxes? Modified peptides as unique, etc? Any of those options work?

**Comment by lschaffer2** [comment]
I had it set to default I can try to change those and see if I still get the error

**Comment by lschaffer2** [comment]
If I check "treat modified peptides as different peptides" it works

**Comment by stefanks** [comment]
Please give me the files you used here as well!

**Comment by lschaffer2** [comment]
Same error with new release. I'll put files in your folder on bison

**Comment by lschaffer2** [comment]
Fixed in #493
