### ISSUE TITLE
Parallelization Inefficiency in new release 0.0.120?

### ISSUE THREAD

**Issue by zrolfs** [smith-chem-wisc/MetaMorpheus#488]
Indexing appears to be progressing rapidly and then hangs with a sliver from the end for several minutes. A similar "hanging" issue is occurring in "Matching Peptides to Proteins", but it is uncertain if this is unique to modern search. I assume these are parallelization problems, as the CPU drops down to 5% in task manager during these hangs. (Run on Orion, 128 GB RAM, 24 Core)

**Comment by stefanks** [comment]
Temporarily use release number 119, if possible.

**Comment by stefanks** [comment]
Is this still an issue?

**Comment by zrolfs** [comment]
I am not sure; I'll check and get back to you.

**Comment by zrolfs** [comment]
Doesn't seem to be occurring in 0.0.124.
