### ISSUE TITLE
Allow VCF file as input to MM

### ISSUE THREAD

**Issue by trishorts** [smith-chem-wisc/MetaMorpheus#489]
directly add variants prior to search

**Comment by acesnik** [comment]
I have a unit-tested C# VCF reader in my proteogenomics work.

**Comment by acesnik** [comment]
> maybe we could plot that in mzlib?

VCF contains variants called against a genome; UniProt doesn't have a reference genome and annotates SAVs as amino acid base positions. The information in the VCF file wouldn't be useful unless you have additional information about the reference genome and how the proteins were derived. I'm working on that in Proteoform Database Engine world.

**Comment by acesnik** [comment]
It looks like Uniprot also maintains references to dbSnp, so we could cross-reference sequence variants pulled in from VCF to decide which UniProt variants to keep. I think that's the only way we could get around not having a reference genome, at the moment.

**Comment by acesnik** [comment]
trishorts:
> could we use a paired system where someone would have to use an ensembl protein database with an ensembl context vcf? getting away from uniprot and using gptmd for ptms?

**Comment by rmillikin** [comment]
see #1124
