### ISSUE TITLE
Do percolator instead! checkbox to filter all results for 1% local FDR

### ISSUE THREAD

**Issue by trishorts** [smith-chem-wisc/MetaMorpheus#492]
individual modification types and total modification count

**Comment by stefanks** [comment]
Try to consider the number of modifications as a factor in the future implementation of percolator. Once that is done, the local FDRs should be indistiguishable, FDR should not be a function of anything.

**Comment by stefanks** [comment]
Duplicate https://github.com/smith-chem-wisc/MetaMorpheus/issues/31
