### ISSUE TITLE
Flag for confidently identified modifications

### ISSUE THREAD

**Issue by acesnik** [smith-chem-wisc/MetaMorpheus#497]
In multiple rounds of pruning, we would like to maintain the modifications previously identified at 1% FDR.

The challenge is in distinguishing these modifications from those added in GPTMD. I suggest we add a flag to the new modification entries when we write a pruned database. That way, we may know not to subject them to pruning again.

**Comment by rmillikin** [comment]
merging with #308

**Comment by acesnik** [comment]
Cool. I posted my comment there, in case it's useful, and so it doesn't get lost.
