### ISSUE TITLE
 Consistent capitalization in dropdowns (e.g. Ppm --> PPM)

### ISSUE THREAD

**Issue by acesnik** [smith-chem-wisc/MetaMorpheus#512]
It might be nice to write PPM instead of Ppm in the dropdown menus.

**Comment by trishorts** [comment]
ppm

**Comment by stefanks** [comment]
Arguments for/against PPM ppm Ppm?

**Comment by acesnik** [comment]
I guess it just bugs me when the capitalization is inconsistent, so I would suggest either "absolute" and "ppm" or "Absolute" and "PPM." Similarly, I would suggest having "Trypsin" instead of "trypsin," since "LysC" is capitalized (which is conventional for that protease, I believe).

**Comment by stefanks** [comment]
Going with ppm for now.

Fixed in https://github.com/smith-chem-wisc/MetaMorpheus/pull/690
