### ISSUE TITLE
Make pepXML an output option for standard search in metamorpheous

### ISSUE THREAD

**Issue by lonelu** [smith-chem-wisc/MetaMorpheus#514]
Do we want to use a 'choose button' of what type of output user want?

**Comment by rmillikin** [comment]
I like this idea

**Comment by stefanks** [comment]
I'd say more of a collection of checkboxes: PSMs tsv, mzid, pepXML

**Comment by acesnik** [comment]
I like the checkbox idea; one could export multiple types of results files for multiple purposes in a single run.

**Comment by rmillikin** [comment]
see #1124
