### ISSUE TITLE
Low-scoring peptides should not be used for protein parsimony

### ISSUE THREAD

**Issue by trishorts** [smith-chem-wisc/MetaMorpheus#517]
when a scan can be assigned as two different unique peptides from two different proteins with the same score, the peptides from that scan should not be used in the first round of parismony but should instead be assigned as if they were shared peptides in later rounds

**Comment by rmillikin** [comment]
we also need to decide if a certain q-value cutoff should be used for parsimony (0.01, 0.05 ...)

**Comment by lschaffer2** [comment]
Rob can you clarify? I thought PSMs that meet FDR cutoff are used for parsimony

**Comment by rmillikin** [comment]
Parsimony happens before FDR calculations currently, which I think is not desired behavior

**Comment by lschaffer2** [comment]
Yeah it seems like only those that meet cutoff should help decide what proteins are present

**Comment by rmillikin** [comment]
done in #1296
