### ISSUE TITLE
"Proteoform Family Assignment" Dropdown menus are narrow.

### ISSUE THREAD

**Issue by seanydai** [smith-chem-wisc/MetaMorpheus#519]
Complete words of the options could not be seen.
![ps2 2issue1](https://user-images.githubusercontent.com/20566230/28897275-936414b6-77a5-11e7-9b2e-f29195477113.png)

**Comment by acesnik** [comment]
Probably intended to be a proteoform suite issue :)

**Comment by seanydai** [comment]
Intended for a different software.
