### ISSUE TITLE
Validate mzIdentML against HUPO mzidentML and PRIDE validator, as well as ProteoWizard, IDConvert, Skyline, IDPicker 

### ISSUE THREAD

**Issue by stefanks** [smith-chem-wisc/MetaMorpheus#52]
Use mzLib, and the included class generated from schema.

**Comment by stefanks** [comment]
Or maybe mzTab is the format we should be focusing on?

**Comment by trishorts** [comment]
we could get some/all of this code from morpheus

**Comment by stefanks** [comment]
I would prefer to use class files generated from xsd, that are already included in mzLib. Less possibilities to mess up, and will automatically conform to specifications.

**Comment by trishorts** [comment]
check the result against the HUPO mzidentML and PRIDE validator tools:
https://github.com/HUPO-PSI/mzIdentML

**Comment by chambm** [comment]
Somebody reported a ProteoWizard idconvert failure on some MetaMorpheus mzIdentML. It has no peptide or protein information in it at all! Work in progress, I assume? :)

**Comment by rmillikin** [comment]
reorganized in #1125
