### ISSUE TITLE
Add FDR that ignores PSMs that match to both a target and decoy

### ISSUE THREAD

**Issue by zrolfs** [smith-chem-wisc/MetaMorpheus#544]

**Comment by zrolfs** [comment]
Currently PSMs that are assigned both a target and a decoy sequence are counted as decoys for FDR calculations. An additional FDR that does not consider these PSMs is desired, as the current method yields an inflated FDR rate.

**Comment by rmillikin** [comment]
did the e-value implementation resolve this issue?

**Comment by zrolfs** [comment]
No, e-value assigns the same score to both target and decoy. A "random" coin toss should be used in determining if it is a target or a decoy for FDR calculations (i.e. half a decoy).
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3220955/

It would be prudent to prevent overlap of the target and decoy space (assumption #1 of TD)
https://www.nature.com/articles/nmeth1019

**Comment by rmillikin** [comment]
I think we should do:

PSM that matches to more than one sequence, with one or more being a decoy: use fractional decoys.
e.g. a PSM matches to 2 decoys and 1 target, all with different sequences. Counts as 2/3 of a decoy.

PSM that matches to a target and a decoy, with the same sequence: remove the decoy and count as a target. The decoy is imaginary and no other decoy in the search space outscored the target, therefore it's a target hit.

**Comment by zrolfs** [comment]
The second part makes it slightly more likely for a target to randomly match over a decoy, but it is a small (>0.5% trypsin, >5% nonspecific) difference.

**Comment by rmillikin** [comment]
because the size of the search spaces for target and decoy are different?

**Comment by rmillikin** [comment]
method described above is implemented in #1481

**Comment by zrolfs** [comment]
I'm still confused on what we're doing. Are we counting these as 0.5 of a target and 0.5 of a decoy? Just as a target? Just as a decoy?
