### ISSUE TITLE
Custom task re-naming 

### ISSUE THREAD

**Issue by stefanks** [smith-chem-wisc/MetaMorpheus#545]
Brian: Would be helpful in the Tasks Pane of MM if the user could rename “Search Task” with descriptive things (e.g. 5ppm, Fixed/Dyn Mod, etc.).  The user could do this right after choosing settings and adding that task, and then these descriptive names would become the names of the folders with the results in them. This would help know later what results are in which folder, and it would help in picking a toml file to use for a future search.

**Comment by trishorts** [comment]
something has to be done soon about the file naming.

**Comment by stefanks** [comment]
Done in https://github.com/smith-chem-wisc/MetaMorpheus/pull/704
