### ISSUE TITLE
"too many" is less informative than previously outputting a single entry

### ISSUE THREAD

**Issue by zrolfs** [smith-chem-wisc/MetaMorpheus#561]
Have output be "XXXXXXXXX or too many"

**Comment by stefanks** [comment]
what's XXXXXXXXX  ?

**Comment by zrolfs** [comment]
a sequence, a number, anything that uses resolve to potentially return "too many".

**Comment by stefanks** [comment]
Could you give a specific example?

**Comment by zrolfs** [comment]
LIAQKVRGVDVVVGGHSNTFLYT or (too many)

**Comment by stefanks** [comment]
The whole reason "too many" is returned is because of ambiguity! There is no single base sequence that matches

**Comment by zrolfs** [comment]
"too many" is returned because the ambiguity results in a length over 32000, not because there is "too much ambiguity". We know nothing about the putative sequence if "too many is returned".

**Comment by stefanks** [comment]
Sure. But I don't like outputting a specific match. I feel that it's misleading

**Comment by zrolfs** [comment]
I'm outputting 31990 chars and then (too many)

**Comment by stefanks** [comment]
not a fan of this. It still arbitrarily gives preference to some sequences that made it over some that didn't

**Comment by zrolfs** [comment]
If there are 31990 characters worth of sequences, nobody is going to look at every single one of them. I want as many as possible, though, to allow the viewer to find the pattern. If multiple sequences scored the same, they have to have something in common that hits those peaks.

**Comment by stefanks** [comment]
Let's make a new column instead! That contains the "common pattern"

**Comment by zrolfs** [comment]
If there are really over 31990 characters, it's probably a crummy spectra and nobody will care about it. I care because of fusion peptide searches yielding low scoring initial identifications. I need something for Neo to grab.

**Comment by zrolfs** [comment]
I don't think the feature would be worth the time put into it.

**Comment by stefanks** [comment]
It might be useful to people! I don't think it's not worth the time.

 And I have two problems with displaying partial info: 1. Misleading 2. Makes files bigger

**Comment by zrolfs** [comment]
The "Matched Ion Masses" column should be enough info to obtain a common pattern. I need an example sequence! It is not misleading if we put "(too many)" at the end, as that is the disclaimer that not all possible sequences are being shown. I understand that including many entries will make files bigger, but we already do that with sequences that contain 31999 characters!

**Comment by zrolfs** [comment]
Going off of that thought, I notice that "Matched Ion Masses" is left blank in the case of ambiguity. Shouldn't those peaks be identical?

**Comment by stefanks** [comment]
I believe its currently blank if the compact peptide is ambiguous. But I see your point, even in case of ambiguity the peaks matched should be identical... Hm.

**Comment by zrolfs** [comment]
Begrudgingly agree to disagree.
