### ISSUE TITLE
Cumulative Target/Decoy appears to randomly skip numbers.

### ISSUE THREAD

**Issue by zrolfs** [smith-chem-wisc/MetaMorpheus#569]
_T_D_
1_0
2_0
3_0
**4_0
6_0
6_2**
7_2
8_2
9_2
etc

**Comment by rmillikin** [comment]
could be due to the way FDR is done now (aggregate FDR on all files together, instead of for each individual file) - is this happening in individual results files or in the aggregate results file?

**Comment by zrolfs** [comment]
I only observe it in aggregate

**Comment by rmillikin** [comment]
hmm ok could be a bug then. Are any of them ambiguous?

**Comment by zrolfs** [comment]
The skipped number is missing entirely, so I am not sure. Many visible entries have ambiguities.

**Comment by stefanks** [comment]
What version?

**Comment by zrolfs** [comment]
[results.txt](https://github.com/smith-chem-wisc/MetaMorpheus/files/1246921/results.txt)

[prose.txt](https://github.com/smith-chem-wisc/MetaMorpheus/files/1246922/prose.txt)

**Comment by zrolfs** [comment]
[SearchTaskconfig.txt](https://github.com/smith-chem-wisc/MetaMorpheus/files/1246925/SearchTaskconfig.txt)

**Comment by zrolfs** [comment]
0.0.136

**Comment by zrolfs** [comment]
Hmmm.... might be specific to nonspecific search. Will check really quick.

**Comment by zrolfs** [comment]
Nope, found it in a classic search too.

**Comment by stefanks** [comment]
Fixed in https://github.com/smith-chem-wisc/MetaMorpheus/pull/599

**Comment by zrolfs** [comment]
What was the issue?

**Comment by stefanks** [comment]
Psms were grouped after fdr calculation was done, but that grouping was unnecessary
