### ISSUE TITLE
Allow file specific tolerance (as was done with proteases)

### ISSUE THREAD

**Issue by zrolfs** [smith-chem-wisc/MetaMorpheus#580]
Not all data is created equal. Some data files are incapable of being calibrated or have wider breadth of tolerance. If we could specify tolerance for each raw file, we may be able to improve our PSMs by 5-10% with minimal computational cost.

**Comment by zrolfs** [comment]
#518

**Comment by stefanks** [comment]
This will be ready very soon, once I merge https://github.com/smith-chem-wisc/MetaMorpheus/pull/562

**Comment by stefanks** [comment]
Done
