### ISSUE TITLE
Write pruned database with only certain mod types

### ISSUE THREAD

**Issue by lschaffer2** [smith-chem-wisc/MetaMorpheus#631]
Right now water loss, deamidation, oxidation are being added to the pruned theoretical database for future bu and proteoform searches

**Comment by stefanks** [comment]
Okay! Let's do this. Make a data grid where each row is a mod type. For each mod type, user can select one of four options: do not write, write if observed, write if in database, write if observed and in database. With sane defaults.

**Comment by stefanks** [comment]
This datagrid would replace the "keep uniprot modifications" checkbox.

Also, in the pruned database, would you like protein-ambiguous modifications to be written? I.e. if the peptide is confidently identified, and a modification is localized, but there is protein ambiguity, would you want this modification to be written to both proteins?

**Comment by lschaffer2** [comment]
Since the keep uniprot modifications checkbox was for whether we should keep modifications that weren't detected but were originally in the database, wouldn't we still need that checkbox? 

I'm not sure on the best solution there - I suppose if there's no way to know which protein the mod was seen on, it would be better to write it to both. Does anyone else disagree?

**Comment by stefanks** [comment]
With my suggestion, the keep uniprot mods checkbox would be replaced by (and made more customizeable) by the "write if in database" option in the datagrid, which would be selectable for any kind of modification.

**Comment by lschaffer2** [comment]
Sounds good! Default checks could just be any uniprot mods in database

**Comment by stefanks** [comment]
Defaults something like:

| Type | Do Not Write | Write if in database and observed| Write if in database| Write if observed|
| ------------- |:-------------:| -----:| -----:| -----:|
| Artefact      | * |  | | |
| Uniprot      |  |  | *| |
| Mod|  | * | | |
| N-Term Actylations|  |  | |* |

The write if observed might be used if doing a variable n-term acteylation search, where the acetylations are biologically significant, but are not necessarily in the xml database.

**Comment by lschaffer2** [comment]
For that example would Mod also have * under write if observed? If it's novel it wouldn't be in database

**Comment by stefanks** [comment]
No, because usually the Mods are not included as variable modifications. So the only way to observe these "Mod"s is to do G-PTM-D, and run a search with the augmented database.

**Comment by lschaffer2** [comment]
oh so if you run GPTMD then the final search, write if in database and observed means the database made w/ GPTMD (but not ever written) not the one originally loaded in

**Comment by stefanks** [comment]
Correct, except the GPTMD database is being written/read.

**Comment by stefanks** [comment]
This is a high priority issue. Up for grabs!

**Comment by stefanks** [comment]
Also add a new column  in the PSMs file, called "Essential Sequence", where the only PTMs displayed are the ones selected for writing in the pruned database.

**Comment by stefanks** [comment]
Done in https://github.com/smith-chem-wisc/MetaMorpheus/pull/821
