### ISSUE TITLE
NonSpecific Search: SemiSpecific Searching Protein Parsimony

### ISSUE THREAD

**Issue by zrolfs** [smith-chem-wisc/MetaMorpheus#633]
Currently the user must conduct two search tasks; one for semiN and one for semiC. There should be an option to search for both in a single task so that IDs can be pooled and protein parsimony can be conducted.

**Comment by stefanks** [comment]
Need more details on how this would work!

In the meanwhile, you can use two copies of the same file, with file-specific settings, setting one file to use semiN and the other semiC

**Comment by zrolfs** [comment]
I like that work around!
