### ISSUE TITLE
Wiki Figures

### ISSUE THREAD

**Issue by trishorts** [smith-chem-wisc/MetaMorpheus#645]
File Loading Parameters
![image](https://user-images.githubusercontent.com/16841846/30334813-44f975f2-97a6-11e7-8a51-e329de61e1d4.png)

**Comment by trishorts** [comment]
Search Parameters
![image](https://user-images.githubusercontent.com/16841846/30335989-6463b134-97a9-11e7-9935-5697d5676d5c.png)

**Comment by trishorts** [comment]
Modifications
![image](https://user-images.githubusercontent.com/16841846/30336836-fddeaf4c-97ab-11e7-8c29-e8c2d90abc90.png)

**Comment by trishorts** [comment]
Modifications
![image](https://user-images.githubusercontent.com/16841846/30336892-3a1e4e04-97ac-11e7-8c7c-8b0700a4ae24.png)

**Comment by trishorts** [comment]
Post-Search Analysis
![image](https://user-images.githubusercontent.com/16841846/30337118-f044a822-97ac-11e7-99cd-8b2a90db2f8d.png)

**Comment by trishorts** [comment]
![searchtask_fileloadingparameters](https://user-images.githubusercontent.com/16841846/40325927-20df6a8c-5d03-11e8-97a9-f062cff249ce.png)

**Comment by trishorts** [comment]
![searchtask_assumedspectraldataparameters](https://user-images.githubusercontent.com/16841846/40326137-e9152316-5d03-11e8-9fbe-63db86f268b1.png)

**Comment by trishorts** [comment]
![youtube_20](https://user-images.githubusercontent.com/16841846/40379523-eb130166-5dbb-11e8-8a03-559599cdd560.png)

**Comment by trishorts** [comment]
![mmnice](https://user-images.githubusercontent.com/16841846/40388611-a22ba290-5dd5-11e8-8ec1-2e0d1ef581fe.png)

**Comment by trishorts** [comment]
![mm_icon_56](https://user-images.githubusercontent.com/16841846/40388929-841db5da-5dd6-11e8-8c21-6c71eed30011.png)

**Comment by trishorts** [comment]
![tweet_56](https://user-images.githubusercontent.com/16841846/40389057-efdbfd40-5dd6-11e8-9d9e-68da0e793288.png)

**Comment by rmillikin** [comment]
![capture](https://user-images.githubusercontent.com/24705713/40666826-44a5cb7c-6326-11e8-8e57-17374deb000d.PNG)

**Comment by rmillikin** [comment]
[ExperimentalDesign.zip](https://github.com/smith-chem-wisc/MetaMorpheus/files/2048804/ExperimentalDesign.zip)

**Comment by zrolfs** [comment]
![neo-fusionparams](https://user-images.githubusercontent.com/16883585/43155898-4690a9b8-8f3e-11e8-82bc-042848a3145b.jpg)

**Comment by trishorts** [comment]
[MetaMorpheusXL User Guide_UserDefinedCrosslinker.pdf](https://github.com/smith-chem-wisc/MetaMorpheus/files/2291438/MetaMorpheusXL.User.Guide_UserDefinedCrosslinker.pdf)

**Comment by trishorts** [comment]
[LFQ with FlashLFQ in MetaMorpheus.pdf](https://github.com/smith-chem-wisc/MetaMorpheus/files/2291465/LFQ.with.FlashLFQ.in.MetaMorpheus.pdf)

**Comment by trishorts** [comment]
![qrcode 46975956](https://user-images.githubusercontent.com/16841846/47731367-f6632100-dc31-11e8-9c08-a80e4ca1a95b.png)

**Comment by zrolfs** [comment]
![image](https://user-images.githubusercontent.com/16883585/55643699-6bb2bf00-5799-11e9-87c1-8eace1fbfa6b.png)

**Comment by zrolfs** [comment]
![image](https://user-images.githubusercontent.com/16883585/55643866-d401a080-5799-11e9-97ec-a7399ae4e278.png)

**Comment by zrolfs** [comment]
![image](https://user-images.githubusercontent.com/16883585/66784288-9ba4f280-ee9f-11e9-9139-3e4d0fa3e459.png)

**Comment by zrolfs** [comment]
![image](https://user-images.githubusercontent.com/16883585/66784307-afe8ef80-ee9f-11e9-8a2c-95d4bd45c2f9.png)

**Comment by zrolfs** [comment]
![image](https://user-images.githubusercontent.com/16883585/66784321-bbd4b180-ee9f-11e9-9a59-bf6be88e4e11.png)

**Comment by zrolfs** [comment]
![MMIcon64x64](https://user-images.githubusercontent.com/16883585/75211541-da01c680-5749-11ea-9f6c-096dc2ec4dbc.png)

**Comment by trishorts** [comment]
![image](https://user-images.githubusercontent.com/16841846/194772117-174f0202-b184-4d26-89c9-663ff6235ed4.png)

**Comment by trishorts** [comment]
metamorpheus logo
![metamorpheuslogo](https://github.com/user-attachments/assets/e0dc5bc0-42de-42a0-b001-17dfd760b5fd)
