### ISSUE TITLE
Inconsistent handling of identical peptides between indexed and classic searches

### ISSUE THREAD

**Issue by zrolfs** [smith-chem-wisc/MetaMorpheus#656]
When ambiguity is turned off, a single theoretical is assigned to a spectra.
In the case where a peptide is present in both target and decoy search spaces (something that shouldn't occur in the first place), there is inconsistency in that:
For Classic, the peptide assigned is a always a decoy
For indexed searches, the peptide assigned is always a target.

To satisfy a TDA, there should be a random coin toss to determine which ID is assigned in both cases.

**Comment by zrolfs** [comment]
As an update, it doesn't appear that turning off ambiguity does anything to output of classic search, so that should be fixed, too.

**Comment by stefanks** [comment]
Is this fixed now?
