### ISSUE TITLE
Performance Improvement Ideas

### ISSUE THREAD

**Issue by stefanks** [smith-chem-wisc/MetaMorpheus#658]
Looking at the search task:

- Protein DB loading is fast enough
-  File loading
   - Raw files load slowly, try to load scans dynamically, as needed. 
   - Mzml load fast enough
   - Precursor deconvolution for coisolation is often slow on QHF files. Try to speed up, or turn off by default
- Classic search engine
   -  Protein digestion and GetPeptidesWithSetModifications are slow. Consider these improvements:
      - Collapse Digest and GetPeptidesWithSetModifications into a single method, remove PeptideWithPossibleModifications object
      - Instead of creating new ModificationWithMass objects, refer to modifications by a pre-determined key
      - Consider replacing the dictionaries that store modifications with arrays of integers corresponding to modification types and locations in peptide
   - Consider storing all digestion results, and then trimming them to remove duplicates
   - Too many peptide-scan comparisons
      - Too many peptides being generated, maybe some are not supposed to be there
         - Consider more restrictive defaults for min/max peptide lenghts, add lower/upper peptide mass limits
      - Too many scans are allowed to match a peptide, maybe restrict by prediction elution time 
   - Possible computer-sciency Parallel.ForEach loop performance improvements
- SequencesToActualProteinPeptidesEngine should benefit from protein digestion improvements
- Turn off mass shift localization by default

**Comment by zrolfs** [comment]
What about sorting theoretical and experimental peptides by precursor mass for classic search so that you wouldn't have to check if each theoretical is within an acceptable tolerance for each experimental?
