### ISSUE TITLE
Info in both "Code" and "Wiki" tabs

### ISSUE THREAD

**Issue by zrolfs** [smith-chem-wisc/MetaMorpheus#665]
There is some helpful information under the code tab that I keep thinking is in the wiki and cannot find because I never expect it in the code tab. Could we perhaps move that information (or at least duplicate it) into the wiki?

**Comment by stefanks** [comment]
The code tab contains text from Readme.md. It is the front page of MetaMorpheus, and should contain only short, simple instructions, that make users want to try it. The wiki should go into details, when necessary. Please use these guidelines when making changes!

**Comment by zrolfs** [comment]
I agree, but feel that not all the simple instructions from the readme are covered by the wiki.
