### ISSUE TITLE
Custom "Allowed Precursor Mass Differences" default back to 5 ppm when saved

### ISSUE THREAD

**Issue by zrolfs** [smith-chem-wisc/MetaMorpheus#668]
This is a super weird bug. If you add a new PMD and then select it, it turns blue and the bubble selects, but when you scroll up, the 5 ppm PMD is also still selected. When you scroll back down the new PMD is no longer selected. Saving anytime during this process returns 5ppm PMD. The workaround I've found is to select other PMDs and then the custom PMD.

**Comment by zrolfs** [comment]
Update: it occurs for other lower down radio buttons as well, not just custom PMD

**Comment by stefanks** [comment]
Fixed in https://github.com/smith-chem-wisc/MetaMorpheus/pull/690
