### ISSUE TITLE
Remove isotope peaks in MS2

### ISSUE THREAD

**Issue by zrolfs** [smith-chem-wisc/MetaMorpheus#736]
High intensity monoisotopic fragment ions tend to have a +1 neutron peak that should be removed during peak filtering. This will prevent incorrect assignments to these non-monoisotopic mass peaks and improve the intensity score.

**Comment by stefanks** [comment]
This is half-way to deconvolution... should we just switch over to deconvolution of ms2 scans?

**Comment by stefanks** [comment]
@rmillikin is this a part of your pull request?

**Comment by rmillikin** [comment]
no, the pull request removes nothing from the data. it deconvolutes isotope envelopes into a single mass, and uses that mass to look up theoretical fragment masses to match to.

**Comment by stefanks** [comment]
I think this is what Zach wants. Right?

**Comment by rmillikin** [comment]
it gives the same result but with a different method, so yes

**Comment by stefanks** [comment]
Okay! This is a high priority change, and is up for grabs, anyone is welcome to volunteer and make this happen :)

**Comment by rmillikin** [comment]
merged with #673
