### ISSUE TITLE
Allow for Variable CoIsolation Window

### ISSUE THREAD

**Issue by zrolfs** [smith-chem-wisc/MetaMorpheus#751]
Current coisolation is defaulted to 3 Da, but for top-down a larger window is common. We should include an option to modify the coisolation window.

**Comment by stefanks** [comment]
> Current coisolation is defaulted to 3 Da

No, it's no. See line 136 in https://github.com/smith-chem-wisc/mzLib/blob/d16f67356e97b659e386ec8b4de65106424708db/MassSpectrometry/DataScan/MsDataScanWithPrecursor.cs
