### ISSUE TITLE
Add PSM count column to unique peptides TSV file

### ISSUE THREAD

**Issue by trishorts** [smith-chem-wisc/MetaMorpheus#752]

**Comment by trishorts** [comment]
yes. I would love to see this feature added still......

**Comment by trishorts** [comment]
I'd like to promote the urgency of this functionality. I look for it routinely to get a sense for how likely a particular peptide assignment is correct. Do we see it once or a hundred times?

**Comment by trishorts** [comment]
q<=0.01 I think.

**Comment by rmillikin** [comment]
done in #1536
