### ISSUE TITLE
Investigate the reason for system dlls being distributed in the MM folder, and remove them if possible

### ISSUE THREAD

**Issue by stefanks** [smith-chem-wisc/MetaMorpheus#767]

**Comment by XRSHEERAN** [comment]
**Here is a list of dll files generated after adding SharpLearning NuGet package.**
SharpLearning.Common.Interfaces.dll 
SharpLearning.Common.Interfaces.dll
SharpLearning.Common.Interfaces.xml
SharpLearning.Common.Interfaces.xml
SharpLearning.Containers.dll
SharpLearning.Containers.dll
SharpLearning.Containers.xml
SharpLearning.Containers.xml
SharpLearning.CrossValidation.dll 
SharpLearning.CrossValidation.dll
SharpLearning.CrossValidation.xml 
SharpLearning.InputOutput.dll 
SharpLearning.InputOutput.xml
System.AppContext.dll
System.Collections.Concurrent.dll
System.Collections.NonGeneric.dll 
System.Collections.Specialized.dll 
System.Collections.dll
System.ComponentModel.EventBasedAsync.dll 
System.ComponentModel.Primitives.dll 
System.ComponentModel.TypeConverter.dll
System.ComponentModel.dll 
System.Console.dll | System.Console.dll
System.Console.dll
System.Data.Common.dll 
System.Diagnostics.Contracts.dll
System.Diagnostics.Debug.dll 
System.Diagnostics.FileVersionInfo.dll
System.Diagnostics.Process.dll
System.Diagnostics.StackTrace.dll
System.Diagnostics.TextWriterTraceListener.dll
System.Diagnostics.Tools.dll 
System.Diagnostics.TraceSource.dll 
System.Diagnostics.Tracing.dll 
System.Drawing.Primitives.dll 
System.Dynamic.Runtime.dll 
System.Globalization.Calendars.dll 
System.Globalization.Extensions.dll 
System.Globalization.dll 
System.IO.Compression.ZipFile.dll 
System.IO.Compression.dll 
System.IO.FileSystem.DriveInfo.dll 
System.IO.FileSystem.Primitives.dll 
System.IO.FileSystem.Watcher.dll 
System.IO.FileSystem.dll 
System.IO.IsolatedStorage.dll 
System.IO.MemoryMappedFiles.dll 
System.IO.Pipes.dll 
System.IO.UnmanagedMemoryStream.dll 
System.IO.dll 
System.Linq.Expressions.dll 
System.Linq.Parallel.dll 
System.Linq.Queryable.dll 
System.Linq.dll 
System.Net.Http.dll
System.Net.NameResolution.dll
System.Net.NetworkInformation.dll 
System.Net.Ping.dll 
System.Net.Primitives.dll 
System.Net.Requests.dll 
System.Net.Security.dll 
System.Net.Sockets.dll 
System.Net.WebHeaderCollection.dll 
System.Net.WebSockets.Client.dll 
System.Net.WebSockets.dll 
System.ObjectModel.dll 
System.Reflection.Extensions.dll 
System.Reflection.Primitives.dll 
System.Reflection.dll 
System.Resources.Reader.dll 
System.Resources.ResourceManager.dll 
System.Resources.Writer.dll 
System.Runtime.CompilerServices.VisualC.dll 
System.Runtime.Extensions.dll 
System.Runtime.Handles.dll 
System.Runtime.InteropServices.RuntimeInformation.dll 
System.Runtime.InteropServices.dll
System.Runtime.Numerics.dll 
System.Runtime.Serialization.Formatters.dll
System.Runtime.Serialization.Json.dll
System.Runtime.Serialization.Primitives.dll
System.Runtime.Serialization.Xml.dll
System.Runtime.dll 
System.Security.Claims.dll
System.Security.Cryptography.Algorithms.dll
System.Security.Cryptography.Csp.dll 
System.Security.Cryptography.Encoding.dll
System.Security.Cryptography.Primitives.dll 
System.Security.Cryptography.X509Certificates.dll
System.Security.Principal.dll
System.Security.SecureString.dll
System.Text.Encoding.Extensions.dll
System.Text.Encoding.dll
System.Text.RegularExpressions.dll
System.Threading.Overlapped.dll
System.Threading.Tasks.Parallel.dll
System.Threading.Tasks.dll
System.Threading.Thread.dll
System.Threading.ThreadPool.dll
System.Threading.Timer.dll
System.Threading.dll
System.ValueTuple.dll
System.Xml.ReaderWriter.dll
System.Xml.XDocument.dll
System.Xml.XPath.XDocument.dll
System.Xml.XPath.dll
System.Xml.XmlDocument.dll
System.Xml.XmlSerializer.dll
*.csproj file doesn't have any trace of how these files are generated.*

**Comment by stefanks** [comment]
Fixed in https://github.com/smith-chem-wisc/MetaMorpheus/pull/835
