### ISSUE TITLE
Taskbar pinned MM icon gets removed on update

### ISSUE THREAD

**Issue by stefanks** [smith-chem-wisc/MetaMorpheus#803]

**Comment by XRSHEERAN** [comment]
Also that uninstalling does not remove the icon. Working on them.

**Comment by XRSHEERAN** [comment]
It seems like there is not such a way for WIX to access taskbar pins, as said by many [forums](http://windows-installer-xml-wix-toolset.687559.n2.nabble.com/Keep-Desktop-Shortcuts-and-Pinned-Task-Bar-Icons-with-Upgrades-td7599707.html) and this [post](https://stackoverflow.com/questions/26269169/alternative-way-to-pin-an-exe-to-windows-taskbar). As far as I tried, WIX installer cannot access those pins and so I guess it is a bug on WIX or windows. Here is also a inclusive discussion on the taskbar pin problem and limitation of msi installer from [Adobe Brackets](http://windows-installer-xml-wix-toolset.687559.n2.nabble.com/Keep-Desktop-Shortcuts-and-Pinned-Task-Bar-Icons-with-Upgrades-td7599707.html).
