### ISSUE TITLE
ProteinGroups.tsv isn't excel compatible

### ISSUE THREAD

**Issue by zrolfs** [smith-chem-wisc/MetaMorpheus#823]
MDa proteins have sequences that exceed excel's character limit. Perhaps a "(too many)" as is done for psmtsv files, or only show valuble information near where sequences were observed such as "aasdfasdfasdfasdfasdfASDFASDFASDFASDFASDFAaasdfasdfasdf.... ...asdfasdfasdfafASDFASDF etc"

**Comment by rmillikin** [comment]
done in #934
