### ISSUE TITLE
Selenocysteine (U) questions

### ISSUE THREAD

**Issue by acesnik** [smith-chem-wisc/MetaMorpheus#846]
* is U carbamidomethylated like C? At what efficiency? Should it be a variable mod by default?
* Are there U's in any of the UniProt sequences? There are a hundred or so in the Ensembl protein sequences

**Comment by rmillikin** [comment]
selenocysteine does get carbamidomethylated. both S- and Se- are very nucleophilic (Se- more so than S-). Not sure of efficiency but probably high
 https://link.springer.com/article/10.1007/s00216-008-1883-5

Some examples of selenoproteins from a UniProt fasta:
>sp|P59797|SELV_HUMAN Selenoprotein V OS=Homo sapiens GN=SELENOV PE=1 SV=2
>sp|Q8IZQ5|SELH_HUMAN Selenoprotein H OS=Homo sapiens GN=SELENOH PE=1 SV=2
>sp|Q9NZV5|SELN_HUMAN Selenoprotein N OS=Homo sapiens GN=SELENON PE=1 SV=5
>sp|Q9BQE4|SELS_HUMAN Selenoprotein S OS=Homo sapiens GN=SELENOS PE=1 SV=3

**Comment by acesnik** [comment]
Thanks for looking into this! It sounds like we should consider adding fixed carbamidomethylation of U as a default.

**Comment by stefanks** [comment]
Any other thoughts? If there is consensus, I'll just add it

**Comment by acesnik** [comment]
Yes, it sounds like this should be the default.

**Comment by acesnik** [comment]
We got a definitive "yes" from Brian on this one, so let's make it a default.

**Comment by stefanks** [comment]
Done in https://github.com/smith-chem-wisc/MetaMorpheus/pull/861
