### ISSUE TITLE
command line invocation

### ISSUE THREAD

**Issue by jj-umn** [smith-chem-wisc/MetaMorpheus#851]
I'm finally getting back to testing MetaMorpheus via command line in Linux. 

The instructions I originally had were for version 0.0.111.0:
mono MetaMorpheusCommandLine.exe -d mouse-10.xml -s Task1SearchExample.toml -t Task1SearchExample.toml 

Is the correct download for commnd line now:  MetaMorpheusDotNetFrameworkAppveyor.zip

galaxy@galaxyp2014 [~/src/MetaMorpheus.0.0.238.0] % ls 
Chemistry.dll                            SharpLearning.CrossValidation.dll
CMD.exe                                  SharpLearning.DecisionTrees.dll
CMD.exe.config                           SharpLearning.GradientBoost.dll
CMD.pdb                                  SharpLearning.InputOutput.dll
Data                                     SharpLearning.Metrics.dll
EngineLayer.dll                          Spectra.dll
EngineLayer.pdb                          System.Data.Common.dll
FlashLFQ.dll                             System.Diagnostics.StackTrace.dll
FluentCommandLineParser.dll              System.Diagnostics.Tracing.dll
ManagedThermoHelperLayer.dll             System.Globalization.Extensions.dll
MassSpectrometry.dll                     System.IO.Compression.dll
MathNet.Numerics.dll                     System.Net.Http.dll
MetaMorpheusDotNetFrameworkAppveyor.zip  System.Net.Sockets.dll
Mods                                     System.Runtime.Serialization.Primitives.dll
mzIdentML.dll                            System.Security.Cryptography.Algorithms.dll
MzLibUtil.dll                            System.Security.SecureString.dll
MzML.dll                                 System.Threading.Overlapped.dll
NetSerializer.dll                        System.ValueTuple.dll
Nett.dll                                 System.Xml.XPath.XDocument.dll
Newtonsoft.Json.dll                      TaskLayer.dll
pepXML.dll                               TaskLayer.pdb
Proteomics.dll                           Thermo.dll
settings.toml                            UnmanagedThermoHelperLayer.dll
SharpLearning.Common.Interfaces.dll      UsefulProteomicsDatabases.dll
SharpLearning.Containers.dll

galaxy@galaxyp2014 [~/src/MetaMorpheus.0.0.238.0] % mono CMD.exe

Unhandled Exception:
System.IO.FileNotFoundException: Could not load file or assembly or one of its dependencies.
File name: 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'

**Comment by stefanks** [comment]
Thanks for looking at it! We recently switched over to .net core, please try this command!

```
dotnet CMD/bin/Release/netcoreapp2.0/CMD.dll -t Examples/Task1SearchExample.toml Examples/Task2CalibrationExample.toml Examples/Task3SearchExample.toml Examples/Task4GptmdExample.toml Examples/Task5SearchExample.toml -s Examples/example.mzML -d Examples/mouse-10.xml
```

**Comment by jj-umn** [comment]
Thanks.   Got it to run on my Macbook.   
We are still running Centos6 on our HPC system, so I may have to get a separate Centos7 node to try dotnet on linux.
