### ISSUE TITLE
E-value: remove the scores resulting from PROTEIN ambiguity from PSM.allScores

### ISSUE THREAD

**Issue by zrolfs** [smith-chem-wisc/MetaMorpheus#854]

**Comment by trishorts** [comment]
don't we want to keep those, since it will make the e-value worse? If another sequence can give the same score, then we can't be confident. If we can't be confident then there should be a bad e-value.

**Comment by zrolfs** [comment]
I agree with you for unique sequences. However, identical sequences present in multiple proteins hurt the eScore, despite high confidence in the sequence ID.

**Comment by trishorts** [comment]
The peptide is sequence is not ambiguous (only the protein name). So, there should be no additional scores from that case. That is separate from the case where the peptide ambiguity is at the peptide sequnce level. those scores we want to keep.

**Comment by rmillikin** [comment]
MM no longer calculates e-values
