### ISSUE TITLE
organism specific PTMs

### ISSUE THREAD

**Issue by trishorts** [smith-chem-wisc/MetaMorpheus#864]
for example, this one shows up in human gptmd but "maybe??" should not be included:

Dehydroalanine is a dehydroamino acid. It is a hypothetic molecule that does not exist except as a residue found as a residue in peptides of microbial origin. It is unusual in having an unsaturated backbone.

**Comment by trishorts** [comment]
Bacillosamine is a rare amino sugar first discovered in Bacillus subtilis.[1]

**Comment by stefanks** [comment]
Both of those were confidently identified with more than 10 matches in either the Mouse Islets or Jurkat lysates. I'll try to dig up where I saw them..

**Comment by stefanks** [comment]
In Jurkat Frac12 scan 18964 I am getting a match to AEGSDVANAVLDGADC[Mod:Dehydroalanine from Cysteine]IMLSGETAK, with score 28 and sub-ppm mass error. This peptide is from protein P14618. So both the precursor and some fragment masses correspond to C[Mod:Dehydroalanine from Cysteine].

**Comment by stefanks** [comment]
Bacillosamine is actually not there. The formula is exactly the same as Aspartic Acid+Leucine or Glutamic Acid+Valine. So I'll remove it.

**Comment by stefanks** [comment]
According to Brian "I say yes DHA instead of Cys does make sense occassionally in human samples despite what @trishorts posted from Wikipedia.  The reason is b/c it can occur during sample prep, so even though it does not have a human fxn, we can sometimes see it."

**Comment by stefanks** [comment]
Done in https://github.com/smith-chem-wisc/MetaMorpheus/pull/865
