### ISSUE TITLE
Tidying up DLLs?

### ISSUE THREAD

**Issue by acesnik** [smith-chem-wisc/MetaMorpheus#869]
Is it possible to place all of the DLLs into a subfolder?

Here's Cytoscape below. All of the library files are in the `framework` folder. It's a Java program, so I'm not sure the same thing can be done in MM, but it might be nice to tidy it up a bit and make it harder to accidentally delete a DLL file.
![image](https://user-images.githubusercontent.com/16342951/35309447-36f7c7a8-0072-11e8-9563-7df6b1922d2b.png)

**Comment by acesnik** [comment]
https://stackoverflow.com/questions/2445556/c-sharp-putting-the-required-dlls-somewhere-other-than-the-root-of-the-output

**Comment by zrolfs** [comment]
I liked the end of that answer: "Users wont get confused if you install the application properly in the start menu ;) I never had that problem, including projects with 50+ assemblies. Users simply never see them."

**Comment by rmillikin** [comment]
probably not necessary since we've nixed the portable version. the CMD version still has this problem but I think most people use the installer
