### ISSUE TITLE
Failed search

### ISSUE THREAD

**Issue by Dmorgen** [smith-chem-wisc/MetaMorpheus#870]
Hi,

I've installed metamorpheus 0.0.242.0 on a windows server 2008 R2 Enterprise computer. trying to run a search (HeLa file) I got the following notice:

Run failed, Exception: Could not load file or assembly 'ManagedThermoHelperLayer.dll' or one of its dependencies. The specified module could not be found.

Thanks!
David.

**Comment by stefanks** [comment]
Do you have Thermo MsFileReader installed?

**Comment by Dmorgen** [comment]
yes, both 32 and 64bit version 2.2.62 . please see attached log file.

Thanks!
[results.txt](https://github.com/smith-chem-wisc/MetaMorpheus/files/1660501/results.txt)

**Comment by stefanks** [comment]
Would you try updating it to the current version? 
3.1 SP4
Thanks!

**Comment by Dmorgen** [comment]
will do. thanks!

**Comment by Dmorgen** [comment]
Still doesnt work...
[results.txt](https://github.com/smith-chem-wisc/MetaMorpheus/files/1660565/results.txt)

**Comment by stefanks** [comment]
Could you share the raw data file? I'm trying to replicate the error.

**Comment by Dmorgen** [comment]
here it is:
https://owncloud.incpm.weizmann.ac.il/index.php/s/rUhHcNF23uu67f1

Thanks!

**Comment by stefanks** [comment]
Thanks! While I am looking at this, you can use MsConvert to convert the raw file to (centroided) mzml, and search the converted file.

**Comment by Dmorgen** [comment]
wilco.

**Comment by stefanks** [comment]
Could you try downloading and installing "Microsoft Visual C++ Redistributable" from the bottom of this page?  https://www.visualstudio.com/downloads/
Thanks!
This is a tricky bug

**Comment by Dmorgen** [comment]
will do :)

**Comment by Dmorgen** [comment]
tried to run the mzML file using the default settings. got stuck in the calibrate task stage. got the following message:
currentResult.Ms1List.Count = 0 currentResult.Ms2List.Count = 116813
datapointAcquisitionResult is null
Cannot proceed. No data files selected.

:)

**Comment by Dmorgen** [comment]
works like a charm with the RAW file. thanks!

**Comment by stefanks** [comment]
For the mzML file, are your MS1 scans in profile or centroid mode? With default MSConvert settings, they are in profile mode, and MM can't work with those (yet). You can choose the "pick picking" processing step in MSConvert to have all scans be centroided.

Did the RAW file start working after you installed c++?

Sorry for the buggy operation, we will include the c++ installer in the next version!

Thank you

**Comment by Dmorgen** [comment]
success! the raw file analysis succeeded

**Comment by Dmorgen** [comment]
the mzML is indeed profile. 
the RAW worked after I installed C++. thanks for the help!

**Comment by VotanWarnwitz** [comment]
Hi,
I had the same problem as Dmorgen with the ManagedThermoHelperLayer.dll error message. After installing "Microsoft Visual C++ Redistributable" as recommended (thank you stefanks!), the above error message did not came up again but sadly this one: "Run failed, Exception: Der Index war außerhalb des Arraybereichs" (sorry for the german) which should translate to "Index out of bound/range". 
I recieve this error message after converting the raw-files to mzML as well :/

Here is the results.txt:
[results.txt](https://github.com/smith-chem-wisc/MetaMorpheus/files/1667465/results.txt)

Sorry for the inconvenience

Best,
Franz

**Comment by stefanks** [comment]
@VotanWarnwitz could you share the raw file you are searching? 
Thanks!

**Comment by VotanWarnwitz** [comment]
Here it is:
https://www.dropbox.com/s/zepxs2b6ae8289j/A-M_01-027_VCS.raw?dl=0

Thank you for taking the time and looking into this :D

**Comment by stefanks** [comment]
The culprit seems to be the empty scan 138. Will make a fix shortly!

**Comment by VotanWarnwitz** [comment]
Awesome! Good catch!! Sadly every raw file of my set contained at least one empty spectrum :/ (old machine plus short injection times...). But I just tested a file from our lab with only proper MS2-scans and it worked out perfectly. Thank you again for looking into this and fixing this.
Best,
Franz

**Comment by stefanks** [comment]
The current version includes a fix for crashes on empty scans, as well as an installer (MetaMorpheusInstaller.exe) that includes the c++ redistributables. 

Thanks everyone for reporting issues!
