### ISSUE TITLE
require correct thermo file reader to operate

### ISSUE THREAD

**Issue by trishorts** [smith-chem-wisc/MetaMorpheus#876]
mm should check to make sure users have the correct versions installed and then give a popup warning if they do not. I do not like seeing crash messages. I think many people will simply give up if mm doesn't work on the first try. Especially if they do have another version of file reader installed and think they're doing everything right.

**Comment by trishorts** [comment]
should we also check for that c++ redistributable is also installed?

**Comment by trishorts** [comment]
msfilereader version determined in mzLib/MzLibUtil/SystemInfo.cs in CompleteSystemInfo

**Comment by XRSHEERAN** [comment]
I found a way to warn C++ redistribution  and will try to add it to the MM startup event. This should fix the crash if users do not have the redistributable. But still we have a bundle installer in the release, which install the redistributable before MM (MetaInstaller.exe). I'll continue dig into the reader part.

**Comment by rmillikin** [comment]
I've added a warning upon adding a raw file to the GUI when MSFileReader is not installed, or different version of MSFileReader is installed in #1064 . The run will still proceed if the user ignores the warning and decides to run the tasks. I'd rather not prevent the user from running a task in case the DLLs are in an unexpected directory, or a different version of MSFileReader is installed and is adequate for the desired analysis, or some other unexpected reason. 

This warning is in the GUI, so the command line version will just crash if MSFileReader is not installed. mzLib will describe this crash in that case, though. 

So, technically this crash still exists, but for now I think the initial warning and meaningful crash message are sufficient to not leave the user in the dark. Feel free to reopen this issue and comment if you disagree.
