### ISSUE TITLE
Incorrect Index File May be selected

### ISSUE THREAD

**Issue by dippman** [smith-chem-wisc/MetaMorpheus#905]
Sometimes, if an index file is present in the folder the current task is running in (peptideIndex.ind, fragmentIndex.ind) then the wrong file may be selected (or no file at all) since MetaMorpheus assumes that file has been generated by the current run when in reality that file was from a previous run of MM. 

Check out GenerateIndexes() and GetExistingFolderWithIndices() in SearchTask.cs for more info.

**Comment by stefanks** [comment]
The idea is that indexes from previous runs should be re-usable! Does this make sense in context of this issue?

**Comment by dippman** [comment]
I believe so, however, it right now the method compares the settings of the index parameters for equality and selects the index files in that directory if that is the case.

But in the case that you have multiple DB files in the same directory and the same index parameters for both files, but the index files themselves for each DB are different, would this be problematic?

Or does the equality of the index params mean that the index files themselves will be the same?

**Comment by stefanks** [comment]
> equality of the index params mean that the index files themselves will be the same

Ideally this is the case. If you find a case where this is not true, please report it!
