### ISSUE TITLE
Viewing search results.

### ISSUE THREAD

**Issue by Dmorgen** [smith-chem-wisc/MetaMorpheus#915]
Hi,

I'm trying to visualize the search results, especially the G-PTM-D findings. Peptide shaker does show some of the modifications, but not all and definitely not the amino acid substitution. I have also tried to import the mzID to Scaffold without success. any recommendations? 

Thanks!
David.

**Comment by trishorts** [comment]
We have been and will continue to reach out to the peptide shaker people. Please see https://github.com/compomics/peptide-shaker/issues/276
I think this is in the pipeline but not imminent.

**Comment by trishorts** [comment]
You might be able to speed things along if you chimed in on that issue. I can tell you that the Galaxy-P folks at the University of Minnesota are also pushing this issue.

**Comment by Dmorgen** [comment]
will do, thanks!

**Comment by trishorts** [comment]
Moreover, we have a major cancer project ongoing where amino acid variants and PTM peptides en masse are identified and quantified BUT we haven't worked out how to visual these results in a nice way. We will, but that will require some effort.

**Comment by rmillikin** [comment]
What kind of visualization are you looking for (b and y ions, peak shape, fold-changes)? Maybe we can point you in the right direction, or edit our output for use in your favorite visualization tool. We are trying hard to make our files inter-operable with other software. Or we could make our own visualization tool eventually...

I've had some luck importing our mzID results into Skyline to highlight b and y ions in fragmentation spectra, but I have not tested it extensively. I've also imported FlashLFQ quantification results into Perseus and visualized fold-change results there, just from the plain text .tsv files.

**Comment by Dmorgen** [comment]
@stefanks of course, but that does not allow an easy assessment of the validity of a modification/substitution - especially when dealing with biologically relevant modifications - such as sulfonation or AA substitutions.  Since in many cases, fragmentation doesn't provide full sequence coverage we may either have a compounding of mass shift or erroneous annotation. 
what I'm looking for (@rmillikin ) is a simple annotator that will allow me - 
1. get a feeling of the way the software generates ID of PTMs/mass shifts, and
2. be able to quickly confirm identifications of important finding without going to Xcalibur and annotate spectra manually. I currently favor Byonic for such searches, as the result's annotator allows to quickly confirm IDs.

good to hear about Skyline and Perseus!

Thanks!
David.

**Comment by trishorts** [comment]
Mann group has a very nice annotation sofware that you can install on PC that I've routinely used to look at peak assignment. https://www.ncbi.nlm.nih.gov/pubmed/22888147
It is kinda hard to find. If you can't, send an email and I'll get you a zip copy. It is way better than Protein Prospector. Still not as easy as you'd like.

**Comment by trishorts** [comment]
One student is working on pepxml output, which might go directly into TPP. I'm not sure where that is at.

**Comment by Dmorgen** [comment]
thanks!

**Comment by lonelu** [comment]
I work with pepxml. It is not easy to have a 'right output format' for other viewers like TPP. Especially if you have something new want to show, which maybe not available in other viewers. 
Another way I tried before is to code the drawing function inside MetaMorpheus, which could output the annotated spectrum. This is much easier and more controllable. However, the drawing function relay on other packages and the output figures is limited to certain formats like .pdf or .png.

**Comment by stefanks** [comment]
@Dmorgen Would you try running the search again with the newest MM? I was able to sucessfully import the mzid results into scaffold.

**Comment by Dmorgen** [comment]
the search is already running :)

**Comment by stefanks** [comment]
Version 254!! It will be uploaded momentarily.

**Comment by Dmorgen** [comment]
ahhh....

**Comment by stefanks** [comment]
@Dmorgen I just ran some post-G-PTM-D results though Scaffold , and was able to see some AA substitutions. For example, the I->F annotated in Uniprot http://www.uniprot.org/uniprot/P16521 was successfully discovered by G-PTM-D and annotated by Scaffold. 

![itof](https://user-images.githubusercontent.com/5972770/35704902-8a810862-0766-11e8-9829-ff0ee3119f82.png)

**Comment by Dmorgen** [comment]
@stefanks thanks! can you provide some more information, please? is it the new version you've released? what version of scaffold are you using? what raw file format were the data searched with? did you use the uniprot XML or Fasta as DB?

**Comment by Dmorgen** [comment]
@lonelu can you walk me through on how to generate pepXMLs that will be TPP compatible? one of the goals is to turn MM results into spectral libraries so going through spectraST is something I will have to do anyway...

Thanks!

**Comment by stefanks** [comment]
@Dmorgen yes, it's the the current version, 0.0.255. Using the newest Scaffold version. Uniprot xmls for searching in MM, but had to use FASTAs in scaffold. 

The files are here, including the original RAW (yeast lysate fraction) and the calibrated mzml:
https://uwmadison.box.com/s/8amsis3b27trivhu3a9gsxhx5xozz6qb

You are welcome to try running G-PTM-D and search on this calibrated file, this should not take more than a few minutes!

**Comment by Dmorgen** [comment]
@stefanks Sorry for being a little thick, but I can't seem to get it done. I can't seem to load the XML for the G-PTM-D folder, but I can the mzID. does the G-PTM-D gets integrated into the mzID? if not, how can i upload the XML file?

Thanks!
David.

**Comment by Dmorgen** [comment]
@stefanks  Hi,
I've managed to import the mzID to scaffold, but not the XML file from the G-PTM-D search. Additionally I can't seem to find a way to observe the spectra ID's. is there a way to open the XML files? are they separate from the mzID in their ID content?

**Comment by trishorts** [comment]
He'll be in shortly.. scaffold won't take xml. You'll have to get a fasta with the same sequences and use that. that's what we did. The observed ptms will get read from the .mzid

**Comment by Dmorgen** [comment]
From the mzID? the mzID sums also the G-PTM-D search?

**Comment by trishorts** [comment]
Not totally understanding your shorthand but.... Yes. You can do a G-PTM-D search (which creates a new xml database). Do a final search with the xml database to get the .mzid output. Load that result into scaffold BUT you gotta have a FASTA file SO go back to uniprot or whatever the source of the original xml and get the comparable FASTA file. Does that make sense? Not everyone uses xml yet.

**Comment by rmillikin** [comment]
The G-PTM-D task does not create an mzID I think. G-PTM-D only adds PTMs to the XML database. After that you will need to run a "search task" using the new database to create an mzID, which you can then open with Scaffold. I think that's what you want to do anyway?

1. Calibrate (mass calibration)
2. G-PTM-D (add PTMs to database; the XML written is just the original database with PTMs added to it)
3. Search (make mzID and tsv result files)
4. Open mzID with Scaffold

**Comment by Dmorgen** [comment]
awesome!

**Comment by rmillikin** [comment]
great! and as a clarification, our pepXML output is only for cross-link searches at the moment. we may eventually write pepXML for a typical search but we currently don't.

**Comment by Dmorgen** [comment]
If you do, it'd be great if you could adjust it to a format that can be imported into SpecraST :)

**Comment by trishorts** [comment]
Schema here: http://tools.proteomecenter.org/wiki/index.php?title=Formats:pepXML
looks like we need "probabilities" for it to work in SpectraST (which can come from peptideprophet)

**Comment by rmillikin** [comment]
I'm going to close this and reference issue #1124 for supporting additional output types (e.g., pepXML). mzID validation (and pepXML validation) is also an issue we're interested in (#52).

**Comment by wenbostar** [comment]
We have an open source tool ([PDV](https://github.com/wenbostar/PDV)) which can load result from MetaMorpheus for visualization. Hope it's useful to the users of MetaMorpheus.

**Comment by trishorts** [comment]
Very intriguing. We'll definitely have a go.
