### ISSUE TITLE
Search stalled in new MM version and lengthy searches

### ISSUE THREAD

**Issue by Dmorgen** [smith-chem-wisc/MetaMorpheus#922]
Hi,

I've downloaded the new version and ran a search. search stalled in "picking MS2 spectra". when I shut the run down, I got "index out of range error". the search was done on a single file running a search and G-PTM-D pipeline.

the second question is of slow searches. before downloading the new version i've put a quant set to search running an initial search with wide ppm values and small DB, calibration and then full search and G-PTM-D.
calibration took forever - 3 files took more than 8 hours. the software is installed on a 26 core VM on a Windows Enterprise 2008 R2 version. could that be influencing the search speed? 

Thanks!
David.

**Comment by stefanks** [comment]
@Dmorgen Calibration is an optional step that takes a long time, but once you have calibrated files there is no need to re-run the calibration again! Just use the output mzmls in any subsequent searches.

Regarding the "loading ms2 scans" taking a long time, you can uncheck "Deconvolute Precursors" in the search task window.

**Comment by rmillikin** [comment]
Calibration is much faster in v0.0.275. Please give that a shot. A yeast lysate from a Velos took me ~6min and a Jurkat fraction took me ~15min. If you're still getting performance problems please feel free to make a new issue.
