### ISSUE TITLE
MM Crash on Contaminants

### ISSUE THREAD

**Issue by zrolfs** [smith-chem-wisc/MetaMorpheus#940]
When checking a database as contaminant and then adding any file (MS, db, toml), MM crashes in MainWindow.xaml.cs, ln 340 "dataGridXMLs.Items.Refresh();" throwing "System.InvalidOperationException: "Refresh" is not allowed during an AddNew or EditItem transaction."

**Comment by rmillikin** [comment]
fixed in #993
