### ISSUE TITLE
Search task stalls in the MS2 spectra import of the 1st file, after calibration and G-PTM-D tasks on ver 260

### ISSUE THREAD

**Issue by Dmorgen** [smith-chem-wisc/MetaMorpheus#946]
Hi,
I'm running a Quant set of 12 samples of mixed Ecoli and HeLa cells. 
Data was calibrated initially using Ecoli and Human Uniprot XMLs, and Crap 2.0 Fasta file.
following calibration, G-PTM-D was run using the resulting mzMLs
Then a search was set to run on the G-PTM-D XMLs. this stage failed. I then re-run the search using mzMLs and XML DBs and got the error message attached in the enclosed file. 
[results.txt](https://github.com/smith-chem-wisc/MetaMorpheus/files/1727024/results.txt)

you can download all of the data and searches done using this link:
https://owncloud.incpm.weizmann.ac.il/index.php/s/YFsMDDz8DdMAgLa

Thanks!
David.

**Comment by zrolfs** [comment]
Hi David,
The crash appears to be from an issue with .xml databases and semi-trypsin digestion. We are working on a fix, but in the meantime switching your digestion from "semi-trypsin" to "trypsin" should allow you to run the search.

Thanks for finding that!
Zach

**Comment by zrolfs** [comment]
Another workaround may be to use "trypsin" digestion, but change the "Search Mode" from "Classic Search" to "NonSpecific Search".  This should yield semi-tryptic peptides, but NonSpecific Search is a newer feature that could use more testing. If you run into RAM issues, simply increase the "Number of Database Partitions".

**Comment by Dmorgen** [comment]
Crashed again using Trypsin only search
[results.txt](https://github.com/smith-chem-wisc/MetaMorpheus/files/1729192/results.txt)

**Comment by zrolfs** [comment]
Thanks for your patience! Could you post the .toml that you used for the trypsin only crash?

**Comment by Dmorgen** [comment]
sure!
[SearchTaskconfig.zip](https://github.com/smith-chem-wisc/MetaMorpheus/files/1729343/SearchTaskconfig.zip)

**Comment by zrolfs** [comment]
I was unable to reproduce the crash using your toml, spectra file "QEP1_Spikeln_230914_1_3ng_270914-calib.mzml", and databases "crap_2.0GPTMD.xml" and "Ecoli_UP_Jan2018-Human_UP_Jan2018GPTMD.xml" obtained from 2018-02-09-22-45-43. Can you confirm that these inputs are correct?

**Comment by Dmorgen** [comment]
Correct. the search goes on for a while, but then after an undetermined time I get the error message.

**Comment by Dmorgen** [comment]
@zrolfs did you do classic or modern search?

**Comment by zrolfs** [comment]
I did a modern search, since that is what your toml specified. The database is somewhat large, so using multiple partitions can increase the speed of modern search. I would recommend 4-8 in the future, but I used 1 to try to reproduce the crash. You can view/download the results here: https://uwmadison.box.com/s/6f6chm2vuuhgga86xmzyk4ix5kndt24c

**Comment by rmillikin** [comment]
I'll give this a shot on my machine to see if I can reproduce your crash. We're focusing on making MetaMorpheus more stable over the next month, so your help is greatly appreciated!

**Comment by Dmorgen** [comment]
Trying again with more partitions and parallel processes. so far so good,

**Comment by Dmorgen** [comment]
it finished successfully with 8 partitions and 8 parallel processes.

**Comment by rmillikin** [comment]
Glad it worked for you - we'll still continue investigating the crash and report back.

**Comment by rmillikin** [comment]
I may have found the source of this Index Out Of Range Exception in Modern Search. It'll be in 0.0.265. If you encounter this bug again in 0.0.265, please either reopen this issue or open a new one and we can take a look.
