### ISSUE TITLE
File Specific Tolerances yielded fewer PSMs

### ISSUE THREAD

**Issue by zrolfs** [smith-chem-wisc/MetaMorpheus#949]
Analyzing dmorgen's data with default precursor/product tolerances of 5/20 yield 23662 PSMs, but using the calibration suggested tolerances of 6.8/42.07 yield only 21242 PSMs.

Spectra: QEP1_SpikeIn_230914_1_3ng_270914-calib.mzml
Databases: crap_2.0GPTMD.xml AND Ecoli_UP_Jan2018-Human_UP_Jan2018GPTMD.xml
Toml and filespecific tomls below.

**Comment by zrolfs** [comment]
[SearchTaskconfig.txt](https://github.com/smith-chem-wisc/MetaMorpheus/files/1732788/SearchTaskconfig.txt)

**Comment by zrolfs** [comment]
[QEP1_SpikeIn_230914_1_3ng_270914-calib.txt](https://github.com/smith-chem-wisc/MetaMorpheus/files/1732791/QEP1_SpikeIn_230914_1_3ng_270914-calib.txt)

**Comment by trishorts** [comment]
i guess that it might be variable b/c the score cutoff for global search and individual file search will be different.

**Comment by zrolfs** [comment]
There was only one file searched, so there should be no disparity.

**Comment by trishorts** [comment]
might point to unexpected parameter override (.e.g changed tolerance). could be a bug.

**Comment by rmillikin** [comment]
Is the problem just that the suggested ppm tolerances give worse results than the default tolerances? or some other bug?

**Comment by zrolfs** [comment]
Correct. The suggested ppm tolerances give worse results than the default tolerances.

**Comment by rmillikin** [comment]
@zrolfs  please check to see if this issue persists in 0.0.262?

**Comment by rmillikin** [comment]
Confirmed this is still an issue in 0.0.262.

Before calib: 8214 PSMs within 1% FDR
After calib: 6842 PSMs within 1% FDR

**Comment by rmillikin** [comment]
Merged with #518

**Comment by zrolfs** [comment]
I think these are separate issues; may need to keep an eye out that consistency and increased psms are both resolved.
