### ISSUE TITLE
Crash when .toml containing post-calibration ppm suggestions are dragged into GUI

### ISSUE THREAD

**Issue by rmillikin** [smith-chem-wisc/MetaMorpheus#951]
When the .toml containing the suggested PrecursorMassTolerance and ProductMassTolerance for a specific calibrated .mzml is dragged into MM, a crash results

**Comment by zrolfs** [comment]
Yep! Those tomls shouldn't be dragged into the GUI, as they are file specific.

**Comment by rmillikin** [comment]
This .toml should not be allowed to be added to the GUI (it is automatically read if it is available)

**Comment by zrolfs** [comment]
It is difficult to handle that gracefully. Perhaps a check rejects the toml if it does not contain the string "Common Parameters"?

**Comment by rmillikin** [comment]
That's fine - a check for elements that are supposed to be there. Some kind of error message in the "Warnings" that simply says this type of .toml isn't supposed to be dragged into the GUI should result, not a crash.

**Comment by rmillikin** [comment]
Here is an example
[02-15-17_YL-stnd_old-heat-calib.zip](https://github.com/smith-chem-wisc/MetaMorpheus/files/1745819/02-15-17_YL-stnd_old-heat-calib.zip)

**Comment by rmillikin** [comment]
fixed in #992
