### ISSUE TITLE
Validate digestion space

### ISSUE THREAD

**Issue by rmillikin** [smith-chem-wisc/MetaMorpheus#954]
Rachel observes that when we digest our protein database, we see that 90+% of proteins contain a unique peptide (a peptide that can be a digestion product of only that protein). This number is consistent across proteases. Experimentally, this number is only 50%. 

Are we digesting our database correctly? Or are shared peptides simply more abundant and thus more likely to be observed?

**Comment by zrolfs** [comment]
Wasn't the 90% number calculated using up to 2 missed cleavages? We mostly observe no missed cleavages, which may have more overlap. Did she include proteolytic cleavages? More information about the digest is needed. I agree that shared peptides are more likely to be observed, as they are more abundant by a factor of the number of shared proteins, but the discrepancy seems high.

**Comment by rmillikin** [comment]
I think she tried it with no missed cleavages and got that ~90% number

**Comment by zrolfs** [comment]
What percent of peptides are unique? This might be a closer answer to our experimental observation, because we don't get full coverage of every protein that we identify. This will need to be calculated on a length basis, as shorter peptides will rarely be unique and longer peptides are much more likely to be unique.

**Comment by trishorts** [comment]
what unit tests do we have specifically for digestion? I saw different digestions used in classic and modern search tests, but only with simple peptides. I didn't see anything really to get to all the possibilities of digestion.  Also didn't see test for each of the different proteases.

**Comment by rmmiller22** [comment]
For Trypsin using Uniprot database that contains 71,785 proteins with minimum peptide length of 5 and no max set
- 2 missed cleavages: 89.42% of proteins contain at least 1 unique peptide
- no missed cleavages: 77.78% of proteins contain at least 1 unique peptide

**Comment by rmmiller22** [comment]
Additionally, for the same set of conditions:
2 missed cleavages: 27.33% of all peptides are unique (not excluding duplicates in total count)
0 missed cleavages: 25.04% of all peptides are unique (not excluding duplicates in total count)

**Comment by zrolfs** [comment]
Can you clarify the minimum and maximum length allowed? ie the peptide "K" is ~6% of all peptides, but is never observed in proteomics.

**Comment by rmmiller22** [comment]
The minimum peptide length is 5 and I have not set a maximum length allowed.
