### ISSUE TITLE
Note in the readme which of the growing number of releases to choose for first-time users

### ISSUE THREAD

**Issue by acesnik** [smith-chem-wisc/MetaMorpheus#955]

**Comment by acesnik** [comment]
- Mostly referring to the first line: Download the current version at https://github.com/smith-chem-wisc/MetaMorpheus/releases.
- Something like this line would probably be more helpful: Download the latest MetaMorpheusInstaller.exe release, and install MetaMorpheus.

**Comment by rmillikin** [comment]
Done
