### ISSUE TITLE
append toml to results.txt in error report

### ISSUE THREAD

**Issue by trishorts** [smith-chem-wisc/MetaMorpheus#959]
that might help us with the debugging.

**Comment by rmillikin** [comment]
done in #1009

**Comment by zrolfs** [comment]
Can you clarify how this was implemented? Does it print out the toml that was given to it, or the parameters that it had at the time of the error?

**Comment by rmillikin** [comment]
It retrieves the .toml for the task that crashed (its folder, specifically), reads it, and appends it to the end of the email
