### ISSUE TITLE
warning for incorrect version of msfilereader when loading .raw files

### ISSUE THREAD

**Issue by trishorts** [smith-chem-wisc/MetaMorpheus#968]
We could warn people that some users experience instability/crashes when loading thermo raw files with msfilereader versions other than 3.0 sp2

**Comment by rmillikin** [comment]
This is has been a consistent problem over the entire lifespan of MetaMorpheus and I'd really like to get a robust solution in place. I think it should be one of our top priorities.

This issue already exists though (#876), so I'm going to close this. Sheeran will be working to solve this problem but I suspect he will need help from all of us to ensure this crash is captured from all angles
