### ISSUE TITLE
Support .fasta.gz and .mzml.gz

### ISSUE THREAD

**Issue by trishorts** [smith-chem-wisc/MetaMorpheus#998]
MM assumes compressed must be xml. Not the case. When this gets fixed, let's make it so we can take compressed .raw and .mzml as well.

**Comment by rmillikin** [comment]
several crashes related to .gz extensions fixed in #999 

supporting .fasta.gz and .mzml.gz will come later

**Comment by rmillikin** [comment]
see #1124
